### ISSUE TITLE
Do we need a built-in yaml filter?

### ISSUE THREAD

**Issue by Kijewski** [djc/askama#1002]
I don't really see a compelling use case for a built-in yaml filter. It's a serialization format widely used for input configurations, not for generated web output. The feature was asked for in #192, and it was added in #201.

The package serde_yaml is now marked as [deprecated and unmaintained](https://github.com/dtolnay/serde-yaml/commit/3ba8462f7d3b603d832e0daeb6cfc7168a673d7a) by its author. If we keep the feature, then maybe we should look around if there is an active fork of the project?

Cc @antifuchs.

**Comment by GuillaumeGomez** [comment]
I think it's "easy enough" to add your own `yaml` filter if needed. Seems to be out of scope of `askama`.

**Comment by djc** [comment]
That's fair -- let's kill it.

**Comment by GuillaumeGomez** [comment]
Sending a PR to remove it then. :3

**Comment by antifuchs** [comment]
Fine by me to kill the feature - I honestly had to look up what askama even was, it's been so long that I used the tool that I built using it ((:
