### ISSUE TITLE
Template compilation infinite loop / failed cycle detection

### ISSUE THREAD

**Issue by and-reas-se** [djc/askama#1004]
Hello,

I ran into the same bug as is reported is issue #515. That issue was closed as solved in 2021, with some cycle detection added in, but I have a simple case the cycle detection fails to trigger on.

The following project will reproduce it, running cargo build never halts.

`src/lib.rs`:
```rust
use askama::Template;

#[derive(Template)]
#[template(path = "page.html")]
pub struct Page;
```

`templates/base.html`:
```
{% extends base.html %}
```
`templates/page.html`:
```
{% extends base.html %}
```

**Comment by GuillaumeGomez** [comment]
Is `page.html` necessary to trigger it?

**Comment by and-reas-se** [comment]
Yes, if you do `path = "base.html` in `lib.rs the cycle detection triggers properly.

**Comment by GuillaumeGomez** [comment]
Interesting. Checking what's going on.

**Comment by GuillaumeGomez** [comment]
Opened https://github.com/djc/askama/pull/1005. Thanks for the detailed issue! :)
