### ISSUE TITLE
empty struct fails with proc macro

### ISSUE THREAD

**Issue by drahnr** [djc/askama#101]
Hi djc,

not sure if this is a general rust issue or an implementation detail in askama (I might be just too silly to pass the right terms to my fav search engine).

```
#[derive(Template)];
struct Index; // no struct members
```

```
error: proc-macro derive panicked
  --> src/main.rs:18:10
   |
18 | #[derive(Template)]
   |          ^^^^^^^^
   |
   = help: message: derive(Template) only works for struct items

error: aborting due to previous error

error: Could not compile `cantaloupe`.

To learn more, run the command again with --verbose.
```
---

```
$ rustc --version
rustc 1.27.0 (3eda71b00 2018-06-19)
```

**Comment by djc** [comment]
This is Askama-specific. It probably works if you make it `struct Index {};`?

**Comment by drahnr** [comment]
Yes indeed! Adding `{}` makes it compile (if I also add either a `new` or `default` impl since `Index.render().unwrap()` won't work anymore).

**Comment by djc** [comment]
You can similarly do `Index {}.render().unwrap()` (maybe needs some extra parentheses).

**Comment by drahnr** [comment]
True, didn't think of that.

**Comment by djc** [comment]
So I've decided to lift the restrictions here, so you can now use any kind of struct as the context.

**Comment by djc** [comment]
And thanks for reporting!

**Comment by drahnr** [comment]
Awesome, thank you! As, always, incredible turnaround times :)

**Comment by djc** [comment]
It helps that we're timezone-aligned 😊
