### ISSUE TITLE
When using askama_axum, the automatic import of IntoResponse will preferentially import from askama_axum instead of axum::response.

### ISSUE THREAD

**Issue by rendaoer** [djc/askama#1047]
When using askama_axum, the automatic import of IntoResponse will preferentially import from askama_axum instead of axum::response.
<img width="367" alt="image" src="https://github.com/djc/askama/assets/46780118/0f985d5f-a858-42fe-a1c7-3f133657b231">

**Comment by djc** [comment]
This doesn't seem very actionable? I'm not sure what we could do about it.

**Comment by rendaoer** [comment]
好像确实没什么办法╮ (╯▽╰)╭

**Comment by djc** [comment]
I don't understand that.

**Comment by Kijewski** [comment]
It's fixed in main. askama_axum only exports axum_core, not any symbols in it.
