### ISSUE TITLE
Using block fragments as part of larger template

### ISSUE THREAD

**Issue by eliasgranse** [djc/askama#1049]
I am trying to use the feature called "block fragments" as described in the [book, section "Block Segments"](https://djc.github.io/askama/template_syntax.html#block-fragments). The block fragment I am trying to create is part of a larger template and the Rust code looks like this:
```rust
#[derive(Template)]
#[template(path = "pages/index.html", block = "my_block")]
pub struct MyTemplate {}
```
However the line `#[derive(Template)]` stops on the error:
```
unsupported attribute key Ident { ident: "block", span: #0 bytes(16214..16219) } found
```
Looking at the [Docs.rs](https://docs.rs/askama/0.12.1/askama/index.html#the-template-attribute) documentation this feature is not documented which makes me think this is not supported for some reason.

Anyways, I cannot seem to figure out what I am doing wrong. Thanks!

**Comment by djc** [comment]
The block fragment feature hasn't been released yet. See #1035 for release planning -- you could use main for now.

**Comment by eliasgranse** [comment]
I see thanks for responding so quickly!

**Comment by Astralchroma** [comment]
I've just been tripped up by this as well. Perhaps don't include features in the book that don't actually exist yet, or at least a warning?

**Comment by matjazonline** [comment]
PR here https://github.com/djc/askama/pull/1084
