### ISSUE TITLE
Add  `elif` keyword

### ISSUE THREAD

**Issue by FalkWoldmann** [djc/askama#1056]
Hi,

we recently migrated from Tera to Askama and overall it was quite straightforward. One thing that did not work out of the box was the `elif` keyword, so it would be nice to include that. In addition, `elif` seems to be [supported by jinja](https://jinja.palletsprojects.com/en/3.1.x/templates/#if).

**Comment by djc** [comment]
I guess I'm open to having that added as an alias for `else if`.

**Comment by GuillaumeGomez** [comment]
Ah cool. :D
