### ISSUE TITLE
How to organize templates for multi page application?

### ISSUE THREAD

**Issue by soqe** [djc/askama#106]
During creating my actix-web + askama project I got the problem: I need different structs to be used together. For example, I need to render stuff like articles data, auth data, exchange rates or anything else. I need one big "backbone" struct that will represent my template? I don't think it's good way to organize templates like that. I also have tried using template inheritance, but I don't know how to implement all of that the way with "_parent" fields only.

**Comment by djc** [comment]
This is a little vague, so I'm not sure what to recommend. Can you give a more concrete example?

You don't need `_parent` fields any more, so I would recommend against using them (I'll probably deprecate them in a future release.)

If you set up your data structures in a structure that feels right to you, we can probably get Askama to work with that (that's an important theory about Askama's design, at least).

**Comment by soqe** [comment]
Let's assume I have the next structure of my templates directory:

- src/
  - templates/
    - article/
      - get.html  -- Render entry from a database
      - add.html -- Render form with adding new entry 
      - edit.html -- Render editing form
    - user/
      - get.html      -- Render info about user
      - signup.html -- Render signup form
      - signin.html  -- Render signin form

For every .html file listed above, I have unique Rust struct. For example, for signin.html I have following struct:
```#[derive(Clone, Debug, Serialize, Deserialize, Template)]
#[template(path = "user/edit.html")]
pub struct EditUserTemplate { pub name: Option<String>, }
```
So, every template contains it's own set of fields. 

But from site's user perspective, while I want to read an article, I also want to know that I was logged in, or else see the form which authenticates me on site, or see some other info, which doesn't represent by same structure as getting article template(there is no fields). But from server perspective, each request handler can return only one template which then will be seen to the user. So, the question is, how using askama I can return a full page with all information that will be need to the user?

**Comment by djc** [comment]
Yeah, I think what you want to is use inheritance. That is, write a base template that has all your chrome (login info, authentication form, some other info) in blocks that a child template can fill in. Then, your `user/edit.html` will `extend "base.html"` and fill in those content blocks. The `EditUserTemplate` can gain any number of fields that hold the required data, or a single field that is a sort of meta type to hold all that info needed to fill the page chrome.

Does that make sense?
