### ISSUE TITLE
Lazy loading or runtime templates

### ISSUE THREAD

**Issue by baron-digit** [djc/askama#1078]
Hi,

Is there a way to switch from compile time loading of the templates to runtime (similar to tera) if needed?

I like askama's syntax better, but for flexibility reasons (e.g. updating just the response templates with the front end team) it would be awesome to have a possibility to switch whenever needed.

Thanks in advance for your support.

**Comment by GuillaumeGomez** [comment]
You can use `rinja_parser` and then generate the code from there if you want?

**Comment by djc** [comment]
See #491. @GuillaumeGomez I don't see how the use of rinja_parser helps compared to using askama_parser. (This is Askama's issue tracker, not rinja's.)

**Comment by GuillaumeGomez** [comment]
Oh wow sorry, I meant `askama_parser`... Didn't pay attention to the repository.
