### ISSUE TITLE
Issue with HTML escaping

### ISSUE THREAD

**Issue by Gefn** [djc/askama#112]
I have a string, the value of which is `2/4`. I'm trying to print it in my template using the following syntax:
```
Signature {{ signature }}
```

And I obtain the following:
```
Signature 2&#x2f;
```

I tried safe/escape filters, though it didn't help.

**Comment by yoshrc** [comment]
`safe` filter seems to work.

src/main.rs:

```rust
#[macro_use]
extern crate askama;

use askama::Template;

#[derive(Template)]
#[template(path = "test.html")]
struct TestTemplate<'a> {
    signature: &'a str,
}

fn main() {
    let template = TestTemplate { signature: "2/4" };
    println!("{}", template.render().unwrap())
}
```

templates/test.html

```
<!doctype html>
<html><body>Signature {{ signature|safe }}</body></html>
```

output of cargo run:

```
<!doctype html>
<html><body>Signature 2/4</body></html>
```

**Comment by Gefn** [comment]
You won't believe how stupid I am. I was printing `template` instead of `template.render().unwrap()`. Sorry for the non-issue... And thanks for pointing me the right direction !
