### ISSUE TITLE
[Question] Changing delimiters?

### ISSUE THREAD

**Issue by lukehsiao** [djc/askama#121]
With the template delimieters as `{{` `}}` `{%`, etc., is there a way to use askama in content that heavily uses these curly braces and `%`? For example, if I wanted to use askama to template a LaTeX section like this:
 
 Trying to template `name.last`
 
 ```tex
 \newbibmacro{name:bold_author}{%
   \ifthenelse{\equal{\namepartfamily}{ {{name.last}} }}%
     {\textbf{\ifblank{\namepartgiven}{}{\namepartgiveni\space}\namepartfamily}}%
     {\ifblank{\namepartgiven}{}{\namepartgiveni\space}\namepartfamily}%
   \ifthenelse{\value{listcount}=1 \AND\value{liststop}=2}%
     {\space and\space}
     {\ifthenelse{\value{listcount}<\value{liststop}}%
       {\addcomma\space}
       {}
     }
 }
 ```
 
 I would assume that this would fail due to the conflicting use of `{}` and `%`.
 
 Using jinja's options in Python, I am able to switch delimiters:
 
 ```python
 block_start_string='~<',
 block_end_string='>~',
 variable_start_string='<<',
 variable_end_string='>>',
 comment_start_string='<#',
 comment_end_string='#>',
 ```
 
 which allows me to make a template that looks like the following and parses correctly:
 
 ```tex
 \newbibmacro{name:bold_author}{%
   \ifthenelse{\equal{\namepartfamily}{ <<name.last>> }%
     {\textbf{\ifblank{\namepartgiven}{}{\namepartgiveni\space}\namepartfamily}}%
     {\ifblank{\namepartgiven}{}{\namepartgiveni\space}\namepartfamily}%
   \ifthenelse{\value{listcount}=1 \AND\value{liststop}=2}%
     {\space and\space}
     {\ifthenelse{\value{listcount}<\value{liststop}}%
       {\addcomma\space}
       {}
     }
 }
 ```
 
 Is similar functionality possible in askama, or am I stuck? Is it impossible to use askama in templates that already use curly braces and percentage signs?

**Comment by djc** [comment]
It is possible, but it has not been implemented. Since a few releases there is a per-crate configuration file that we could stick the configuration in, but wiring that up to the parser would need some work.

Would you be interested in working on that? If not, maybe @botika would like to help?

**Comment by botika** [comment]
Nice to help! You can assign it to me now.

**Comment by djc** [comment]
I can't assign it to you, but feel free to take it. :+1: The trick here will be to figure out how to parametrize the parser's input type with the configuration.

**Comment by botika** [comment]
I've seen it xD, anything that I do not see clearly I mention it for gitter.

**Comment by djc** [comment]
Your work so far is great, I have confidence you can figure out most of it! Much appreciated.

**Comment by djc** [comment]
This has been implemented, thanks to @botika for getting it done!

**Comment by lukehsiao** [comment]
This looks great, thanks for considering this feature addition. I'm excited to try it out in one of my projects.

**Comment by lukehsiao** [comment]
@botika 

I'm getting the following error when trying to set a custom syntax:

```
thread 'main' panicked at 'bad delimiters block_start: ~<, comment_start: <#, expr_start: <<, needs one of the two characters in common', /home/lukehsiao/.cargo/registry/src/github.com-1ecc6299db9ec823/askama_shared-0.7.2/src/lib.rs:151:13
```

My `askama.toml` contains

```
[general]
# Directories to search for templates, relative to the crate root.
dirs = ["templates"]

[[syntax]]
name = "latex"
block_start = "~<"
block_end = ">~"
comment_start = "<#"
comment_end = "#>"
expr_start = "<<"
expr_end = ">>"
```

I'm left a little confused since the error suggests a character must be shared, which in my case is `<`. Do you have any pointers?

**Comment by lukehsiao** [comment]
Given multiple custom syntaxes like in the docs examples:

```
[general]
default_syntax = "foo"

[[syntax]]
name = "foo"
block_start = "%{"
comment_start = "#{"
expr_end = "^^"

[[syntax]]
name = "bar"
block_start = "%%"
block_end = "%%"
comment_start = "%#"
expr_start = "%{"
```
Is there an example or documentation of how to use different syntax for different template files?

**Comment by djc** [comment]
@lukehsiao glad you managed to figure things out! I'll see if we can improve the error message.
