### ISSUE TITLE
Feature request: loop.last

### ISSUE THREAD

**Issue by casey** [djc/askama#130]
It might be useful to add `loop.last`, which would be true iff this was the last iteration of the loop. I needed it in order to add separators between items, but not after the last item.

It could be implemented using [`Iterator::peekable`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.peekable). If `peek` returns `None`, then `loop.last` is true.

**Comment by djc** [comment]
Oh, that's a neat technique, and would definitely be nice to have. I'll see if I can implement it some time, unless you'd like to have a go at it?

**Comment by casey** [comment]
I wish I could, but I'm a bit swamped with work right now T_T
