### ISSUE TITLE
User-defined escaping

### ISSUE THREAD

**Issue by lukehsiao** [djc/askama#136]
**Feature Request**:
Would it be possible to allow users the ability to define a custom escape mapping in the `askama.toml`, similar to how a user can define a custom syntax? 

I'm not entirely sure what this would look like so this issue is just a place to discuss the idea.

**Comment by lukehsiao** [comment]
I believe it should be more general that just triggering on the same characters that are currently escaped in html. 

> On the other hand, the current architecture/interface is sort of built on the notion that different file types need different escaping modes, so that seems the most clean way to plug in. 

This is the idea I think is important. Almost all the templating engines (especially for Rust) mainly look at HTML templates. It would be great to be able to use askama for more general applications. For example, the project I'm looking at right now is templating markdown and LaTeX. In the LaTeX case, I might want to escape special latex characters (e.g. `&` to `\&` or `$` to `\$`, but not escape these when outputting the same strings to the markdown template. It would be nice to have some way of defining this mapping, and being able to give it a specific name like we can do with the syntaxes.

**Comment by djc** [comment]
In that case I think there is a relatively straightforward solution. I propose that we indeed define another table structure in the configuration, which could look something like this:

```rust
[escape.latex]
filter = "latex_mod::escape"
extensions = ["tex"]
```

This will enable the `latex` escape mode automatically for extensions with the extension `tex` (it is an error to create escape modes with overlapping extensions or to define escape modes with names that conflict with the built-in `html` escape mode). Askama will call the named function when content needs to be escaped (that is, when `AsRef<str>`-type content is injected into the template output); it is on the template user to make sure that the escape function or module is in scope of template context types.

Does that sound right?

**Comment by djc** [comment]
This is probably nice-to-have for 0.8, and might not make it.

**Comment by botika** [comment]
We can use https://doc.rust-lang.org/cargo/reference/build-scripts.html#case-study-code-generation for generate `fn escape` and include in `askama_escape/src/lib.rs`. To generate this function, I have built this macros [`new_escape`](https://github.com/rust-iendo/v_htmlescape/blob/any_escape/v_htmlescape/src/lib.rs#L14-L17) 

```
new_escape!(
    HTMLEscape,
    "60->&lt; || 62->&gt; || 38->&amp; || 34->&quot; || 39->&#x27; || 47->&#x2f; || "
);
```
Than through the syntax "`$u8->$quote || `" generate the `Escaped` structure with any pair.

You can write from askama.toml and have the most common, (latex, html, etc,) saved.

That is to say, 
- generate from the `build.rs` and `askama.toml` the `escape` function in `env!("OUT_DIR"), "/escape_function.rs"`
- add in `askama_escape/src/lib.rs` next line 
```
include!(concat!(env!("OUT_DIR"), "/escape_function.rs"));
```

- remove old escape function

How about?

**Comment by botika** [comment]
About the options that you told me, rocket included, I attached the [benches report](https://travis-ci.org/rust-iendo/v_htmlescape/jobs/471206133) with the comparison with the current one, rocket and v_escape. 

So it would, be logical, on the configuration table adding the options to create the escape function using v_escape.

@djc Can you tell me what you think?

**Comment by botika** [comment]
On the other hand, there is a cyclical dependence between askama_shared (`Config`) and askama_escape (`MarkupDisplay`) that they forced me to do another refactor.

**Comment by djc** [comment]
See #197.
