### ISSUE TITLE
Conditional Parent Templates

### ISSUE THREAD

**Issue by gregelenbaas** [djc/askama#137]
Hi there. First, thank you for your work on Askama, it is a great project that I hope I can contribute to! 

Anyway, I've been reading the docs for a few days and from I've read it doesn't seem like it is possible to conditionally extend a template from a parent template, or to extend it differently, or to just render the child. I would conditionally like to render an html template as part of an html document, or as an escaped string in a json object. `Is this something that is on the roadmap? I would be interested in helping with it.

**Comment by djc** [comment]
Happy that you like it, any contributions would be welcome!

I'm not sure conditional parent templates would fit well with how the code is compiled. Maybe you could solve this using `include`s, which can be done conditionally, or macros?

**Comment by gregelenbaas** [comment]
Thanks for the quick response. I think Includes will work for now. Was looking for something like the Null-Master Fallback technique described here: http://jinja.pocoo.org/docs/2.10/tricks/ but looking at the generator code, I'm not quite sure how it would be done. I'll try to think if I can come up with any proposals.
