### ISSUE TITLE
[2018 branch] uri! macro from Rocket 0.4 leads to panic in proc-macro

### ISSUE THREAD

**Issue by mjanda** [djc/askama#174]
Seems to my that new typer URIs from Rocket 0.4 don't work in askama templates when they contain any parameters.

Simple `uri!`s without parameters work.

`{{ uri!(crate:foo::bar: foo = bar) }}` will lead to:

```
... proc-macro derive panicked
... message: unable to parse template:
```

**Comment by djc** [comment]
(Note that the 2018 branch has been merged into master already.)

Oops, I guess our parsing for Rust macro (as opposed to template macro) arguments is a little too restrictive to handle what's actually allowed in macros (and thus expected to work for users).

To be exact, the [`rust_macro` parser](https://github.com/djc/askama/blob/master/askama_derive/src/parser.rs#L431) uses the [`arguments` parser](https://github.com/djc/askama/blob/master/askama_derive/src/parser.rs#L274), but that only accepts a comma-separated list of simple expressions.

Widening that enough could be tricky... perhaps the Rust macro support should just pass through all the tokens unparsed?

**Comment by botika** [comment]
@djc It's like you say.

I leave you two options, detecting nested parentheses #176 or a more complicated invocation end `);` #178 .

For me the best option is the #178.

**Comment by djc** [comment]
@botika great work! Why do you prefer the latter option? It seems to me that, while the former is maybe a bit more code (and this uglier), it might also be more correct (since ultimately `);` can also appear in macro arguments). Or am I missing something?

**Comment by botika** [comment]
If you have the argument "(" we would have an unexpected error. In the last there is not this problem.

**Comment by botika** [comment]
Thanks for reporting.

**Comment by mjanda** [comment]
Thank you, you're wonderful
