### ISSUE TITLE
Gotham IntoResponse feature?

### ISSUE THREAD

**Issue by rakenodiax** [djc/askama#175]
My favorite stack includes both this crate and the `gotham` web framework. It'd be awesome to have an implementation of its `IntoResponse` trait to make rendering that much simpler and ergonomic. I'm happy to work on this feature and submit a pull request, but wanted to make sure this would be of interest as a crate feature.

**Comment by djc** [comment]
Sure, bring it on! Search for "rocket" or "iron" to see all the pieces on how to put it all together.

**Comment by botika** [comment]
Gotham is a hyper wrapper, really functionality is not Gotham but hyper. So it would make more sense in the feature `with-hyper`. The current implementation #179  , removing the references to Gotham, would work for both Hyper and Gotham cases.

**Comment by rakenodiax** [comment]
@botika The distinction is that `gotham::IntoResponse` is not implemented for `Into<hyper::Response<hyper::Body>>`, so if `Template` were to implement the latter instead, `Template::into` would have to be called manually:

```rust
struct FooBar;

impl Into<hyper::Response<hyper::Body>> for Foobar { ... }

fn hello(state: State) -> (State, impl IntoResponse) {
    (state, FooBar{}.into())
}
```

**Comment by botika** [comment]
Ok, thanks
