### ISSUE TITLE
Print deprecation notices when using _parent field

### ISSUE THREAD

**Issue by djc** [djc/askama#180]
I want to remove the special handling for `_parent` fields, but it would be nice to have one version where these still work but generate some sort of warning from the compiler. It appears there's no nice way to print deprecation notices from procedural macros, so I suppose we should just print a note to `stderr` that maybe is formatted a little bit like a compiler warning.

**Comment by botika** [comment]
We can use [librustc-errors](https://github.com/rust-lang/rust/blob/master/src/librustc_errors/lib.rs#L664). 
```rust
if parent.is_some() {
   emit(...);
}
```

How about?

**Comment by djc** [comment]
Sounds great! Is that crate available from crates.io?

**Comment by botika** [comment]
It is not available in crate. I have made a small version.
