### ISSUE TITLE
allow white spaces before and after the pipe symbol when using filters

### ISSUE THREAD

**Issue by joekyo** [djc/askama#186]
Thank you for creating this great library, I enjoy quite a lot when I use it.
I found that `{{ hello|uppercase }}` works, while `{{ hello | uppercase }}` doesn't work, and the document doesn't mention about this limitation.
Could you please add support to allow one or more white spaces exist before and after the pipe symbol.
I mean the white space character `0x20`, no need to support `\t`, `\r`, `\n` and alike though.

**Comment by djc** [comment]
Thanks for the bug report!

Unfortunately this cannot be fixed as you propose, because `|` is also a valid operator, and so `hello | uppercase` would be parsed as the binary xor of `hello` and `uppercase`.
