### ISSUE TITLE
Publishing 0.8 to Cargo and general timeline question

### ISSUE THREAD

**Issue by gregelenbaas** [djc/askama#191]
Hey there, 
I'm not sure this is the right place, but wanted to ask when 0.8 will be published to cargo? Currently only 0.7.2 is up on Cargo. 0.8 has a critical fix for me #133. Thank you!

**Comment by djc** [comment]
I've started drafting release notes:

https://github.com/djc/askama/releases/tag/untagged-8175a7cdc41a42d007de

I need to write a little more documentation, but the release should come soon.

**Comment by LPGhatguy** [comment]
It looks like the README currently tells users to reference version 0.8, which doesn't exist on crates.io yet. I hit this today trying to get started with Askama!

**Comment by djc** [comment]
Sorry about this... I've been slacking a bit on getting the release out. Still really close though! Just needs some documentation updates for the configurable escapers, getting #205 merged in some way and potentially addressing #196.

**Comment by djc** [comment]
Mostly I've been procrastinating on the first of those, by the way, so if someone wants to take a swing at that, that would be great.

**Comment by gregelenbaas** [comment]
I think after #205 is merged, which looks good to go, we should cut a release. I want to take a stab at fixing #196  but it's going to take me some time to get up to speed with Nom and to be more familiar with Askama's codebase.

**Comment by djc** [comment]
0.8.0 has finally been released -- sorry for the long wait, everyone!

Final release notes are here: https://github.com/djc/askama/releases/tag/0.8.0
