### ISSUE TITLE
Control over indentation with the |json filter

### ISSUE THREAD

**Issue by antifuchs** [djc/askama#192]
Hi there, I use askama to great effect with the `cargo-template-ci` crate (to create yaml for various CI services), and have run into a little weirdness - it's not a blocker, but my aesthetics still feel like this could be better.

When I use the `something|json` filter, the output is indented JSON - that works OK in yaml for me, but it looks *really* weird - I'd much prefer if the JSON output was just a single line, rather than [(legally but weirdly) outdented yaml](https://github.com/antifuchs/cargo-template-ci/blob/f3c7aa5eea5bbcc912b60a1fcb20c1fba747306d/.circleci/config.yml#L107-L118).

Can the filter function be configured to do that?

**Comment by djc** [comment]
It cannot, but you can define user-defined filters, which sounds like a good fit for your particular issue?

There's a little bit of documentation about the feature here:

https://docs.rs/askama/0.7.2/askama/#filters

**Comment by djc** [comment]
To answer your question more directly: no, you cannot, but based on this single request I don't think I want to change stuff built-in to Askama if the user-defined filter provides good (possibly better? -- you can do an actual YAML filter) cover for your needs.

Also I'd be okay with having an optional `yaml` filter included, BTW.

**Comment by djc** [comment]
Closing this for now, since it looks like your problem has been solved!

**Comment by djc** [comment]
(Just to make it better, the next release will feature an optional `yaml` filter, see #201.)

**Comment by asf-stripe** [comment]
Thanks, this is great!
