### ISSUE TITLE
Multi-templates for one struct

### ISSUE THREAD

**Issue by yossyJ** [djc/askama#195]
I think it is better to support multi-templates for one struct, like so:
```
#[derive(Template)]
#[template(path_regex= "(en|ja)/(edit|confirm).html")]
struct FormTemplate<'a> {
    ...
}
```

And generates:
```
impl FormTemplate{
    // list up found templates
    fn get_names() -> &'static[&'static[&'static str]] {
        &[
            &["en", "edit"],
            &["en", "confirm"],
        ]
    }
    fn render_into_by_names(&self, writer: &mut ::std::fmt::Write, names: &[&str]) -> ::askama::Result<()> {
        match names {
            &["en", "edit"] => ...,
            &["en", "confirm"] => ...,
            _ => Err(...),
        }
    }
}
```

**Comment by djc** [comment]
Can you explain the problem you are trying to solve?

**Comment by yossyJ** [comment]
When I make a web server, switch languages by user.  "ja" means Japanese. It determines which language templates are available at run time.

**Comment by djc** [comment]
So if you want this mainly for localization purposes, I think Askama should gain support for proper i18n features. If you're looking for something else I'd still be interested in a more concrete example.

(Note that you can also use includes and inheritance in order to prevent duplication.)

**Comment by yossyJ** [comment]
I will cancel this issue.

**Comment by Deedasmi** [comment]
@djc Apologies for necro posting, but I am interested in localization options and this was my first idea as well. Do you have a way you'd prefer to tackle this issue?

**Comment by djc** [comment]
Would you mind opening a separate issue about localization? Then we can discuss what's needed to make it good.
