### ISSUE TITLE
Static method call

### ISSUE THREAD

**Issue by yossyJ** [djc/askama#196]
Can I use static method in the template?

**Comment by djc** [comment]
Can you give a concrete example? Presumably you have tried it?

**Comment by yossyJ** [comment]
I tried like so:
`{% let a = crate::a() %}
`

**Comment by yossyJ** [comment]
The print attribute is "all", but it shows only `message: unable to parse template:`

**Comment by djc** [comment]
I think bare function calls are not supported at all. Might be a nice addition. Just add a variant `Expr::Call()` similar to `Expr::MethodCall()` and a parser called `expr_call` which is referenced in `expr_single` (before `expr_path`, and you can probably steal code from `expr_path`, too).

(For bonus points, I think you can remove the `expr_var` parser by changing the `many1` in `expr_path` to `many0` to clean things up a little -- in a separate commit please.)

**Comment by yossyJ** [comment]
As I fix it, it seems to affect existing rules, so I will not fix it.

**Comment by djc** [comment]
Really? I think we should fix it anyway.

**Comment by gregelenbaas** [comment]
I'm going to try to take this on this week
