### ISSUE TITLE
Re-export custom derives from askama crate

### ISSUE THREAD

**Issue by dtolnay** [djc/askama#2]
> Custom derive macros can not be exported together with other items, so you have to depend on a separate crate for it.

They can actually. If you are okay requiring Rust >=1.15 to compile askama, you can include this in askama/src/lib.rs:

```rust
#[allow(unused_imports)]
#[macro_use]
extern crate askama_derive;
pub use askama_derive::*;
```

Then users can write:

```rust
#[macro_use]
extern crate askama;
```

and get access to the derives that way.

**Comment by djc** [comment]
Ah, so a crate can export both, but the crate that contains the proc macro cannot export anything else? As it's currently setup, `askama_derive` depends on `askama`, but I guess circular dependencies are not supported, right?

**Comment by dtolnay** [comment]
I would prefer to drop the dependency of askama_derive on askama by moving the codegen-related code into the derive crate. Then you can re-export the derive from askama and save users the trouble of depending on two crates.

**Comment by djc** [comment]
Yeah, that would be much nicer. It was how I set it up initially, but since I misunderstood the exporting restrictions figured that it made more sense to put all the logic together.
