### ISSUE TITLE
struct variant fails to parse

### ISSUE THREAD

**Issue by drahnr** [djc/askama#213]
Askama version: 0.7.2

In matches with fat enums using the named decl, askama can not match

```
{% match x %}
{% when X::A with { name } %}
{% endmatch %}
```

(where `X` is a fat enum)

fails to compile.

So do variants with:

`{% when X::A with ( name ) %}`, `{% when X::A with ( name ) %}`, `{% when X::A with ( name : name ) %}`, `{% when X::A with { name : name } %}`

Fully working minimal example displaying the bug at hand: https://github.com/drahnr/askama-test

**Comment by djc** [comment]
I don't think I've seen the term "fat enum" before, but if you mean struct variants, then yes, I don't think they are supported at this point. Unfortunately I'm afraid I won't have much time to work on this in the near future, though I would be happy to guide you if you wanted to contribute support. It's probably not super hard to add.

**Comment by drahnr** [comment]
I think I picked that term up when I had to do some Java years ago and I just couldn't rember the rustic term.

It depends how involved it is, can you give me starting point so I can have a look into it?

**Comment by drahnr** [comment]
I had brief look into it, and it seems this is caused by 0.7.2 being a little out of date.

The implementation for the above is actually already covered with commit 48c5ebbd2be8f7d89f37f3aa04500b8ad1a3d460 and tested by test `test_match_custom_enum`.

Is there already a release date set for `0.8.0`?

**Comment by djc** [comment]
See #191. Thanks for investigating!
