### ISSUE TITLE
Support for chained attribute expressions

### ISSUE THREAD

**Issue by MHordecki** [djc/askama#22]
If I'm reading [expr_attr] correctly, then it doesn't support recursive productions, such as `obj.x.y.z`.

I've tried to extend `expr_attr` to support this using [fold_many0!]. Alas, I had a bunch of lifetime errors, probably due to some bizarre nom idiosyncrasy I'm not aware of.

[expr_attr]: https://github.com/djc/askama/blob/master/askama_derive/src/parser.rs#L144
[fold_many0!]: https://docs.rs/nom/3.0.0/nom/macro.fold_many0.html

**Comment by djc** [comment]
Thanks for the report, should be fixed now!

Let me know if you have any other feedback about missing features or documentation... I'd also be curious to hear about your use case.

**Comment by MHordecki** [comment]
Wow, that was quick!

I'm writing a garden-variety web app. I find askama to be a breath of fresh air compared to the regular, dynamically typed approaches. Thank you for writing it!
