### ISSUE TITLE
recurse by including self

### ISSUE THREAD

**Issue by drahnr** [djc/askama#220]
I tried to use askama to follow down a tree like structure by using something like this:

```jinja
{# content of this.xyz #}
{%for item in item.children %}
{%if !item.is_leaf() %}
{% include "this.xyz" %}
{% endif %}
{% endfor %}
```

is this something that is supposed to be supported?

The actual result is a message:

```
help: message: attempt to multiply with overflow
```

**Comment by djc** [comment]
You should probably have a look at the generated code (add `print = "code"` to the `#[template()]` attribute and recompile) to see what's going on.

**Comment by drahnr** [comment]
Unfortunately there is no code printed. I tried both `print=code` and `print=all`, and I get the AST but not the generated code.
The error originates from the proc macro itself.

I just wanted to know whether this is a supposedly working use case, since as far as I could see it was not covered by any tests - just to decide whether it's faster to fix or implement another iterator type yielding me what I need :)

**Comment by djc** [comment]
This sounds like a bug that's unrelated to the recursive include itself...

**Comment by drahnr** [comment]
I'll go with the custom iterator then for the time being, maybe I can find some time next week to have glance, maybe.

**Comment by luqmana** [comment]
I've also run into this issue with trying to call a macro recursively.

**Comment by djc** [comment]
In order for this to be actionable it would still be nice if someone could show me some generated code, ideally pasted into the original module so I get the full context for the error message.

**Comment by drahnr** [comment]
```
   Compiling askama-bug v0.1.0 (/home/bernhard/Projects/askama-test)
[Lit("\n", "content:", "\n"), Loop(WS(false, false), Name("item"), Var("root"), [Lit("\n", "", ""), Cond([(WS(false, false), Some(Unary("!", MethodCall(Var("item"), "is_leaf", []))), [Lit("\n", "", ""), Include(WS(false, false), "xyz.html"), Lit("\n", "", "")])], WS(false, false)), Lit("\n", "", "")], WS(false, false))]
error: proc-macro derive panicked
  --> src/main.rs:46:10
   |
46 | #[derive(Template)]
   |          ^^^^^^^^
   |
   = help: message: attempt to multiply with overflow

error: aborting due to previous error

error: Could not compile `askama-bug`.

To learn more, run the command again with --verbose.
```

Same result with `cargo expand`.

Code at: https://github.com/drahnr/askama-test

**Comment by drahnr** [comment]
The least one could do is, mention that it can not be used for recursion in the docs, and a custom iterator should be used instead?

**Comment by djc** [comment]
Would you mind contributing a patch to that effect? Would be much appreciated!

**Comment by drahnr** [comment]
Will do :)

**Comment by josefrcm** [comment]
I think this issue is the same as #105. I just posted a possible solution there, that consist on rendering the template from the template itself.

**Comment by drahnr** [comment]
@djc should I go a head and document as said given @josefrcm workaround?

**Comment by djc** [comment]
@drahnr that would be valuable, thanks!
