### ISSUE TITLE
Filter can't be applied to macro invocation

### ISSUE THREAD

**Issue by luqmana** [djc/askama#226]
Using Rocket's `uri!` macro I noticed I can't combine it with a filter:

foo.html:
```html
{{ uri!(home)|safe }}
```

Results in :
```
error: proc-macro derive panicked
 --> src/main.rs:16:10
  |
6 | #[derive(Template)]
  |          ^^^^^^^^
  |
  = help: message: unable to parse template:
          
          "{{ uri!(home)|safe }}"

error: aborting due to previous error

```

cc @botika who fixed actually being able to call macros in the first place (#178)

A simple workaround for now is just assigning the macro result using let and then using that variable with the filter.

**Comment by djc** [comment]
Thanks for reporting! The grammar for this was indeed set up a bit too restrictive, it should be better with 84d81e1, can you check if that fixes your issue?

**Comment by luqmana** [comment]
Yup, that works (Y) Thanks!
