### ISSUE TITLE
Jinja'a raw block

### ISSUE THREAD

**Issue by fokinpv** [djc/askama#228]
Hi,

Is there any equivalent to the Jinja's `raw` block? Or maybe, it can be emulated somehow.

**Comment by djc** [comment]
Unfortunately this is not supported yet. If you would like to contribute it, I'd be happy to mentor you (or anyone else) -- it shouldn't be too hard.

**Comment by fokinpv** [comment]
I'd like to contribute and made first attempt. https://github.com/djc/askama/pull/231
But will need your advice.
