### ISSUE TITLE
Escaping by default for HTML templates

### ISSUE THREAD

**Issue by robinst** [djc/askama#23]
This looks like a really neat project!

Before I would use it in production though, it needs to have escaping be enabled by default for HTML. Otherwise it will inevitably lead to security problems.

See here for what some other template engines do:

* Handlebars: http://sunng87.github.io/handlebars-rust/handlebars/index.html#escaping
* Tera: https://github.com/Keats/tera#autoescaping
* Jinja2 itself: http://jinja.pocoo.org/docs/2.9/templates/#working-with-automatic-escaping

This library doing things at compile-time, maybe there's a different approach you could use, e.g. escaping all `String`s by default, but introducing a new type that wraps a string that will result in unescaped output.

What are your thoughts on this?

**Comment by djc** [comment]
I've definitely wanted to include something like this, but haven't yet had the need for it. I've sort of been off working on different angles of a project that will eventually converge back on something that needs Askama, I think.

Would you be interested in contributing to this work?

**Comment by robinst** [comment]
Hey. As soon as you do HTML, past experience with templating libraries have shown that the only safe thing is for escaping to be the default. I was just curious because SergioBenitez/Rocket#340 mentioned askama, so I looked into it. As far as I can tell from rocket's stance on this, it would be a requirement for them as well.

I'm not interested in contributing this at the moment, sorry :).
