### ISSUE TITLE
it is probably me

### ISSUE THREAD

**Issue by commandline-be** [djc/askama#239]
In an attempt to quickly jump ship from using tera templates to askama templates i now ended up with working code which does appears to generate the desired html, it is simple not rendered into the browser

**Comment by djc** [comment]
I don't think this is enough information for me to diagnose any problem you might have... Have you checked the server response using something like curl or wget? How are you serving your content -- using a particular framework integration?

**Comment by commandline-be** [comment]
Thank you for the follow up. I assumed it was a typical mistake.

The web application is built on rocket.rs and builds without errors or warnings.

When the application is running i see the rendered HTML output. This means three variables have been inserted into the html tags as was intended.

However, in the browser i do not see this rendered html. Just a minimal set of tags.

It is counter intuitive to me at this point.

Br,

JL

- - -
mailto:commandline@protonmail.com

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 16 mei 2019 09:25, Dirkjan Ochtman schreef:

**Comment by djc** [comment]
This sounds like it's not an Askama problem.

**Comment by commandline-be** [comment]
A bit of an unsetteling yet understandable response.

My assumption is i use println! while i should be using ?

- - -
mailto:commandline@protonmail.com

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 16 mei 2019 09:38, Dirkjan Ochtman schreef:

**Comment by djc** [comment]
You should not use `println!()`, you should return the context type from your Rocket handler.

**Comment by commandline-be** [comment]
Yes. I smack my forehead again. Will revisit my code. Thanks.

Aksama seems blazing fast compared to tera templates. Curious for the end result.

- - -
mailto:commandline@protonmail.com

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 16 mei 2019 09:42, Dirkjan Ochtman schreef:

**Comment by djc** [comment]
I'm happy you like it, let me know if you run into problems.
