### ISSUE TITLE
askama_escape Why escape slashes?

### ISSUE THREAD

**Issue by mashedcode** [djc/askama#245]
Sorry, I just don't seem to understand what harm slashes can do in html.

[Why does it escape slashes?](https://github.com/djc/askama/blob/467f4ade19fa34983de7e6f6d81c6b4d5ff140fe/askama_escape/src/lib.rs#L134)

**Comment by djc** [comment]
Because the OWASP recommends doing so. 

https://security.stackexchange.com/questions/49852/why-should-xss-filters-escape-forward-slash

**Comment by mashedcode** [comment]
[OWASP Cross Site Scripting Prevention Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md#rule-1---html-escape-before-inserting-untrusted-data-into-html-element-content)
Yes they do indeed.
But not in there [XSS Experimental Minimal Encoding Rules](https://www.owasp.org/index.php/XSS_Experimental_Minimal_Encoding_Rules).

Furthermore I don't see anyone provide an actual attack on Security Stack Exchange that was enabled due to unescaped `/`. So I don't agree.

If I agree or not doesn't matter though since the OWASP recommends doing so.
It would still be nice to have a minimal escape version of that function.
The reason for this is that I simply don't want my slashes inside of `src` and `href` to be escaped. It's simply useless.

**Comment by djc** [comment]
You could write your own filter that does more minimal escaping and returns the result as a `MarkupDisplay::Safe`, I think.
