### ISSUE TITLE
Support actix-web v1.0

### ISSUE THREAD

**Issue by NfNitLoop** [djc/askama#246]
The `feature = ["with-actix-web"]` functionality currently depends on actix-web v0.7.0, and won't work with v1.0.

I tried updating the dependency locally, and it looks like the interface of actix-web's `Responder` trait changed in 1.0. ([v1.0] vs. [v0.7])

[v1.0]: https://docs.rs/actix-web/1.0.0/actix_web/trait.Responder.html
[v0.7]: https://docs.rs/actix-web/0.7.19/actix_web/trait.Responder.html

**Comment by djc** [comment]
Right now this will also fail CI since a dependency conflicts with a Gotham dependency (see #234).

**Comment by ZanderBrown** [comment]
Any progress on this?

**Comment by djc** [comment]
I'm afraid there's no good way to split this stuff. At this point I'd prefer to move the integrations into their respective upstreams if possible to make sure Askama doesn't have to build a dependency graph that has to work across 3+ web frameworks. Filed https://github.com/actix/actix-web/issues/1072.
