### ISSUE TITLE
How to set template for multi files

### ISSUE THREAD

**Issue by linca-apricot** [djc/askama#247]
I want to use template for multi files like glob.
is there any inteface?

```rust
#[derive(Template)]
#[template(path = "hello.*")]
struct HelloTemplate<'a> {
    name: &'a str,
}
```

I want to output multi files by extension.

hello.html
```html
<html><body>{{ name }}</body></html>
```

hello.json
```
{
 "name": {{ name }}
}
```

hello.edn
```edn
{:name {{ name }}}
```

hello.somthing...

I already read https://github.com/djc/askama/issues/195

**Comment by djc** [comment]
There is currently no interface, nor do I have much time to work on this. If you come up with a design proposal for this, I'd be happy to review this, though. (Also if this is important to you or your employer I might be available a paid consultant to work on this.)

**Comment by linca-apricot** [comment]
OK. Thanks.
