### ISSUE TITLE
Partials (or nested templates)

### ISSUE THREAD

**Issue by anowell** [djc/askama#25]
Porting some jinja templates, I was using `include` to conditionally including partials (specifically for repeated snippets) that looked something like this:

```
<section name="{{foo_name}}">
  {% include 'creds-'~provider~'-partial.j2' %}
</section>
<section name="{{bar_name}}">
  {% include 'creds-'~provider~'partial.j2 %}
</section>
```

Porting this to use template inheritance doesn't work since the block would be repeated, and I didn't see a built-in partial mechanism. I've currently resorted to just rendering the creds template and storing the `String` result on the main template struct and using it like this:

```
<section name="{{foo_name}}">
  {{provider_creds}}
</section>
<section name="{{bar_name}}">
  {{provider_creds}}
</section>
```

Overall that template file seems fine, but it's kinda disappointing that I have to pre-render the `provider_creds` to and store it on the parent template struct as `provider_creds: String`. I'd prefer to store `provider_creds: AwsCreds` (where `AwsCreds` also derives `Template`) and have Askama handle the recursive rendering. I'm currently hacking together something like this with:

```
impl ::std::fmt::Display for AwsCreds {
    fn fmt(&self, mut f: &mut fmt::Formatter) -> ::std::fmt::Result {
        writeln!(&mut f, "{}", self.render())
    }
}
```

I could even extend that to `impl <T: Template> Display for T`, but I'm not sure how I feel about implementing `Display` for a bunch of these types. Perhaps this would work more elegantly if Askama used a `Renderable` trait instead of the `Display` type, and provided a blanket `impl <T: Display> Renderable for T` and `impl <T: Template> Renderable for T`? I might be missing something here, but it seems simple and elegant to me.

Alternatively, Askama could try and add an `include` statement. I don't see how `include 'path/to/file'` would work given the the path is a part of the derived `Template`, but I could imagine a scenario where you allow `{% include provider_creds %}` or just `{% render provider_creds %}` to trigger `self.provider_creds.render()`, although, at that point maybe `{{ provider_creds.render() }}` is even more intuitive.

Anyhow, this is just my first attempt to think through the space around partials/nested templates. There are still a few kinks in my head that I want to sleep on (e.g. how to maximize template reuse when supporting both `AwsCreds` and  `OpenStackCreds`). But I'd love to know your thoughts. Does anything along these lines fit into the scope of Askama?

**Comment by djc** [comment]
So `include` now works, but only with a string literal path. Not sure that satisfies your use case here?

At some point I think I will need something like a `Renderable` trait anyway, also for escaping strings by default (#23). Not yet sure I like this name, but also haven't come up with a better one...

**Comment by anowell** [comment]
Thanks. This does look pretty reasonable while remaining true to being Jinja-like, though you're correct it doesn't quite satisfy my usecase.

For my usecase, I've stuck to just adding a `String` field on a template and pre-rendering the partial nested template when intializing the main template. It works well enough, though I still think it'd be cleaner if I could use the actual template type or `Box<Template>` or maybe a generic `T: Template` (so that i can' hold different nested templates) as the type of a field on another template.

Anyhow, huge thanks for the various fixes/features to improve my use cases. Askama is definitely great to work with!

**Comment by djc** [comment]
I told you I wasn't done. :wink:

I just pushed cece25b0be1f09f6ab9d53d099bb244858928f57, which implements `Display` for all `Template`s. I experimented with making a separate trait for this which I called `Render` (to invoke a similarity to the `Read` and `Write` traits in `std`), but it ends up being identical to `Template`, which is not helpful. On top of that, the `Template` trait itself is already really similar to `Display`, in that the meat of it is just a method that writes stuff into a `Write`.

So doing it this way seems to be more ergonomical, and makes conceptual sense: if you derive `Template` for your type, it makes sense to me that displaying that type invokes the template implementation. If people want a different serialization, they can use `Debug` still, and I could potentially add an option to the `template()` attribute to disable generation the `impl Display` code.

So, with that, I think you have a nice solution to your problem!

Thanks again for all the feedback, I think it's already made Askama a lot better already, and it has allowed me to more critically review my code from 6 months ago. 👍

**Comment by anowell** [comment]
Huge thanks! Implementing `Display` for all `Template`s works for me and I mostly agree with your reasoning. I sorta imagine somebody eventually coming along and not wanting that behavior, but I had a hard time thinking up a compelling scenario for that, so 👍 from me.

p.s. I included a shout-out for Askama in this [r/rust thread](https://www.reddit.com/r/rust/comments/6sqxyi/for_highlevel_code_how_productive_is_rust/dlgn1vg/?st=j67iha0t&sh=dceac1bc). ;-)

**Comment by djc** [comment]
Thaks for the shout out, very nice.
