### ISSUE TITLE
Tests support like: {% if foo is defined %}     {{ foo }} {% endif %}

### ISSUE THREAD

**Issue by mocsy** [djc/askama#257]
```jinja
{% if foo is defined %}
    {{ foo }}
{% endif %}
```

This doesn't work with askama. It works in tera.
Issue [#46](https://github.com/djc/askama/issues/46) is closed with "This has long been done." but it's either not the case or it's only the case for the match syntax from the same issue.

In tera/jijna2 lingo _defined_ is a _test_:
[tera tests](https://tera.netlify.com/docs/templates/#built-in-tests)
[jinja 2 tests](http://jinja.pocoo.org/docs/2.10/templates/#builtin-tests).
I couldn't find any tests in askama, don't know where to put this.

Code wise my _defined_ is rather simple:
```rust
pub fn defined<T>(o: &Option<T>) -> Result<bool>
{
    if o.is_some() {
        return Ok(true);
    }
    Ok(false)
}
```
The reason for using an Option is that in the template input struct everything a template refers to must always be defined anyway, so to satisfy a template with optional data, using the rust Option type makes the most sense.

Results are different in that the Err can also hold a value, so that's not something to use with defined anyway.

**Comment by djc** [comment]
That's right, you can do this with match (or is_some() and unwrap()).

**Comment by mocsy** [comment]
> That's right, you can do this with match (or is_some() and unwrap()).

Yeah but that breaks away from existing practice in tera and jinja.
Question is, which is more valued in askama: going with jinja2 syntax, going with rust syntax or inventing an askama specific syntax.
Based on the project description "Askama implements a template rendering engine based on Jinja. " I suspect that 'jinja likeliness' is a goal, so these kind of _tests_ would be beneficial.
Let me know if the goals are different.

**Comment by mocsy** [comment]
Is it possible to extend askama a new crate?
Adding extra filters, or in this case _tests_ to another crate so those who want this kind of syntax compatibility could get it, but the askama crate could stay as is.
I like my template engine minimal anyway, so a way to extend would be more ideal, right?

**Comment by djc** [comment]
Askama implements a Jinja-like syntax which is adapted to fit Rust. So far, I have not implemented what Jinja calls "tests" and there has not been much demand for it.

The only currently implemented extensibility is in filters, and some limited customizability in the template syntax (mostly around the block and expression delimiters).

I suppose the `defined` test could translate down to an `if let`. What other "tests" (just using the quotes to disambiguate from all other uses of the word test) would you want to use?

**Comment by djc** [comment]
(And also, would you be willing to implement this yourself? I'd be happy to mentor, but I won't have time any time soon to implement this myself -- unless your or your employer wants to sponsor the work.)
