### ISSUE TITLE
How to compose templates (not inheritence but composition)?

### ISSUE THREAD

**Issue by yatesco** [djc/askama#262]
<newbie/>
I have a single template working and I have read the documentation from top to bottom. I understand that we can use inheritence and pull all the common layout stuff (banner, headers etc.) into a parent template and extend from that.

However, I can't figure out to compose templates. For example, I have a "pager template" which is parameterised by the current page number and the number of total pages etc. I want to use this template in a number of other templates, but I can't see how to do that.

I could always "execute that template" and capture the output as string and then provider that string to the "main" template, but that feels awkward.

What have I missed :-).

**Comment by djc** [comment]
Have you looked at `include`? Also `Template` implements `Display` and `Display` things can just be used as an expression.

**Comment by yatesco** [comment]
That's exactly what I was looking for - thank you :-).
