### ISSUE TITLE
Type checking form names match?

### ISSUE THREAD

**Issue by yatesco** [djc/askama#263]
<newbie/>

I think the answer is going to be "tests", but is there any mechanism for checking that fieldNames in forms match their underlying structs?

Thanks!

**Comment by djc** [comment]
I'm not quite sure what you're asking. Askama has no notion of forms or field names, as far as I know?

**Comment by yatesco** [comment]
I mean if I have a form with an input field called “naem” but the struct I will be binding it to has a field called “name”. 

Oh, the joys of HTML :-).

**Comment by djc** [comment]
Askama doesn't know anything specific about forms, so it probably won't help you there. There might be other crates that can help solve similar problems (quick searching turns up webforms).
