### ISSUE TITLE
Using for control structure on iterators

### ISSUE THREAD

**Issue by zakcutner** [djc/askama#268]
Hey! I've been using Askama for a few days now and I think it's great 👌 However, there's one thing that I haven't been able to work out how to do. To illustrate with a simple example, I have a method like this...

```rust
fn numbers(&self) -> impl Iterator<Item = i32> { ... }
```

...but when I try to call it within a template like this...

```jinja2
{% for n in self.numbers() %}n{% endfor %}
```

...Askama generates the following code for the loop...

```rust
for (n, _loop_item) in ::askama::helpers::TemplateLoop::new((&self.numbers()).into_iter()) { ... }
```

Now this code doesn't compile. Because `&self.numbers()` creates a shared reference, when `into_iter()` (which takes `self`) is called on it, it tries to take ownership of the underlying iterator, illegally moving out of the reference.

What is the reason for borrowing the iterable before calling `into_iter()` on it? Is it possible to either prevent this borrow, or even bypass the call to `into_iter()` entirely (in the same way as ranges are generated) as `self.numbers()` is already an iterator in this case?

Thank you ☺️

**Comment by djc** [comment]
See also #222, #107. I'd be happy to solve this, but I haven't come up with a satisfactory solution so far.

**Comment by zakcutner** [comment]
@djc thanks for the links!

**Comment by djc** [comment]
I'll close this issue for now.
