### ISSUE TITLE
Invalid tag causes rendering to silently halt

### ISSUE THREAD

**Issue by anowell** [djc/askama#27]
I had a child template start with this (a typo of `extends` as `extend`)

```
{% extend "path/to/file.j2" %}
```

then the generated coded ended up with an empty `render_to` block. More generally, I can insert almost any arbitrary, non-valid content inside the `{% %}` (including nothing inside the tag) and any content after that tag is not rendered. So:

```
foo
{% garbage %}
baz
``` 

generates

```rust
impl< 'a > ::askama::Template for ApplicationConfAws< 'a > {
    fn render_to(&self, writer: &mut ::std::fmt::Write) {
        writer.write_str("foo").unwrap();
        writer.write_str("\n").unwrap();
    }
}
```

**Comment by djc** [comment]
Ah, I think that makes sense. I can probably include some catch-all parser rules that panic on unsupported stuff, which I think will make the situation better/more obvious.
