### ISSUE TITLE
Use "and", "or", "not" logical operators

### ISSUE THREAD

**Issue by bibicron** [djc/askama#275]
Thank you for this great project.

Is it possible to add the "and", "or", "not" logical operators in addition to "&&", "||", "!" in the IF statements?

This will make the templates more jinja2 compatible.
I am was thinking to use the same template files with Askama for SSR and Nunjucks for CSR.
Nunjucks will not render if will find the "!" operator. The workaround for now is to place the code in the ELSE block.

Thank you

**Comment by djc** [comment]
I think I would be open to this; we can extend the custom syntax support that's already in place to allow changing these operators.

**Comment by bibicron** [comment]
Sound good.
Other updates which will make the code more jinja2 compatible are:
1. Call macros as an expression also
- Jinja2 can call a macro as a block: {%call foo()%}...{%endcall%}
- Jinja2 can call a macro as an expression: {{foo()}}
- Askama can call a macro like this: {%call foo()%}
2. Declare variable with "set"
- Jinja2 declares mutable variable as: {%set foo=bar%}
- Askama declares immutable variable as: {%let foo=bar%}

I can start with the "set" declaration as I already implement it on my local copy.
All these updates will be 100% compatible with the previous syntax.
