### ISSUE TITLE
Question: Return Values

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [djc/askama#276]
Is it possible to have a login page with an html something like this
```html
<body>
    <h1>Welcome!</h1>
    <form action="/login" method="POST">
        <label for="user">Login</label>
        <input type="text" placeholder="Enter a @email or phone#" name="user" required>
        <button type="submit" value="Submit">Login</button>
    </form>
</body>
```
at `ip:port/login`
And make a function that returns the values of entered in input text box on submit and take then send that user to `ip:port/dashboard` using that information to log him in? 

I've seen people use a text box that sends the user to something like `ip:port/user{user_name}'` and then parse the url to get the user but that's not very elegant.

**Comment by djc** [comment]
I suppose you may already have figured this out by now, but Askama doesn't interact with the HTTP protocol in any way -- it's just a way to help generate strings from Rust values.
