### ISSUE TITLE
Feature request: auto implement Deref to _parent for child templates

### ISSUE THREAD

**Issue by anowell** [djc/askama#28]
I have a pair of parent/child templates like this:

```rust
#[derive(Template)]
#[template(path = "application.conf.j2")]
pub struct ApplicationConf<'a> {
    app: &'a AppConfig,
    provider: Provider,
}

#[derive(Template)]
#[template(path = "application.conf.openstack")]
struct ApplicationConfOpenStack<'a> {
    _parent: ApplicationConf<'a>,
    os: &'a OpenStackConfig,
}
```

And I'd like `application.conf.openstack` to be able to use `{{app.field}}` rather than `{{_parent.app.field}}`. I am accomplishing this by adding this `Deref` impl.

```rust
impl <'a> ::std::ops::Deref for ApplicationConfOpenStack<'a> {
    type Target = ApplicationConf<'a>;
    fn deref(&self) -> &Self::Target {
        &self._parent
    }
}
```

And it seems to me that the idea of template inheritance lines up pretty well with the intent of `Deref`.

**Comment by djc** [comment]
This is a great idea! I'll have to work on the mechanics a little bit, though.
