### ISSUE TITLE
Erroneous architecture for memory management

### ISSUE THREAD

**Issue by Su-Ky** [djc/askama#297]
[Here](https://github.com/djc/askama/blob/master/askama_shared/src/generator.rs#L675-L682) you comment 
```rust
// Since nodes must not outlive the Generator, we instantiate
// a nested Generator here to handle the include's nodes.
```
but this is nonsense, I don't think you understand memory management in Rust.

With the right **lifetime**, you should not do that, which I think is very bad because it does not allow you to get the data out of this context. 
With what I see that every time it is used, I will be forced to empty the writable buffer. 
With what every macro or block I do generates unnecessary functions. 

Could it not generate these unnecessary functions?

I am watching him do it but it comes from far behind, it covers the entire generator and its support classes. I think you need a refactor.

Thanks

**Comment by djc** [comment]
That particular code block only covers includes, not macros or blocks. Can you give a specific example where suboptimal code is generated?

(If you are asking for my help/support, it would make me much more favorably disposed towards your request if you refrained from writing things like "I don't think you understand Rust lifetime management".)

**Comment by Su-Ky** [comment]
**Every time you use a macro or a block.** The code I think is clear. And it is not that it is suboptimal, it is that the architecture is not well designed. 

So generate a call to `std::Display::fmt(..)` **every time** you use a block or a macro.

It really is like an iceberg, here's the tip https://github.com/djc/askama/blob/master/askama_shared/src/generator.rs#L77-L86

It is clear that seeing how you treat your contributors I am not going to fix the code so that later my commits disappear.

As nodes can not leave if they come from outside, exactly from the parser function.

Please do not treat me as if I were stupid, **denying the evidence**.

**Comment by djc** [comment]
This is not a constructive way of engagement. I'll close this issue, and I've blocked the author from further participation in this project.
