### ISSUE TITLE
Realloc every escaped or filter value

### ISSUE THREAD

**Issue by Su-Ky** [djc/askama#299]
It is relocated without the need for strings, https://github.com/djc/askama/blob/master/askama_escape/src/lib.rs#L7. Convert non escape types to string and realloc in another strings. And if we count the filters we have an endless number of realloc. 

Can unnecessary reallocations be fixed?

**Comment by djc** [comment]
I don't think there are any unnecessary reallocation, but feel free to point them out specifically if you find them.

**Comment by Su-Ky** [comment]
I see clearly that the only type is Display, therefore the only method you have is `to_string` and its variants. Therefore with the following code the number, the number string and the template string are allocated. 

```rust
#[derive(Template)
#[template(source = "{{ number }}"]
struct Foo {
    number: usize
}
```
I don't see you understand the Trait Display, I attached the [documentation](https://doc.rust-lang.org/std/fmt/trait.Display.html)

**Comment by djc** [comment]
Unfortunately this issue is not specific enough to be actionable. Given the author's abrasive way of communicating in #298 and #297, I've decided to block them from participating in this project.
