### ISSUE TITLE
All Template structs require a name field

### ISSUE THREAD

**Issue by superlou** [djc/askama#313]
Whenever I create a template without a `name` field, I receive the following error:

```
error[E0609]: no field `name` on type `&IndexTemplate`
 --> src/main.rs:5:10
  |
5 | #[derive(Template)]
  |          ^^^^^^^^ unknown field
  |
```

I get this with the following test server:

```
use actix_web::{web, App, HttpServer, HttpResponse, Responder};
use askama::actix_web::TemplateIntoResponse;
use askama::Template;

#[derive(Template)]
#[template(path="index.html")]
struct IndexTemplate {}

async fn index() -> impl Responder {
    IndexTemplate { }.into_response()
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {

    HttpServer::new(move || {
        App::new()
            .route("/", web::get().to(index))
    }).bind("127.0.0.1:8080")?.run().await
}
```

The program compiles successfully with the following change:

```
#[derive(Template)]
#[template(path="index.html")]
struct IndexTemplate<'a> {
    name: &'a str,
}
```

Is that expected? I've seen examples with templates that have no fields. I am using the following dependencies:

```
[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
askama = {version="0.9", features=["with-actix-web"]}
futures = { version = "0.3" }

[build-dependencies]
askama = "0.9"
```

**Comment by djc** [comment]
What does `index.html` contain?

**Comment by djc** [comment]
You can `print = "code"` to the `template` (or use cargo-expand) attribute to see the generated code, this should make it clear what's going on.

**Comment by superlou** [comment]
Askama is working absolutely fine, and this is embarrassing. I had removed the `{{name}}` references from a template that had had them, but the IDE (Atom) didn't know to rebuild since it was an html file. Then, a combination of a filename typo and my rushing about made me think it was also failing in a terminal `cargo run` build as well. Sorry, and thanks so much for the quick response!

**Comment by djc** [comment]
No problem, these kinds of issues happen to me quite often. :)
