### ISSUE TITLE
Incorrect code generation for `{{ true && false }}`

### ISSUE THREAD

**Issue by cipriancraciun** [djc/askama#328]
[Discovered while working on #315 and #327.]

Apparently when trying `{{ true && false }}` the compiler fails with:
~~~~
expected `bool`, found `&bool`
~~~~

The same error is encountered also for `{{ true || false }}`.

Although both `{{ ! true }}` and `{% if true && false %}` works.

The same error is encountered also when working with boolean variables:
~~~~
{% let x = true %}
{% let y = true %}
{{ x && y }}
~~~~

**Comment by vallentin** [comment]
@djc this can be closed, I fixed it in #390 but I forgot to reference it.
