### ISSUE TITLE
Add support for redefining the same variable with `let` (just as Rust permits)

### ISSUE THREAD

**Issue by cipriancraciun** [djc/askama#329]
[Discovered while working on #315 and #327.]

The following statements, although allowed by Rust, are disallowed by `askama`:
~~~~
{% let x = 1 %}
{% let x = 2 %}
~~~~

The failure is:
~~~~
cannot assign twice to immutable variable
help: make this binding mutable: `mut x`
~~~~

**Comment by djc** [comment]
I'm guessing this should be easy to fix.

**Comment by max-frai** [comment]
Any news on this? It's very important when splitting template into small parts with ability to `include` them and setting some variables before include.

**Comment by djc** [comment]
I haven't had a chance to work on it, and it's not much of a priority for me right now. I might be able to mentor you if you want to dig in, or you can pay me for a few hours of work on this, if that's a viable option for you.

**Comment by vallentin** [comment]
I wonder if we should include Jinja's `{% set ... = ... %}` and use it to differentiate between defining and assigning. We could also make the `set` keyword optional, I'm just suggesting it to be more in line with Jinja.

In short:

- `{% let x = ... %}` would always (re)define the variable, i.e. result in `let x = ...;`
- `{% set x = ... %}` would (re)assign the variable, i.e. result in `x = ...;`
- Any use of `{% set x = ... %}` would result in the already declared variable to become mutable, i.e. `let mut x = ...;`
- If `{% set x = ... %}` is not accompanied by a previous `{% let x %}` or `{% let x = ... %}`, then it will implicitly generate `let mut x;`

Example Template:

```jinja
{% let x = "foo" %}
{% let x = "bar" %}

{% set y = "foo" %}
{% set y = "bar" %}

{% let z %}
{% set z = "foo" %}
{% set z = "bar" %}
```

Then the above template would generate the following Rust:

```rust
let x = "foo";
let x = "bar";

let mut y = "foo";
y = "bar";

let mut z;
z = "foo";
z = "bar";
```

**Comment by djc** [comment]
I don't like the idea of `set` and `let` having different semantics (which I think would not be obvious). I also don't like introducing mutability here -- I feel like `let` bindings in Askama templates should always be immutable. I am open to shadowing, following general Rust semantics. We could also just make `set` an alias for `let`, which seems innocuous enough and might be helpful for people porting code from another template engine.

**Comment by vallentin** [comment]
Alright, I'll implement that sometime soon, when I'm able to.

- [ ] Shadowing
- [ ] `set` alias for `let`

> Askama templates should always be immutable

Just out of curiosity. But the generator currently omits `let` and only produces an assignment, if the variable is already defined. Has the Askama previously allowed mutable variables?

https://github.com/djc/askama/blob/3b57663b5b626a322e81f9399f0ab39a88411fd4/askama_shared/src/generator.rs#L832-L838

**Comment by djc** [comment]
No, this is just to facilitate assignments where different values are assigned in different valuesl; so, `let foo` without a value, then assigning a value in an `if` or `match` branch (I think this is the `LetDecl` AST node).

**Comment by vallentin** [comment]
Ah of course. Funny how I literally had an example demonstrating that behavior just before. But my brain short circuited anyways and got confused. 😅
