### ISSUE TITLE
for-loop on values of a BTreeMap inside a template does not compile

### ISSUE THREAD

**Issue by luc-mercier** [djc/askama#333]
Hi Askama team,

I'm hitting the an issue with for-loops inside template on `(some BTreeMap).values()`.

## Preliminary: what DOES work
Consider first the following piece of code, which works, demonstrating that the `values()` function of `BTreeMap` can be used inside an Askama template, as expected:

`main.rs`:
```rust
use std::collections::BTreeMap;
use askama::Template;

#[derive(Debug)]
struct Foo {
  foo: u64,
}

fn make_map() -> BTreeMap<u64, Foo> {
    let mut map : BTreeMap<u64, Foo> = BTreeMap::new();
    map.insert(23, Foo { foo: 51} );
    map
}

#[derive(Template)]
#[template(path = "template.txt")]
struct MyTemplate<'a> {
  map : &'a BTreeMap<u64, Foo>
}

fn main() {
    println!("Demo of weird stuff with BTreeMap in Askama template");
    let map = make_map();

    for foo in map.values() {
        println!("{:?}", foo)
    }

    let rendered = (MyTemplate {
        map : &map
    }).render().unwrap();
    println!("{}", rendered);
}
```

`template.txt`:
```
{{ map.values().count() }}
```

This works just fine, and the template renders the number of values, which is 1.

## But iterating does not work

Now add the following to the template:
```
{% for foo in map.values() %}
  {{ format!("{:?}", foo) }}
{% endfor %}
```

This won't compile:
> move occurs because value has type `std::collections::btree_map::Values<'_, u64, Foo>`, which does not implement the `Copy` trait

This surprises me, since in the main we also have a similar for-loop on the values, which work just fine.

## Workaround: collect references to values in a vector of references

I did find the following workaround: in the `MyTemplate` struct, add field
```rust
foos : &'a Vec<&'a Foo>
```

In `main.rs`, allocate a vector of references to the map values:
```rust
let foos : Vec<& Foo> = map.values().collect();
...
MyTemplate {
     ...,
     foos : &foos
}...
```

and iterate on `foos` in the template. This works, but is cumbersome.

Thanks in advance for considering this report!

**Comment by ggreif** [comment]
Allocating a `Vec` just to appease `djc/askama` seems unfortunate. I wonder whether adding something like the `&`-syntax could improve things:
```
{% for &foo in map.values() %}
```

**Comment by dbr** [comment]
I encountered the same issue trying to iterate over a `BTreeMap` using `.rev()`:

```jinja
{% for (date, day_videos) in videos.videos %}
```
compiles successfully into:
```rust
for ((date,day_videos,), _loop_item) in ::askama::helpers::TemplateLoop::new((&self.videos.videos).into_iter()) {
```

Whereas

```jinja
{% for (date, day_videos) in videos.videos.into_iter().rev() %}
```
compiles with error to
```rust
for ((date,day_videos,), _loop_item) in ::askama::helpers::TemplateLoop::new((&self.videos.videos.into_iter().rev()).into_iter()) {
```

This results in a similar error:
```
error[E0507]: cannot move out of `self.videos.videos` which is behind a shared reference
...
move occurs because `self.videos.videos` has type `std::collections::BTreeMap<std::string::String, std::vec::Vec<web::WebVideoInfo<'_>>>`, which does not implement the `Copy` trait
```

**Comment by djc** [comment]
Can you try with `videos.videos.iter().rev()`?

**Comment by dbr** [comment]
Similar error:

```jinja
{% for (date, day_videos) in videos.videos.iter().rev() %}
```
becomes
```rust
for ((date,day_videos,), _loop_item) in ::askama::helpers::TemplateLoop::new((&self.videos.videos.iter().rev()).into_iter()) {
```
resulting in:
```rust
error[E0507]: cannot move out of a shared reference
   --> src/web.rs:177:10
    |
177 | #[derive(Template)]
    |          ^^^^^^^^ move occurs because value has type `std::iter::Rev<std::collections::btree_map::Iter<'_, std::string::String, std::vec::Vec<web::WebVideoInfo<'_>>>>`, which does not implement the `Copy` trait
```

**Comment by luc-mercier** [comment]
@djc, any update on this? Do you know why it's happening? Do you have some solution in mind? How does it rank on your priority list?

**Comment by djc** [comment]
It's pretty high on my priority list, but I'm currently on holiday so not doing a ton of open source work. I think I may have a solution in find, but it might not be fully backwards compatible, so I need to think about it more.

**Comment by luc-mercier** [comment]
Thanks @djc for the update!

**Comment by cmcqueen** [comment]
I am encountering this issue in release 0.10.5. Is there a plan for a release that includes this fix?

**Comment by djc** [comment]
Yup, see #451.
