### ISSUE TITLE
Extra space apparently causes failure to parse

### ISSUE THREAD

**Issue by jmafc** [djc/askama#337]
In the `deep-blocks` branch (presumably now in `master` too), a macro caused a `message: unable to parse template`. The macro is relatively complex but it seems an extra space was causing the failure. Once the space was removed, it ran fine.

The macro looks like this:
```jinja
{%- macro example(r) -%}
{%- if !r.is_empty() -%}
<div>{% for p in r -%}
<li><a href="{{ p.y|safe }}">{% if p.t != "" -%}
      {{ p.x  }}{% else %}{{ p.t }}{% endif %}</a></li>
{%- if !loop.last %}, {% endif -%}
{%- endfor %}
</div>
{%- endif -%}
```
The problem are the two spaces after `p.x`. If I remove one of them, it's OK.

**Comment by djc** [comment]
Nice find. I had made the whitespace parsing a bit more restrictive but that's not probably not a good idea. Loosened it up again in d7d18d3.

**Comment by jmafc** [comment]
I think Jinja is *very* lenient with respect to whiespace. For some reason, one of my templates had a very odd format for an if/else, like this:
```jinja
{% if foo %}
    X{%
else %}
   Y{%
endif %}
```
This pattern was even repeated right after the above (but with another test value). Askama didn't like to parsing that until I changed to a more sensible way, i.e., without breaking the else/endif across lines.

**Comment by djc** [comment]
I just tried that template on current master (on or after cfc38883b4b0247f21cb3403845d2fe3df06df0c) and it seemed to work. 👍
