### ISSUE TITLE
No license files in subpackages on crates.io

### ISSUE THREAD

**Issue by tim77** [djc/askama#339]
Hi. Please add license files into askama subpackages on crates.io. Symlink would enough. This is mandatory requirement for packaging in some Linux distros.

**Comment by djc** [comment]
Can you be specific about the distro you're referring to here? The Cargo manifest makes it a requirement to specify the license or the license-file but doesn't require both -- it seems like well-defined license names really shouldn't require the file.

**Comment by tim77** [comment]
Trying to package it for Fedora https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

cc: @ignatenkobrain

**Comment by djc** [comment]
That link gives me a 403 Forbidden error. What's the use case here? I presume you're trying to package something that uses Askama as a dependency?

**Comment by tim77** [comment]
From this guidelines:

> If the source package includes the text of the license(s) in its own file, then that file, containing the text of the license(s) for the package must be included in %license. If the source package does not include the text of the license(s), the packager should contact upstream and encourage them to correct this mistake.

> In cases where the upstream has chosen a license that requires that a copy of the license text be distributed along with the binaries and/or source code, but does not provide a copy of the license text (in the source tree, or in some rare cases, anywhere), the packager should do their best to point out this confusion to upstream. This sometimes occurs when an upstream project’s only reference to a license is in a README (where they simply say "licensed under the FOO license"), on their website, or when they simply do not check a copy of the license into their Source tree. Common licenses that require including their texts with all derivative works include ASL 2.0, EPL, BSD and MIT. Packagers should point out to upstream that by not including a proper full license text, they are making it difficult or impossible for anyone to comply with their desired license terms.

> However, in situations where upstream is unresponsive, unable, or unwilling to provide proper full license text as part of the source code, and the indicated license requires that the full license text be included, Fedora Packagers must either:

> - Include a copy of what they believe the license text is intended to be, as part of the Fedora package in %license, in order to remain in compliance. It is worth noting that this may place some additional risk on the packager, however, Fedora believes that this risk is minimized by the fact that if the upstream disagrees with what we have distributed as the full license text, they can easily remedy this by making full license text available in the source code. Packagers who choose to do this should ensure that they have exhausted all attempts to work with upstream to include the license text as part of the source code, or at least, to confirm the full license text explicitly with the upstream, as this minimizes the risk on the packager. Packagers should also take copies of license texts from reliable and canonical sources (such as the Fedora Software Licenses page, the FSF licenses page, or the OSI license list), whenever possible.

> - Choose not to package that software for Fedora.

Trying to package that uses Askama as dependecy, yep, but all deps and crates should include this license file. This is mandatory for Fedora. 😟

**Comment by djc** [comment]
So out of curiosity, what is the dependency that you're trying to package in the end?

Do you also have guidelines/examples of how it should work when more than once license applies? In the Rust ecosystem, the MIT + Apache-2.0 combination seems quite common, but Cargo only supports a single `license-file` as far as I can tell, so I'm not sure how to resolve that situation.

(FWIW, I find the guidelines' tone pretty condescending towards upstream maintainers when stating things like "point out this confusion" and "correct this mistake".)

**Comment by tim77** [comment]
> So out of curiosity, what is the dependency that you're trying to package in the end?

This is `flat-manager`.

Distributing this files on crates.io would enough: `LICENSE-APACHE` and `LICENSE-MIT`. Here is some examples how this packaged in Fedora: https://src.fedoraproject.org/rpms/rust-starship/blob/master/f/rust-starship.spec#_48
and if this not lib, if this is an app itself, Fedora requires to list all depended crates licenses, like this: https://src.fedoraproject.org/rpms/rust-starship/blob/master/f/rust-starship.spec#_34

**Comment by tim77** [comment]
@djc thank you.
