### ISSUE TITLE
No README file on crates.io

### ISSUE THREAD

**Issue by tim77** [djc/askama#340]
Cargo.toml contain it https://github.com/djc/askama/blob/master/askama/Cargo.toml#L13 but there is no this file on crates.io. Please add it. This relates to packaging for official Linux distros.

**Comment by djc** [comment]
What do you mean by this file not being on crates.io? https://crates.io/crates/askama seems to show the README, so clearly it is there in some capacity.

**Comment by tim77** [comment]
But crate itself is not contain README file. This is not a big issue but for example some generators try to include this file, like `rust2rpm` which is not available. Seems like when you release the next version with latest cargo this issue should go away automatically.

**Comment by djc** [comment]
By latest cargo, do you mean the released Cargo version (as in, the Cargo included in the 1.44.1 release)?

**Comment by djc** [comment]
Note that flat-manager depends on Askama 0.7, so presumably my publishing a new Cargo release won't actually help unless flat-manager upstream upgrades to the latest version.

**Comment by tim77** [comment]
> By latest cargo, do you mean the released Cargo version (as in, the Cargo included in the 1.44.1 release)?

I guess so, but not sure.

> Note that flat-manager depends on Askama 0.7, so presumably my publishing a new Cargo release won't actually help unless flat-manager upstream upgrades to the latest version.

In Fedora we patching and bumping version or if this not possible then packaging `compat` packages.

**Comment by djc** [comment]
I've released 0.10.0 to crates.io, and this should include the README. Let me know if you still see issues.

**Comment by tim77** [comment]
> Let me know if you still see issues.

TBH it still. But this is so minor problem and i don't want even bothering you. :) But never seen before like that.

[Packaged](https://src.fedoraproject.org/rpms/rust-askama/blob/master/f/rust-askama.spec#_40).

**Comment by djc** [comment]
That seems like a Cargo issue then? Maybe file an issue there.
