### ISSUE TITLE
Release request 0.10.0

### ISSUE THREAD

**Issue by eigenein** [djc/askama#341]
Hi Dirkjan,

Could you please publish a newer release on crates.io? Specifically, I'd like to use associated function calls, this has been merged quite some time ago.

**Comment by djc** [comment]
Yup, it's about time. I want to get #332 in before I cut the release, but will make another release after that.

**Comment by eigenein** [comment]
👍  I could also help to get things done, just drop the line if anything is needed

**Comment by djc** [comment]
Thanks for the offer! it should be pretty straightforward, though.

**Comment by djc** [comment]
I've released 0.10.0 to crates.io, and the integration crates are being published as I write this. Let me know if you run into any problems!
