### ISSUE TITLE
How to use into_response() with feature "with-actix-web"

### ISSUE THREAD

**Issue by timonbimon** [djc/askama#349]
I was trying to use the into_response() method from the "with-actix-web" feature.
The only place where I could find some "documentation" was in [another issue](https://github.com/djc/askama/issues/313), where it was used by importing `askama::actix_web::TemplateIntoResponse`.

```
use askama::actix_web::TemplateIntoResponse;
use askama::Template;

#[derive(Template)]
#[template(path="index.html")]
struct IndexTemplate {}

async fn index() -> impl Responder {
    IndexTemplate { }.into_response()
}
```

When I try to do that I get the following error:

```
error[E0432]: unresolved import `askama::actix_web`
 --> src/routes/mod.rs:6:13
  |
6 | use askama::actix_web::TemplateIntoResponse;
  |             ^^^^^^^^^ could not find `actix_web` in `askama`
```

I have these lines in my `Cargo.toml`

```
...
actix-web = "2.0"
askama = { version = "0.10.2", features = ["with-actix-web"]}
...
```

I am rather new to Rust so sorry if there is something obvious I am missing :/

**Comment by timonbimon** [comment]
Ok I just saw #346 which seemed to have the same problem and same workaround => add `askama_actix` to `Cargo.toml` and then `use askama_actix::Template`

**Comment by djc** [comment]
Yup, I'll try to improve the documentation on this soon.
