### ISSUE TITLE
into_f64, into_isize unusable

### ISSUE THREAD

**Issue by yshui** [djc/askama#357]
`{{ number | into_f64 }}` expands to `into_f64(&number)`, which doesn't compile, because borrowed number doesn't `impl NumCast`.

**Comment by djc** [comment]
Thanks for the report. Would you mind submitting a patch that adds the appropriate `*` operators?

**Comment by yshui** [comment]
Maybe it's better to have info_f64 take `&T`?

**Comment by djc** [comment]
That's fine, too! Whatever works in the context of Askama filters.
