### ISSUE TITLE
Multiple templates per struct

### ISSUE THREAD

**Issue by ajeetdsouza** [djc/askama#366]
Is there currently a way to use the same struct to generate multiple different templates? So far, the best way I could find was to wrap it in a new struct, one for each template.

Is this the recommended way, or is there a better way of achieving this?

**Comment by djc** [comment]
I can't really think of a better way to achieve this. The `#[template]` attribute basically generates an `impl Template for <type>`, and you can't have more than one of those on a single type.

You could implement `Deref` on the wrapper type to make the wrapping more transparent, that might help a bit.

**Comment by ajeetdsouza** [comment]
Seems fair enough. Thanks!
