### ISSUE TITLE
A little issue with template inheritiance. 

### ISSUE THREAD

**Issue by afidegnum** [djc/askama#375]
I'm trying to implement a template inheritance with askama which is very handy in template. however i have found myself in few errors, where i'm confused on how to implement the template inheritance. 

this is the project [repo for the structure.]( https://github.com/afidegnum/untitled). however, i'm getting the following errors. 

```
error[E0726]: implicit elided lifetime not allowed here
   --> src/main.rs:282:6
    |
282 | impl LayoutTemplate {
    |      ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`

error[E0599]: no method named `get_specific` found for struct `std::string::String` in the current scope
   --> src/main.rs:351:15
    |
351 |     let t = s.get_specific(&menu);
    |               ^^^^^^^^^^^^ method not found in `std::string::String`

```

**Comment by afidegnum** [comment]
I'm trying to implement a template inheritance with askama which is very handy in template. however i have found myself in few errors, where i'm confused on how to implement the template inheritance. 

this is the project [repo for the structure.]( https://github.com/afidegnum/untitled). however, i'm getting the following errors. 

```
error[E0726]: implicit elided lifetime not allowed here
   --> src/main.rs:282:6
    |
282 | impl LayoutTemplate {
    |      ^^^^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`

error[E0599]: no method named `get_specific` found for struct `std::string::String` in the current scope
   --> src/main.rs:351:15
    |
351 |     let t = s.get_specific(&menu);
    |               ^^^^^^^^^^^^ method not found in `std::string::String`

```

**Comment by djc** [comment]
You forgot to add a `Cargo.toml` to the repo, which makes it hard to test.

**Comment by afidegnum** [comment]
hi, sorry i didn't pay attention, i have added `Cargo.toml`

**Comment by djc** [comment]
So this seems to help a little:

```rust
diff --git a/templates/index.html b/templates/index.html
index ed3df67..33945ad 100644
--- a/templates/index.html
+++ b/templates/index.html
@@ -1,4 +1,5 @@
-<!DOCTYPE html>
+{% extends "layout.html" %}
+!DOCTYPE html>
 <html>
 <head>
     <meta charset="utf-8" />
```

Otherwise, your repo is very broken -- numerous files appear to still be missing or in an inconsistent state, and there's a bunch of code that's broken for reasons unrelated to Askama. I suggest you read Askama's documentation [section on template inheritance](https://djc.github.io/askama/template_syntax.html#template-inheritance) (if you haven't already). I'm happy to answer specific questions or diagnose minimally reproduced issues. If you just want me to write the code for you, you can hire me as on a freelance basis to do that too.

**Comment by grv07** [comment]
Hello @djc ,
I think we can mark this one as closed.

I really like the project and want to contribute as much as possible.
I don't know the policy yet, but I am having a hard time selecting my new bug to work because of no labels and unclosed bugs.

I think a little bug cleaning is required :) .

Thanks,

**Comment by djc** [comment]
@grv07 thanks! I don't have much to suggest, maybe @vallentin has some ideas? If you're up for a bigger project, a handlebars-compatible frontend would be very interesting.

**Comment by vallentin** [comment]
@grv07 If it doesn't specifically have to be a bug, then there's a few things in #427, which might be relatively straight forward to implement, e.g. `loop.length`. If you're interested and unsure how to get started or get stuck, then feel free to reach out :)

I'm just writing a quick comment, so I might know a few bugs, but don't really recall any right now.

-----

One thing that comes to mind, and I'm not even sure whether it's something we can prevent. Is that if you incorrectly do:

```jinja
{{ "foo" + "bar" }}
```
 
 Then the compiler will suggest using `.to_owned()`, but it shows changing `#[derive(Template)]` to `#[derive(Template.to_owned())]`. Not sure if we're able to suppress those hints though.

```console
error[E0369]: cannot add `&str` to `&str`
  --> askama\examples\example.rs:23:10
   |
23 | #[derive(Template)]
   |          ^^^^^^^^ `+` cannot be used to concatenate two `&str` strings
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with
-Z macro-backtrace for more info)
help: `to_owned()` can be used to create an owned `String` from a string reference. String concatenation appends the string on the right to the string on the left and may require reallocation. This requires ownership of the string on the left
   |
23 | #[derive(Template.to_owned())]
   |          ^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0369`.
error: could not compile `askama` due to previous error
```
