### ISSUE TITLE
Whitespace issue with if conditions

### ISSUE THREAD

**Issue by ajeetdsouza** [djc/askama#377]
Askama seems to be including whitespace from inside an if condition even when the condition is not fulfilled. Here is my template file:

```jinja
{%- if some_condition -%}
# WARNING

{% endif -%}

# FILE START
```

What I expected is:

- When `some_condition` is `true`:

  ```
  # WARNING
  
  # FILE START
  ```

- When `some_condition` is `false`:

  ```
  # FILE START
  ```

What I got is:

- When `some_condition` is `true`: same as expected output
- When `some_condition` is `false` (notice the blank lines before `FILE START`):

  ```
  
  
  # FILE START
  ```

Is this a bug? If not, is there a way to get the behaviour I described?

**Comment by djc** [comment]
It sure sounds like a bug! Let me look at some code.

**Comment by djc** [comment]
So the code generation for if statements is here:

https://github.com/djc/askama/blob/main/askama_shared/src/generator.rs#L502

I don't immediately see anything obviously wrong. Maybe you can contribute a test case and/or use the debugging facility (add `print = "code"` to your `template` attribute) to look at the generated code and see what's going on?

**Comment by ajeetdsouza** [comment]
@djc I've added the test. Using `print = "code"` makes the bug more apparent - it's adding the newlines outside the if condition rather than inside:

```rust
fn render_into(&self, writer: &mut dyn ::std::fmt::Write) -> ::askama::Result<()> {
    include_bytes !
("/home/ajeetdsouza/ws/askama/testing/templates/cond-whitespace.txt") ;
    if self.show_preamble {
        writer.write_str("preamble")?;
    }
    writer.write_str("\n\nintroduction\n\nconclusion")?;
    Ok(())
}
```
