### ISSUE TITLE
The operator parser gets precedences wrong

### ISSUE THREAD

**Issue by msrd0** [djc/askama#381]
Consider the expression `a + b == c`. If we changed the code generated from `{lhs} {op} {rhs}` to include parentheses around the entire thing, we get `(a + (b == c))`, which is incorrect, because _(i)_ the `+` and `==` operators combined are not associative (and I think that's true for any two different operators), so need to be evaluated left to right, and _(ii)_ the `==` operator has higher precedence than `+`. It only currently works because askama emits the code unmodified enough for the rust compiler to correct the mistake.

**Comment by djc** [comment]
So precedence is handled here:

https://github.com/djc/askama/blob/main/askama_shared/src/parser.rs#L610

I forgot how I wrote this code in the first place, but I'm guessing the associativity aspect is not handled correctly.
