### ISSUE TITLE
Compilation Error While Compiling Askama Derive

### ISSUE THREAD

**Issue by dbcfd** [djc/askama#386]
```askama_derive-0.10.3/src/lib.rs:27:30
   |
27 |     let config = Config::new(&config_toml);
   |                              ^^^^^^^^^^^^ expected `str`, found enum `std::result::Result`
   |
   = note: expected reference `&str`
              found reference `&std::result::Result<std::string::String, askama_shared::CompileError>
```

```rustc --version
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

**Comment by AlexDBlack** [comment]
Running into this today when building the uniffi_bindgen tool, that relies on Askama.
`askama = { version = "0.10", default-features = false, features = ["config"] }`
https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/Cargo.toml#L21

I installed uniffi_bindgen yesterday on a different machine, no changes on the uniffi side that I can see.

rustc 1.47.0, rustup 1.22.1

Full output of `cargo install uniffi_bindgen` showing the compilation failure can be found in the gist below.
https://gist.github.com/AlexDBlack/636e0e9f0332cf38fc7abc16e879d58d

**Comment by dbcfd** [comment]
Pinning askama_shared to 0.10.4 is a workaround.

**Comment by djc** [comment]
Yeah, I must have broken this when pushing out askama_shared-0.10.5 yesterday. Sorry about that! Will fix it ASAP.

**Comment by djc** [comment]
I recently changed the askama_shared API when fixing issues for #368 (in ac7d9e8031b4df489a0d58dc3459bc931f1ff870). Unfortunately I didn't remember that this pushed out the semver-compatible improvements from #384 as a semver-compatible release of askama_shared. I've now rereleased the same code in askama_shared with a 0.11.0 release number and have pushed out semver-compatible releases for askama_derive and askama (both at 0.10.5) that depend on askama_shared 0.11.0. Additionally, I've yanked askama_shared 0.10.5 to prevent more people from hitting this issue.

Please let me know if you still see any issues, and sorry again for the inconvenience.

**Comment by AlexDBlack** [comment]
Thanks for the quick fix, confirmed building/fixed for me.
