### ISSUE TITLE
Unwanted whitespace in match arm

### ISSUE THREAD

**Issue by msrd0** [djc/askama#397]
For a Template struct containing a field `ver: Option<&'a str>` and the following template:

```jinja2
{% let suffix -%}
{% match ver -%}
  {% when Some with (ver) -%}
    {% let suffix = format!("-{}", ver) -%}
  {% when None -%}
    {% let suffix = String::new() -%}
{% endmatch -%}
```

This code is part of the first match arm: `writer.write_str("\n ")?;`. However, since every line ends with `-%}`, there should't be any newlines inserted into this part of the template.

**Comment by vallentin** [comment]
I'm wondering where the whitespace between the `match` and the first `when` should go. Whether it should go into the first match arm or before the match expression (thus "into" all match arms). The whitespace before `endmatch` is self-explanatory.

In short:

```jinja
{% match ... %}[this whitespace]{% when ... %}
```

Should it result in:

```rust
match ... {
    Some(_) => {
        writer.write_str("[this whitespace]")?;
```

or


```rust
writer.write_str("[this whitespace]")?;
match ... {
```

@djc?

**Comment by djc** [comment]
Maybe we should just skip it always? I don't think there's really a natural place for it to go.
