### ISSUE TITLE
Can't include a file that has macro definitions in it

### ISSUE THREAD

**Issue by Eijebong** [djc/askama#40]
Hey,

It would be great to be able to have macros in a file and be able to include that file in another.
Currently it's hitting `panic!("no extends or macros allowed in content");`.

**Comment by djc** [comment]
Not sure how you're trying to put to your macro definitions to get that error, but that error will remain in there even if you can import macro definitions from another file. It indicates that you're trying to define a macro somewhere not at the top-level of a template file, is that what you're doing?

**Comment by Eijebong** [comment]
Yeah I have a macros.html file with macros definitions in it and am including it in another template.

Do you think there is a better way to fix that than changing how include currently works and parse the included file at the beginning and include its nodes in the current template nodes ? (parse it here and append nodes to the current nodes somehow) https://github.com/djc/askama/blob/master/askama_derive/src/generator.rs#L17

**Comment by djc** [comment]
Jinja very clearly separates `include` and `import`, as far as I can tell, where `include` basically renders the included file into the including template while `import` makes the macros from the imported template available to the importing template. So your use case seems to need an import mechanism. In terms of implementation, it could perhaps function similarly to the handling for `defmacro`, in the sense that top-level `import` blocks are removed from the AST and instead result in having some macros added to the macro map.

**Comment by djc** [comment]
Thanks to @larros for fixing this!
