### ISSUE TITLE
Version 0.10 places Copy value literals behind a reference where 0.9 did not

### ISSUE THREAD

**Issue by agraven** [djc/askama#404]
I have a large collection of templates that compiles perfectly fine with version 0.9 of askama, but when I try to upgrade to 0.10, I get a bunch of type errors because a bunch of `Copy` types that were previously passed as values now get placed behind a reference

**Comment by djc** [comment]
Sorry for breaking your templates! Are these types being passed to macros, or to custom filters? Can you give an example?

We have some things in the works that will hopefully fix this.

**Comment by agraven** [comment]
Just off the top of my head, boolean literals, i.e. `true` and `false` are both passed to functions as `&true` and `&false`, and similarly `Copy` enum literals are placed behind a reference as well. There's some additional cases but I need to look closer to see exactly what happens in those

**Comment by vallentin** [comment]
As djc mentioned, it's in the works, that literals will be back to being moved by value. With the exception that fields from the template itself would still be referenced, and thus require `clone()` i.e. `{{ self::and(self.b1.clone(), true) }}`.

If you have any specific examples, different than variations of that case, then feel free to share it.

Also, hello fellow Dane! :)

**Comment by vallentin** [comment]
@agraven the issue should now be resolved. Feel free to try building with the repository as a dependency, to verify if all your issues have been resolved. If not, please re-open or create a new issue.

```toml
[dependencies]
askama = { git = "https://github.com/djc/askama", rev = "f9db444" }
```

Note that e.g. `{{ self::foo(true) }}` should work now. However, if a field is used, then that requires an explicit clone, e.g. `{{ self::foo(self.b.clone()) }}`.

**Comment by danielalvsaaker** [comment]
@vallentin When can we expect this change to be published to the crate?

**Comment by vallentin** [comment]
@danielalvsaaker I think we want to resolve a few more things, until we publish a new version.

That said, @djc is in charge of publishing :)

**Comment by djc** [comment]
I opened #451 to discuss the next release.
