### ISSUE TITLE
TechEmpower no longer uses askama

### ISSUE THREAD

**Issue by botika-fix-bench** [djc/askama#406]
Your README is ~a lie~ confusing, the template engine used in actix and ntex in TechEmpower is yarte. They only uses askama with actix-diesel with disastrous results. Delete it please.

**Comment by vallentin** [comment]
It's not a lie. The README refers to a [quote from Nikolay Kim][tweet].

[tweet]: https://twitter.com/fafhrd91/status/998646827426635776
