### ISSUE TITLE
Filters have precedence over unary operators

### ISSUE THREAD

**Issue by vallentin** [djc/askama#424]
Performing e.g. `{{ -2|abs }}` is parsed as `{{ -(2|abs) }}` resulting in `-2` being rendered.

**Comment by vallentin** [comment]
This specific issue can be fixed.

However, apparently Jinja doesn't seem to specify precedence in relation to filters in their documentation. Which apparently is a long standing issue (pallets/jinja#379), that has created confusion.

I just tried a few things in Jinja, and apparently `{{ 2 + 3|abs }}` is parsed as `{{ (2 + 3)|abs }}` resulting in `5` while ``

{{ "abc" + "abc"|length }}

**Comment by djc** [comment]
Oops -- we should fix that!
