### ISSUE TITLE
askama hang cargo build

### ISSUE THREAD

**Issue by miocs-xyz** [djc/askama#430]
OS: Archlinux
Kernel: 5.4.87-1-lts
gcc version 10.2.0 (GCC)

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

```toml
[dependencies]
askama = "0.10.5"
actix-web = "4.0.0-beta.1"
```

```
 Compiling mioblog v0.1.0 (/home/julian/Workspace/mioblog)
     Running `rustc --crate-name mioblog --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=af3725a7b70051f1 -C extra-filename=-af3725a7b70051f1 --out-dir /home/julian/Workspace/mioblog/target/debug/deps -C incremental=/home/julian/Workspace/mioblog/target/debug/incremental -L dependency=/home/julian/Workspace/mioblog/target/debug/deps --extern actix_web=/home/julian/Workspace/mioblog/target/debug/deps/libactix_web-1a8117679087be69.rmeta --extern askama=/home/julian/Workspace/mioblog/target/debug/deps/libaskama-6ffb5f01c81874ac.rmeta -L native=/home/julian/Workspace/mioblog/target/debug/build/brotli-sys-ab706ca0d133ec2a/out`
    Building [=====================================================> ] 218/220: mioblog        
```

**Comment by djc** [comment]
How do you know Askama is at fault? Do you have any recursive includes or imports?

**Comment by miocs-xyz** [comment]
At first, I thought that actix-web hang the build, but when I disable askama, the build was completed. But if I enable askama, the build was hang.
And, It seem to work fine in gcc 9.3.0. Only have the problem in gcc 10.2.0.

**Comment by djc** [comment]
I'm not sure how gcc is involved. And even if I did, it's unclear how I could debug this as long as I don't have something I can reproduce this.

**Comment by miocs-xyz** [comment]
I have also no idea if the problem was the version of gcc or the implementation for archlinux, since I compile the application on ubuntu 20.10, and got the same issue (the version of gcc in ubuntu 20.10 seems also 10.x). So I think its the issue only in gcc 10.x.  There was no error and log. only hangs when compiling the source include askama.
I can build it successfully with gcc 9.2.0(mingw64) and gcc 9.3.0(alpinelinux docker image ). So, the issue did not affect my project.
I was only want to report that there had this issue in gcc 10.x, and does anyone has the same issue?

**Comment by djc** [comment]
I don't see how the gcc version can have an effect on how Askama works, so I'm going to close this. Feel free to reopen if you can provide more details about the circumstances of what Askama might be getting wrong.
