### ISSUE TITLE
Loading template trait in another template

### ISSUE THREAD

**Issue by jvdwrf** [djc/askama#439]
Hi,

I have been trying to render nested templates without knowing in advance which template will be nested. I know that it is possible using child templates, and that is what I am using now, however it would be nice to be able to render them in the other way as well. An example of what I mean:

```
#[derive(Template)]
#[template(path = "base.html")]
struct Base<'a> {
    title: &'a str,
    template: Box<dyn Template>,
}
```
And then the html file:
```
  <head>
    <title>{{ title }}</title>
  </head>
  <body>
    <div id="banner">
      Welcome! <br>
    </div>
    <div id="content">
      {{ template }}
    </div>
  </body>
```

Right now it is complaining that Template does not implement Display. Is it possible to do this already or can this not be done?

**Comment by djc** [comment]
`Template` impls should also implement `std::fmt::Display`. What happens if you turn the type into `Box<dyn Display>`?

**Comment by jvdwrf** [comment]
Once i change it to impl Display the error dissapears.

**Comment by jvdwrf** [comment]
```
`dyn askama::Template` doesn't implement `std::fmt::Display`
the trait `std::fmt::Display` is not implemented for `dyn askama::Template`
in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
required because of the requirements on the impl of `std::fmt::Display` for `&dyn askama::Template`
required because of the requirements on the impl of `std::fmt::Display` for `&&dyn askama::Template`
required by `MarkupDisplay::<E, T>::new_unsafe`rustc(E0277)
```

**Comment by djc** [comment]
Can you monomorphize it instead of using dynamic dispatch (i.e. `impl Display`)?

**Comment by jvdwrf** [comment]
```
#[derive(Template)]
#[template(path = "base.html")]
struct Base<'a, T: Template> {
    title: &'a str,
    template: T,
}
```
Is this what you mean? Otherwise I don't quite get what your idea is, I can't set the type to impl Template.

This does not fix the problem. Error message:
```
`T` doesn't implement `std::fmt::Display`
in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
required because of the requirements on the impl of `std::fmt::Display` for `&T`
```

**Comment by djc** [comment]
Okay, now try with `T: std::fmt::Display` (but pass in a type that is `Template`)? (You can also use `T: Template + std::fmt::Display` for clarity.)

**Comment by jvdwrf** [comment]
Yes, okay that works at least, with `T: Template + Display.`

Now, however, when trying to render a nested template wiht html, so for example:
```
#[derive(Template)]
#[template(path = "base.html")]
struct Base<'a, T: Template + Display> {
    title: &'a str,
    template: T,
}
```
and passing along a template like
```
<b>Hi!</b>
```
and rendering it like this, where sub_template is the unrendered Template Struct.
```
let template = Base { template: sub_template, title };
Ok(Response::builder(StatusCode::Ok).content_type(mime::HTML).body(template.render().unwrap()).build())
``
my response gets escaped like this:
```
&lt;b&gt;Hi!&lt;&#x2f;b&gt
```
So probably it's converting first to a string, and then obviously escaping since it would be the proper thing to do.
I'm not sure whether this would be the intended way this would work, however for my scenario this would not work

Thanks by the way for the help!

**Comment by djc** [comment]
Yeah, unfortunately we don't have a good way to distinguish between `Template` `Display` impls and other `Display` impls, so we just escape them all. You can apply the `safe` filter to `template`, though, right?

**Comment by jvdwrf** [comment]
Yes I could, however the template could contain both safe and user-input data. Then I would not be escaping at all right?

**Comment by jvdwrf** [comment]
Oh wait that might actually work, give me 1 sec to try

**Comment by jvdwrf** [comment]
I think that works, thanks!
It renders the first template first, escaping html-tags, and then renders the second part overtop right?

**Comment by djc** [comment]
Actually, the way it works it kind of renders the inner template into the buffer for the outer template's output, if that makes sense.
