### ISSUE TITLE
Next release planning

### ISSUE THREAD

**Issue by djc** [djc/askama#451]
@vallentin I forget what things I still wanted to resolve before releasing... Do you have anything else you would like to land in the short term?

**Comment by vallentin** [comment]
Here's a few from my TODO.md:

- [ ] `{{ None }}` produces `self.None`
- [ ] `{{ Some("foo") }}` produces `(self.Some)("foo")`
- [ ] `{% let (x) = (2) %}` produces `let (x) = (2);`, which is semantically wrong and should be `let (x,) = (2);`
   - or `let x = (2);` of course
- [ ] `.zip(0..5)` produces `.zip(&0..5)` instead of `.zip(0..5)`
   - _Might have been fixed_

Then of course also doing the ones from #427, that we agreed on. Though overall I just wanna iron out the bugs.

Been a bit busy for the past month, but I think I'll be able to fix those bugs in the upcoming weekend.

**Comment by djc** [comment]
Sounds good -- let's see where we are on Monday.

**Comment by vallentin** [comment]
One of them was already fixed, but I've fixed the 3 other bugs.

I also discovered an additional bug (I've edited the previous comment).

**Comment by djc** [comment]
I think it's past time we got this out. @vallentin when would you have time to investigate #494?

**Comment by vallentin** [comment]
If it can wait until Thursday / the weekend, then yes :)

**Comment by djc** [comment]
Yeah, that should be fine.

**Comment by djc** [comment]
I'll see if I can spend some time on this tomorrow (mostly writing up a change log).

**Comment by vallentin** [comment]
Was #494 the "last" important bug, before the new release? Just glancing through this issue and #427, then it seems the remaining stuff is new features.

When you start writing the change log, feel free to make a draft PR, then I'll comment any missing stuff I recall. I guess one of the most important things, is highlighting the change to the implicit borrowing. Mentioning that literal primitives and the result of functions are no longer borrowed.

**Comment by djc** [comment]
At this point I'll probably wait for the nom 7 release, which should help with the silly dependencies.

https://github.com/Geal/nom/issues/1323#issuecomment-890846534

**Comment by kristoff3r** [comment]
Since nom 7 has been released, is there anything else blocking a release?

**Comment by djc** [comment]
I need to review/decide on #517 and #518 and then I need to write some release notes.

**Comment by djc** [comment]
I wrote up draft release notes: https://github.com/djc/askama/releases/edit/untagged-1f87fb7743ec53e520b9. @vallentin and @Kijewski, would you please review to see if anything important is missing or should be highlighted more?

**Comment by vallentin** [comment]
Maybe the "General changes" should be split up, so e.g. bug fixes are moved to the bottom of the description, e.g. #394 most probably haven't encountered this. Then "General changes" could be easier to glance through, so users can more easily spot the "real" changes, that affect them or they're interested about

**Comment by Kijewski** [comment]
A project this big can never be free of errors, that will only show themselves after the release. I think the changelog addresses to the users' interests quite well.

**Comment by djc** [comment]
I've published updates for askama_escape, askama_shared, askama, askama_derive, askama_warp, askama_tide and askama_gotham. askama_axum depends on #583; askama_actix and askama_rocket depend on #584. That leaves askama_mendes.
