### ISSUE TITLE
Proper file extension for templates for plugin integration?

### ISSUE THREAD

**Issue by josefrcm** [djc/askama#457]
First of all, let me congratulate you for your work. I'm developing an application with Askama and Rocket, and I'm very happy with the results. However, I recently hit an interesting bump. This was using VS Code as my development environment:

- As the templates are all HTML, I'm just using `.html` extension.
- The HTML formatting plugins don't recognize Askama templates. That means no syntax highlighting, no error detection, and no proper formatting. In fact one plugin completely mangled a few templates and caused my website to crash.
- As Askama is based on Jinja2, I tried to rename my files as `.html.j2` and use a Jinja2 plugin (no Askama plugin seems to exist), and lo and behold, it worked perfectly. Syntax highlighting and proper formatting. The code compiles and runs flawlessly, but...
- Askama's Rocket responder implementation guesses the content type from the file extension, but `.html.j2` is not recognized, so it just returns an empty response! No error message, no nothing, just a totally blank page.

So my question is, how can we fix this? I have a couple ideas:

- Write a proper Askama plugin with its own file extension, or reuse an existing Jinja2 plugin, even if the two syntaxes don't match perfectly?
- Fix the responders implementations to strip the last part of the extension from the file name, in case it matches a predefined list.

**Comment by josefrcm** [comment]
@vallentin I just tested your solution and it works perfectly, thank you so much for the quick response 😀

**Comment by vallentin** [comment]
@josefrcm no problem, happy I could help 😄
