### ISSUE TITLE
Tuple support

### ISSUE THREAD

**Issue by larros** [djc/askama#47]
I haven't found a way to use tuples in a template. It would be great with support both for tuple indexing and destructuring assignments with let.

It seems that the only thing stopping tuple indexing is that identifiers are not allowed to start with numbers. I'm not sure changing the identifier rule is the best solution though because it would not be valid for all usages of identifiers.

**Comment by djc** [comment]
Makes sense. We can introduce a new rule that's effectively `alt!(number_literal | identifier)` and use that for the dot operator. Do you want to write up a patch?

As for destructuring, there is some very rough support in that direction, search for "target" in the parser, which is used in the loop header and variable assignments. It shouldn't be too hard to extend that to support tuples.

**Comment by larros** [comment]
Sure, I'll make a try at the tuple indexing. It looks like it should be quite easy.

**Comment by vallentin** [comment]
Was this issue solely about indexing and destructuring? Because if so, then it can be closed.

Unless, this issue also implicitly asks for support of e.g. `{% let x = ("foo", "bar") %}`?

**Comment by djc** [comment]
Let's close it for now.
