### ISSUE TITLE
Use raw identifiers when expanding the macro

### ISSUE THREAD

**Issue by SciStarter** [djc/askama#473]
When expanding the template macro, it would be nice to replace all of the identifiers defined in the template with [raw identifiers](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/raw-identifiers.html) in the generated code. 

Currently, Rust keywords are sort-of reserved words in the template, in that they trigger weird errors, but they are neither called out as explicit errors nor allowed in working code. Using raw identifiers would allow them to work with no issues.

**Comment by djc** [comment]
I'm open to doing this but only for Rust keywords. Are you willing to submit a PR?

**Comment by SciStarter** [comment]
I am, but why only for Rust keywords? Doing it all the time seems both
simpler and more general.

**Comment by djc** [comment]
It makes the generated code uglier/harder to read -- and it's not like doing it for keywords only incurs a lot of complexity.

**Comment by vallentin** [comment]
Resolved in #476
