### ISSUE TITLE
Cannot import multiple templates

### ISSUE THREAD

**Issue by Restioson** [djc/askama#482]
When trying to import multiple templates with two separate import directives, the second is always ignored, yielding `error: macro 'second' not found in scope '...'`. [Minimised reproducible project](https://github.com/Restioson/askama-import-bug).

**Comment by vallentin** [comment]
In `second_imported.html` the macro is defined as `goodbye`. However, in `main.html` you attempt to call `second::hello()`. If you change it do `{%- call second::goodbye() -%}`, then it works.

**Comment by Restioson** [comment]
Sorry for the confusion!

**Comment by vallentin** [comment]
No need to say sorry :) and yeah as you said, it was a win win and another bug got discovered and fixed :)
