### ISSUE TITLE
Build fails with error[E0601]: main function not found

### ISSUE THREAD

**Issue by greatest-ape** [djc/askama#49]
I have a project using Tera where I want to use Askama instead. It consists of a library and two executables. After adding the recommended build.rs file, building fails with: error[E0601]: main function not found.

The code in question is available here: https://github.com/greatest-ape/rs_news/tree/askama , see commit bff1d68f12c786a3a37f8cc5739e90ed73daa834.

I run macOS 10.10.5, rustc 1.22.0-nightly (0701b37d9 2017-09-18), but I get the same error on Debian.

**Comment by djc** [comment]
Hey, thanks for trying Askama!

I spent about half an hour looking at your code and trying to compile it with a recent nightly compiler, but I get the same error as you, which, BTW, seems to originate [here](https://github.com/rust-lang/rust/blob/afb853a3d742ada964ea06cccd422b08ea250cd3/src/librustc/middle/entry.rs). I [asked](https://botbot.me/mozilla/rust/2017-09-23/?msg=91479090&page=15) in #rust on IRC, but the one person responding there also didn't have a clue.

It seems pretty unlikely to me that Askama is actually at fault for this error message. I tried a few things to see if I could figure out exactly what about the changes between `master` and `askama` started triggering this problem, but no luck so far. Perhaps you can investigate along these lines, trying to reduce the diff between the branches until it no longer errors?

Also, I looked at your commit https://github.com/greatest-ape/rs_news/commit/bff1d68f12c786a3a37f8cc5739e90ed73daa834 and was a bit surprised. This looks seriously ugly, and I haven't seen problems like this coming up in my tests so far. I'll try to dig a bit deeper, maybe you can file a bug about this problem, too?

**Comment by greatest-ape** [comment]
Thank you for your answer.

That is strange. I'll create a new project and try to reproduce the error with as little other code as possible.

I filed a new issue about the borrowing error.

**Comment by djc** [comment]
Good to hear you got it fixed!

**Comment by Tirka** [comment]
I have same issue with [rocket](https://rocket.rs) framework and nightly compiler. I prepared [sample crate](https://github.com/Tirka/askama-rocket-bug) based on [this](https://github.com/djc/askama/blob/master/testing/tests/rocket.rs) askama example.

`rustc --version`:
`rustc 1.37.0-nightly (4edff843d 2019-06-16)`

If you do `cargo run`:
![image](https://user-images.githubusercontent.com/6426670/59578379-95109500-90d0-11e9-8c31-e4b2ddc2399f.png)


If you comment first line of 'main.rs' `#![cfg(feature = "with-rocket")]` and do `cargo run`:
![image](https://user-images.githubusercontent.com/6426670/59578458-f6d0ff00-90d0-11e9-9648-dd94d5a76fd6.png)

**Comment by Tirka** [comment]
Problem solved by removing `#![cfg(feature = "with-rocket")]` line and adding askama dependency to `Cargo.toml` with rocket feature enabled: `askama = { version = "0.8", features = ["with-rocket"] }`

You can find working crate sample [here](https://github.com/Tirka/askama-rocket-bug)

**Comment by djc** [comment]
Sorry that I didn't manage to get back to you -- happy that you've solved it! It was likely that this wasn't a bug in Askama, which is part of why I didn't respond sooner.
