### ISSUE TITLE
Whitespace before endif is rendered after if block

### ISSUE THREAD

**Issue by msrd0** [djc/askama#490]
Consider the following code:

```rust
#[derive(Template)]
#[template(source = "{%for byte in list%}{{byte}}{%if !loop.last%}, {%endif%}{%endfor%}", ext = "txt", print = "code")]
struct TestTemplate<'a> {
	list: &'a [u8]
}
```

This should print a list of numbers, e.g. `1, 2, 3`. However, what it prints instead is `1, 2, 3 `, which is not what I want and not what is defined in the template. This is likely due to the whitespace after the `,` and before the `endif` is rendered after the `if` block in the generated rust code:

```rust
impl < 'a > ::askama::Template for TestTemplate< 'a > {
    fn render_into(&self, writer: &mut dyn ::std::fmt::Write) -> ::askama::Result<()> {
        for (byte, _loop_item) in ::askama::helpers::TemplateLoop::new((&self.list).into_iter()) {
            write!(
                writer,
                "{expr0}",
                expr0 = &::askama::MarkupDisplay::new_unsafe(&byte, ::askama::Text),
            )?;
            if !_loop_item.last {
                writer.write_str(",")?;
            }
            writer.write_str(" ")?;
        }
        Ok(())
    }
    fn extension(&self) -> Option<&'static str> {
        Some("txt")
    }
    fn size_hint(&self) -> usize {
        0
    }
}
```

Here's the parsed AST in case it helps:

```
[Loop(WS(false, false), Name("byte"), Var("list"), [Expr(WS(false, false), Var("byte")), Cond([(WS(false, false), Some(Unary("!", Attr(Var("loop"), "last"))), [Lit("", ",", " ")])], WS(false, false))], WS(false, false))]

**Comment by msrd0** [comment]
Workaround is to replace `, ` with string literal `{{", "}}`

**Comment by vallentin** [comment]
Damn, I thought I fixed all these cases :)

**Comment by djc** [comment]
Thanks for the minimal reproduction! Can you reproduce this with main? It seems to work for me.

**Comment by msrd0** [comment]
I can confirm that this problem does not appear on the main branch.

However (off-topic, I can open another issue if you want), I'm rather unhappy about the fact that invoking a function with both a variable and a literal now involves manually calling `.borrow()` on the literal: https://github.com/msrd0/bitmap-font/commit/f8f66f42ce88dca912bd6105bd63de0bea32c8e2#diff-3967ea9f7da3e8d2ecc5179bad2129d3f618d6379fc329161ecf9c2df023e524

**Comment by djc** [comment]
Yes, please open a separate issue about that. That does seem like a regression.

**Comment by msrd0** [comment]
I opened #492
