### ISSUE TITLE
Are all variables in templates references ? How to create complexe structs ?

### ISSUE THREAD

**Issue by jrouaix** [djc/askama#497]
Hello, 

I have pretty awesome experience with askama so far, yet struggling with something here :

Let's say I want to init a struct with a String value in it :
```
 {% let user = framework::domain::Username::new("User!".to_string()) -%}
```
```
        {% let username = "User!".to_string() -%}
        {% let user = framework::domain::Username::new(username.clone()) -%}
```
```
        {% let username = "User!".to_string() -%}
        {% let user = framework::domain::Username::new(username) -%}
```

None of these working ? I suspect it's by design ? Would it be some magical wizardry I could invoke to fit my need ?
(it's in the base template, and I'd like not to add a value in all template models) 
```
expected struct `std::string::String`, found `&std::string::String`
```

Any idea ?

**Comment by djc** [comment]
Yeah, templates are really not designed to do this; we kind of expect all variable assignments to be references. I suspect you'd have a better time if you inserted this directly into where you want to splice it into the template's output.

**Comment by jrouaix** [comment]
well ... thank you ... at least now I know the limits
