### ISSUE TITLE
What is the point of path based name?

### ISSUE THREAD

**Issue by dtolnay** [djc/askama#5]
What is this useful for?

```rust
#[allow(dead_code, non_camel_case_types)]
type TemplateFromhello2ehtml<'a> = HelloTemplate<'a>;
```

**Comment by djc** [comment]
It was used for inheritance; because the inheriting template includes the path name. I guess now that the inheriting template has a mandatory `_parent` field, I guess this is no longer strictly necessary.

**Comment by dtolnay** [comment]
Yeah I understood the TraitFromhello2ehtml types in the context of inheritance but TemplateFrom never seemed to be used.
