### ISSUE TITLE
Without clone() in template, error[E0507]: cannot move out of borrowed content

### ISSUE THREAD

**Issue by greatest-ape** [djc/askama#50]
The compiler fails when not using clone() on a struct field inside of the template.

See https://github.com/greatest-ape/rs_news/tree/askama-template-borrowing-issue

The error occurs in [this commit](https://github.com/greatest-ape/rs_news/commit/7400b9e0785a78656dcbd33d9f091c02c587d24d)  and is fixed with the change in the [next commit](https://github.com/greatest-ape/rs_news/commit/8c907d8f3a5d7d46231ebd2b71e9983b6310f7ee).

Using rustc 1.22.0-nightly (14039a42a 2017-09-22) on macOS.

**Comment by djc** [comment]
So I finally had some time to experiment with this use case. There's probably not a straightforward fix for this: the `Option` is owned by the template struct and so far Askama has always passed an immutable reference only. You can replace the `clone()` you did by `as_ref()`, which seems to have much the same result without doing an expensive clone, but the ergonomics aren't much better.

I'm still wondering whether I should change Askama to consume the struct instead, I'll play around and see if that would help with this issue.

**Comment by djc** [comment]
BTW, I think #54 would also help a lot by making it more ergonomic to use enums generally.

**Comment by djc** [comment]
So #54 has landed; I'll close this now.
