### ISSUE TITLE
cannot compare strings in macros

### ISSUE THREAD

**Issue by yatesco** [djc/askama#502]
Hi - I have a macro which accepts a string argument but when I try and compare it I get "can't compare `&str` with `str`:

```
{% macro heading(title, sort) %}

<th class="tableHeaderSort">
  {{ title|e }}
  <span class={% if sort == "descending" %} "descending selected" {% else %} "descending" {% endif %}></span>
  <span class={% if sort == "ascending" %} "ascending selected" {% else %} "ascending" {% endif %}>

  </span>
</th>

{% endmacro %}

{% call heading("Closed", "ascending") %}
```

I've read #376 which I think suggest that this should work. 

Any help is gratefully appreciated! Thanks

**Comment by djc** [comment]
Does this work outside a macro context?

**Comment by yatesco** [comment]
Yes it does. 

I didn't realise I could put rust code right inside the template so using enums instead of Strings works fine in macros:

```
{% macro heading(title, sort) %}
<th class="tableHeaderSort">
  {{ title|e }} {% match sort %} {% when SortBy::Descending %}
  <span class="descending selected"></span>
  <span class="ascending"></span>
  {% when SortBy::Ascending %}
  <span class="descending"></span>
  <span class="ascending selected"></span>

  {% when SortBy::None %}
  <span class="descending"></span>
  <span class="ascending"></span>

  {% endmatch %}
</th>
{% endmacro %}

{% call heading("Closed", SortBy::None) %}
```

(and yes, using `Option<SortBy>` is an upgrade from here :-))

**Comment by vallentin** [comment]
This should be fixed, but not released yet. Could you try and verify using the repo? :)

Like this:

```toml
[dependencies]
askama = { git = "https://github.com/djc/askama", rev = "017b590" }
```

**Comment by yatesco** [comment]
@vallentin - Yes, it works fine against that revision :-)

**Comment by vallentin** [comment]
Great! If that was all, then I'll close this issue, as it's been fixed and will be included in the next release :)
