### ISSUE TITLE
Confused about composing templates with state

### ISSUE THREAD

**Issue by yatesco** [djc/askama#508]
Hi - I have a main template "parent" which includes "child". The child template requires some state.

When calling the parent, how do I "lift" the child state to the top level so that when I include the child template the data is accessible to it.

For example:

```rust
struct ChildState {
  count: u32;
}

struct ParentState {
  child_state: ChildState
}
```

with templates:

```
--child.html
{{count|e}}

-- parent.html
{% include "child.html" %}
```

when calling the parent the child state isn't accessible as `count` only `child_state.count` which obviously breaks the child's rendering.

It is also important that I can render both the Parent and Child independently.

Thanks!

**Comment by djc** [comment]
Have you considered using template inheritance for this rather than includes?

**Comment by yatesco** [comment]
I can’t see how that would work out - child cannot inherit from parent because child needs to be rendered independently of the parent.

I might be missing your point though

**Comment by djc** [comment]
I'm not sure exactly what you mean by "independently". Template inheritance does still mean you can render the parent or the child, but the child template can inherit some of the content from the parent template.

**Comment by yatesco** [comment]
Thanks @djc - I'm struggling to see how to reference state because when I render the child template I only provide "ChildState { count: ...}" so the child template evaluates "{{ count|e }}" but when I include the template in the parent template, the state is no longer at "count" but rather "child_state.count".

I'm almost certainly missing something fundamental here.

**Comment by djc** [comment]
Have you read the template inheritance docs in the book and tried to implement it? I'm sorry that you're running into trouble, but I don't have a lot of time to provide (unpaid) support for this project.

**Comment by yatesco** [comment]
I have read it, understand it and am using it to good effect - my question isn't really about inheritance - it is the other way around :-). 

My question is simply: before calling a child template, how do I move state out of "child_struct.count" to "count" so that the child template can access it as "{{ count|e }}".

I'm not in front of the code at the moment, but I wonder if it is it as simple as this in the parent template:
```Jinja
{% let count = child_state.count %} {# lift the count property from the parent's nested struct to the top level context #}
{% include "child_template_expecting_a_count_property" %}
```

I'll experiment some more....

**Comment by djc** [comment]
I think that might work, yes. Are you also aware of the macro functionality?

**Comment by yatesco** [comment]
Yes - you did tell me about the macros before, which is a much better approach. Closing for now - thanks for all your help!
