### ISSUE TITLE
Whitespace suppression not honored for macro blocks

### ISSUE THREAD

**Issue by larros** [djc/askama#52]
Whitespace before and after macro blocks are not suppressed even though the suppression is used. The parser supports the syntax but the macro nodes are excluded from the code generation. The solution to this is to include macro nodes in code generation but only for the purpose of whitespace supression.

Example: 
``` rust
#[derive(Template)]
#[template(source = "{% macro foo(bar) %}{% endmacro -%}\nafter", ext="txt")]
struct SuppressTemplate {
}

#[test]
fn test_suppress() {
    let t = SuppressTemplate{};
    assert_eq!(t.render().unwrap(), "after");
}
```
Fails with:
´´´
'assertion failed: `(left == right)`
  left: `"\nafter"`,
 right: `"after"`
´´´

**Comment by djc** [comment]
Sounds good to me, do you want to create a PR for this? One thing to think about is how to error out on templates that put macro definitions on anywhere but the top-level -- that needs to be preserved (ideally, tested).

**Comment by larros** [comment]
I can take a look at this after the import is completed. The import nodes have the the same problem as macros.

**Comment by djc** [comment]
Thanks, that would be great!

**Comment by larros** [comment]
I've started looking at this now and I think I know what the end result should be. I just want some confirmation.

These are my current thoughts
- The outer white space rules on the macro node should apply to the macro declaration site
- The inner white space rules on the macro node should apply to the call site
- The white space rules on the call node should apply to the call site

**Comment by djc** [comment]
That sounds exactly right!
