### ISSUE TITLE
Shadowing a loop variable does not work

### ISSUE THREAD

**Issue by marienz** [djc/askama#525]
Using Askama 0.10.5, trying to shadow a loop variable with the following template (where `opt` is a `Vec<Option<String>>`):

```jinja
{% for opt in opts %}
  {% let opt = opt.as_ref().unwrap() %}
  {{ opt }}
{% endfor %}
```

expands to the following code:

```rust
    fn render_into(&self, writer: &mut dyn ::std::fmt::Write) -> ::askama::Result<()> {
        include_bytes ! ("/tmp/lets_askama/templates/many.html") ;
        for (opt, _loop_item) in ::askama::helpers::TemplateLoop::new((&self.opts).into_iter()) {
            opt = opt.as_ref().unwrap();
            write!(
                writer,
                "\n  \n  {expr0}\n",
                expr0 = &::askama::MarkupDisplay::new_unsafe(&opt, ::askama::Html),
            )?;
        }
        Ok(())
    }
```

which does not compile, because it's not shadowing `opt`, it's trying to reassign it. If I do the same thing outside a loop, it does shadow (as documented). And the code inside the loop works if I don't shadow (rename the loop variable and write `let opt = maybe_opt...`).

Is this just a bug (in which case I'm happy to take a stab at fixing it), or am I holding it wrong?

**Comment by djc** [comment]
Probably try main first? We've had a lot of changes...

**Comment by marienz** [comment]
My bad, I should've tried that... Using https://github.com/djc/askama#d45e106b, it generates the code I expected:

```rust
    fn render_into(&self, writer: &mut dyn ::std::fmt::Write) -> ::askama::Result<()> {
        include_bytes ! ("/tmp/lets_askama/templates/many.html") ;
        for (opt, _loop_item) in ::askama::helpers::TemplateLoop::new(((&self.opts).into_iter())) {
            writer.write_str("\n  ")?;
            let opt = opt.as_ref().unwrap();
            write!(
                writer,
                "\n  {expr0}\n",
                expr0 = &::askama::MarkupDisplay::new_unsafe(&(opt), ::askama::Html),
            )?;
        }
        Ok(())
    }
```

**Comment by marienz** [comment]
...and #510 mentions fixing this, so I should've searched a little harder (specifically: searched commits and pull requests, not just issues).

**Comment by djc** [comment]
Thanks for testing, #451 is tracking the next release.
