### ISSUE TITLE
Support for global paths in if conditions

### ISSUE THREAD

**Issue by ajeetdsouza** [djc/askama#533]
This line works:

```
{% if std::env::var_os("foo").is_some() %}
foo
{% endif %}
```

But this doesn't:

```
{% if ::std::env::var_os("foo").is_some() %}
foo
{% endif %}
```

It would be nice if Askama could support global paths to call functions unambiguously. Thanks for making this project!

**Comment by djc** [comment]
Have you tried this with main branch? There's been a fair amount of development since the last release, so it's quite possible this has been fixed since the last release.

**Comment by ajeetdsouza** [comment]
It works on main. Thanks!
