### ISSUE TITLE
How can I print a literal `{#`?

### ISSUE THREAD

**Issue by ajeetdsouza** [djc/askama#534]
I want to print a literal `{#`, but that's also the syntax for comments in Askama. Is there any way to do this other than `{{ "{#" }}`?

**Comment by Kijewski** [comment]
It's not pretty, but ``{ {#- -#} #`` works. I.e. breaking up the token with a comment in the middle.

**Comment by vallentin** [comment]
or even shorter with `{ {#-#}#`. Though, like @Kijewski said it's not pretty, and I'd definitely say use `{{ "{#" }}` for clarity.

**Comment by ajeetdsouza** [comment]
Hm, fair enough. It may be worthwhile figuring out if there's an elegant way to escape here, though.

@djc, I'd love to hear your thoughts on this.

**Comment by djc** [comment]
Well, we also support [customizing the syntax](https://djc.github.io/askama/configuration.html) in the `askama.toml` file. Would that help with your use case?

**Comment by ajeetdsouza** [comment]
Hm, that's fair. I suppose I could just configure it to use a different start token instead. Thanks!

**Comment by praveenperera** [comment]
> Well, we also support [customizing the syntax](https://djc.github.io/askama/configuration.html) in the `askama.toml` file. Would that help with your use case?

is it possible to use a different expr_start and end for only one template?

**Comment by djc** [comment]
You can specify the `syntax` to use in a `template()` attribute, which should allow that.

**Comment by praveenperera** [comment]
askama is awesome, thank you
