### ISSUE TITLE
Passing template variables to base (extends) templates

### ISSUE THREAD

**Issue by kellytk** [djc/askama#535]
I can pass a variable to a template by declaring it on the template's struct and then passing it to the struct upon definition.  If that template `extends` a base template, how should the variable be passed to the base template?

**Comment by vallentin** [comment]
One way you can do it, is to have a field in all your template `struct`s, that is both named the same and has the same type. That way you then access that "base" data, in your `base.html`. As an example:


```rust
struct BaseTemplateData {
    title: String,
}

#[derive(Template)]
#[template(path = "index.html")]
pub struct IndexTemplate {
    base: BaseTemplateData,
}

#[derive(Template)]
#[template(path = "about.html")]
pub struct AboutTemplate {
    base: BaseTemplateData,
}
```

Then in `index.html` and `about.html`, assuming you have `{% extends "base.html" %}`, then in `base.html` you'll be able to do:

```jinja
<title>{{ self.base.title }}</title>
```

**Comment by kellytk** [comment]
Thank you.
