### ISSUE TITLE
Rust's raw identifiers in variable access

### ISSUE THREAD

**Issue by kellytk** [djc/askama#540]
From the documentation:

    You can use a dot (.) to access variable's attributes or methods.

`{% match f.fieldtype() %}` runs as expected, however `{% match f.r#type() %}` generates an error `unable to parse template`.

**Comment by vallentin** [comment]
Can you check again the main branch? This might have been fixed in #476

**Comment by vallentin** [comment]
If you're using the main branch. Then try using just `{% match f.type() %}`. Askama does not support _raw identifiers_, but the previously mentioned PR implements, so the generator automatically maps e.g. `type` to `r#type`, when it generates Rust code for the template.

**Comment by kellytk** [comment]
With that code the error is `expected identifier, found keyword 'type'`.

`rustc --version` 1.57 nightly 2021-9-12
