### ISSUE TITLE
escape filter does not escape when escape attribute is set to none

### ISSUE THREAD

**Issue by wezm** [djc/askama#556]
Perhaps this is just a documentation issue but following the recursive macro workaround described in https://github.com/djc/askama/issues/105#issuecomment-483937352 via #308 I annotated my struct as follows:

```rust
#[derive(Debug, Template)]
#[template(path = "topic/node.html", escape = "none")]
pub struct TopicNode {
    pub topic: Topic,
    pub children: TopicTree,
}
```

With a template that looks like this:

```jinja
<li>{{ topic.name }}</li>
{% if !children.is_empty() %}
<li>
    <ul class="tree-list">
        {% for child in children %}
            {{ child.render().unwrap() }}
        {% endfor %}
    </ul>
</li>
{% endif %}
```

I noticed that the name in the first line was no longer being escaped... not unexpected given `escape = "none"` so I tried to manually escape by doing:

```jinja
<li>{{ topic.name|escape }}</li>
```

which still did not escape the text. It seems the `E` argument of the `escape` filter is filled in with the current escaper, which in this case in `none`. I was able to work around this by defining a custom filter as follows:

```rust
pub fn html_escape<T>(v: T) -> askama::Result<MarkupDisplay<Html, T>>
    where
        T: fmt::Display,
{
    Ok(MarkupDisplay::new_unsafe(v, Html))
}
```

Which, works as expected. Anyway, [the docs](https://djc.github.io/askama/filters.html#escape--e) suggest that HTML will always be escaped so I thought it was worth opening an issue. Thanks.

**Comment by djc** [comment]
Hmm, this is indeed tricky. I would argue that `|escape` should escape even when `escape = "none"`, but then it wouldn't know what escaper to use. Do you have any suggestions on how we could document this? It does seem like a potential footgun.

**Comment by vallentin** [comment]
Using the `escape` filter, is just an explicit way of using the configured escaper. Which in this case is `none`, and thus _no_ escaping occurs.

See:

> `escape` (as `escape = "none"`): override the template's extension used for the purpose of determining the escaper for this template. See the section on configuring custom escapers for more information.
>
> https://djc.github.io/askama/creating_templates.html



I think the easiest way to answer your question, is with another question. If you configured the escaper as `none`. Then what _other_ escaper should Askama use, when it encounters `{{ topic.name|escape }}`?

Ideally, Askama can be used to generate anything. So if the escaper is configured as `none`. Then it wouldn't make sense to escape HTML entities. What if we're generating LaTeX?

**Comment by djc** [comment]
@vallentin well, to be fair @wezm *was* arguing this was probably just a documentation change.

I suppose we could add an optional argument to `escape` that takes an escaper, so that either `foo|escape` or `foo|escape("html")` would work.

**Comment by wezm** [comment]
I think the idea of being able to supply an escaper to escape could be a good option. Alternately since it's so common perhaps there could be a html_escape filter built-in.

**Comment by vallentin** [comment]
> to be fair @wezm was arguing this was probably just a documentation change.

Of course, of course. I just wanted to point to the escaper docs in "Creating templates", which I thought explained it a bit more :)

> we could add an optional argument to `escape` that takes an escaper, so that either `foo|escape` or `foo|escape("html")` would work.

That's a good idea, it also looks like a relatively simple addition. If the optional arg is present, then in `visit_filter` use `self.input.config.escapers.iter().find(...)`

**Comment by djc** [comment]
Yup. Would you like to submit the PR?

**Comment by vallentin** [comment]
Sure, I'll do it in the evening when I have time :)
