### ISSUE TITLE
How to compare an enum in a template

### ISSUE THREAD

**Issue by drahnr** [djc/askama#56]
Currently askama throws errors when trying to compare an enum in an if clause (or it is non obvious how to write such an comparison).

**Comment by djc** [comment]
Hey, sorry you're having trouble! Can you give an example of what you're trying to do?

When you use the word "compare", I'm thinking of operators like `==` and `!=`, which I would expect to work just fine in templates if your enum has the appropriate trait implementations.

**Comment by drahnr** [comment]
```
#[Derive(PartialEq,Eq,PartialOrd,Ord,Debug)]
enum Alphabet {
Alpha,
Beta,
}

impl fmt::Display for Alphabet {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
```

where as in the template:

```
{% if x == Alphabet::Beta %}
{% endif %}
```

**Comment by djc** [comment]
Yup, I missed that case! Should be better now on master.
