### ISSUE TITLE
failed to resolve: could not find askama_axum in the list of imported crates

### ISSUE THREAD

**Issue by kinwolfqc** [djc/askama#569]
Hi, 
  I saw that the merge was made for axum 0.4, so I am trying the main branch of askama along with axum 0.4 and I keep getting this error on the #[derive(Template)] 
I looked at the example to make sure I was importing everything that should be, but I still get this error.

> failed to resolve: could not find askama_axum in the list of imported crates

Here is the import in Cargo.toml
```askama = { git = "https://github.com/djc/askama.git", branch = "main" , default-features = false, features = ["with-axum", "mime", "mime_guess"] }```

and I have the usual `use askama::Template;` in the code

Any clue on what is going on?

**Comment by djc** [comment]
You should use askama_axum from your crate. It re-exports items from asks a, so you should not need to depend on it directly.

**Comment by kinwolfqc** [comment]
Thanks for the precision.  Since the crate askama_axum isn't published yet, the only way I found to do that was to download the repo locally and add this to cargo.toml, as I couldn'T find a way to tell cargo to load a crate as a subfolder in the git repo

```
askama = { path = "../../askama/askama" , default-features = false, features = ["with-axum", "mime", "mime_guess"] }
askama_axum = { path = "../../askama/askama_axum" }

```

**Comment by djc** [comment]
Pretty sure you don't need the askama dependency?

**Comment by kinwolfqc** [comment]
If I don't add askama itself, I get a bunch of errors that the askama crate isn't found.  
`use askama::Template` won't work
Even if I  replace with
`use askama_axum::Template`; I still get errors related to the askama crate missing.
Like in this case where I use #derive(Template):
```
// use askama::Template;
use askama_axum::Template;

#[derive(Template)]
#[template(path = "list.html")]
struct ListTutors {
    tutors: Vec<Tutor>,
}
```
I will get 

> failed to resolve: could not find `askama` in the list of imported crates
> could not find `askama` in the list of imported crates

Quite possible that I am misunderstanding how to use the crate though.

**Comment by djc** [comment]
Okay, I guess I remembered wrong and you still need both dependencies.
