### ISSUE TITLE
How to prevent additional newlines for if/else cases

### ISSUE THREAD

**Issue by drahnr** [djc/askama#57]
Given that in templates there are situations where multiple if/else cases are stacked, the final generated file contains empty lines where the if statements reside.

```
{% if x %}
{% if z %}
hello
{% endif %}
virtual
{% else %}
world
{% endif %}
```

How can one prevent this?

**Comment by djc** [comment]
You can write `{%- if foo -%}` to suppress whitespace before and after the if-block. Does that address your problem?

**Comment by drahnr** [comment]
Yes! Thanks a lot!
