### ISSUE TITLE
Trying to crate a custom filter and getting a struct mismatch error

### ISSUE THREAD

**Issue by kinwolfqc** [djc/askama#589]
Hi, not sure what I want to do is the right way to do it, but here goes.  Basically, I pass a vector of  `course` structs to the template and one of the struct field is a UTC Datetime.  `pub course_datetime: DateTime<Utc>,`  When the template display the vector content(using a loop), I want it to display the Local time instead of the UTC time.  So, I tried to make a custom filter that would do the conversion.(I'm pretty sure I didn't understand correctly how to create and use a custom filter too...)
 
The struct: (The  `course_datetime` field is populated from a Datetime field in MongoDB)
```Rust
#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct CourseResponse {
    #[serde(rename = "_id")]
    pub course_id: ObjectId,
    pub tutor_id: ObjectId,
    pub course_name: String,
    pub course_description: String,
    pub course_format: String,
    pub course_structure: Option<String>,
    pub course_type_id: String,
    pub course_duration: String,
    pub course_price: Option<u32>,
    pub course_level: Option<String>,
    #[serde(with = "bson::serde_helpers::chrono_datetime_as_bson_datetime")]
    pub course_datetime: DateTime<Utc>,
    pub course_participant: Option<Vec<String>>,
}

```
The template struct  and filter definition
```Rust
#[derive(Template, Debug, Deserialize, Serialize)]
#[template(path = "view_courses.html")]
#[template(source = "{{ s|localtimefilter }}")]
pub struct ShowCourses {
    pub list_course_category: Vec<CourseCategory>,
    pub list_course_docs: Vec<CourseResponse>,
}

mod filters {
    use chrono::{DateTime, Local, Utc};
    pub fn localtimefilter(s: DateTime<Utc>) -> ::askama::Result<DateTime<Local>> {
        let time_local = s.with_timezone(&Local);
        Ok(time_local)
    }
}

```
The template.  The line in trouble is:  `<li>{{c.course_datetime|localtimefilter}}</li>`
```Jinja
{% extends "base_hero.html" %}
{% block content %}
<div class="page-header">
    <h1>Classes of past and present</h1>
</div>
<div class="row">
    <h2>Open classes:</h2>
    <select>
        {% for x in list_course_category %}
        <option value="{{x.category_name}}">{{x.category_name}}</option>
        {% endfor %}
    </select>
    {% for c in list_course_docs %}
    <li>{{c.course_name|e}}</li>
    <li>{{c.course_duration|e}}</li>
    <li>{{c.course_datetime|localtimefilter}}</li>
    {% endfor %}
</div>
{% endblock %}
```

The result of all that is an error

> error[E0308]: mismatched types
>   --> zata-web-app-ssr\src\.\models\template.rs:36:10
>    |
> 36 | #[derive(Template, Debug, Deserialize, Serialize)]
>    |          ^^^^^^^^ expected struct `chrono::DateTime`, found reference
>    |
>    = note: expected struct `chrono::DateTime<Utc>`
>            found reference `&chrono::DateTime<Utc>`
>    = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)

Am I using custom filters incorrectly?

**Comment by kinwolfqc** [comment]
Looking at various test case, I changed the template struct and filter definition to this, but I got the exact same error message.(And I admit to not understanding one bit why such a syntax must follow "source"

```Rust
#[derive(Template, Debug, Deserialize, Serialize)]
#[template(
    source = "{% for c in list_course_docs %}
    {{c.course_name|e}}
    {{c.course_duration|e}}
    {{c.course_datetime|localtimefilter}}
    {% endfor %}",
    ext = "txt"
)]
pub struct ShowCourses {
    pub list_course_category: Vec<CourseCategory>,
    pub list_course_docs: Vec<CourseResponse>,
}
```

**Comment by djc** [comment]
This error seems pretty clear:

```rust
error[E0308]: mismatched types
--> zata-web-app-ssr\src.\models\template.rs:36:10
|
36 | #[derive(Template, Debug, Deserialize, Serialize)]
| ^^^^^^^^ expected struct chrono::DateTime, found reference
|
= note: expected struct chrono::DateTime<Utc>
found reference &chrono::DateTime<Utc>
= note: this error originates in the derive macro Template (in Nightly builds, run with -Z macro-backtrace for more info)
```

Your filter should take `&DateTime<Utc>` rather than an owned value as an argument.

**Comment by kinwolfqc** [comment]
Wow, that was only that... It works.  You say the error message is pretty clear, but even with it working, I find the error message backward.   I thought the compiler was complaining it was receiving a reference, but expected a direct value. As I say, I had it completely backward.  :-/   It would have made more sense  if the error had been directly on the filter function instead.   I guess when using macro error messages gets  backyard a bit like that, I'll remember it for the future.

Btw, the filter works(still need to tweak it to get the right display output).  Being able to create fn that works as filter is very, VERY useful, thanks!   

It would be great to have good doc(eventually) on the whole Custom Filters syntax, like what to put after `source` .   In the meantime, I'll go look at the source to try to understand. :)

**Comment by djc** [comment]
> You say the error message is pretty clear, but even with it working, I find the error message backward. I thought the compiler was complaining it was receiving a reference, but expected a direct value. As I say, I had it completely backward. :-/ It would have made more sense if the error had been directly on the filter function instead. I guess when using macro, error messages gets backyard a bit like that, I'll remember it for the future.

This has nothing to do with this being a macro; you'd have gotten the exact same error message if you'd passed a `&DateTime<Utc>` directly to your filter function while it was accepting a `DateTime<Utc>`. In Rust, function signature are leading (`expected`) and the argument value (`found`) is expected to conform.

The whole `#[template(source = )]` thing is completely unnecessary here, it just provides an alternative way of specifying the template contents for when the template contents are small enough that having a separate file for them is overkill. That stuff has nothing to do with custom filters. The documentation for custom filters is [here](https://djc.github.io/askama/filters.html#custom-filters), feel free to point out missing information there so we can improve the docs on this.
