### ISSUE TITLE
Parents and child templates have to be in same file?

### ISSUE THREAD

**Issue by kardeiz** [djc/askama#61]
I'm new to using askama, so I apologize if this has been addressed or if I am missing something...

I had a child template set up with a parent template and everything was working as expected.

However, I moved that parent template into a new file (and `use`d the parent template in the file containing the child), and I am getting the error:

```
cannot find trait `TraitFromlayout2ehtml` in this scope
  --> src/web/handlers.rs:15:14
   |
15 |     #[derive(Template)]
   |              ^^^^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
   |
1  | use web::other::TraitFromlayout2ehtml;
```

The suggestion doesn't work since that trait is private.

It's not a big deal--I can move the parent template back into the same file. I just wanted to make sure I wasn't missing something, and if this is the case, it would be nice if it was documented somewhere (unless it already is and I missed it). 

This is with askama 0.5.0 on nightly-2017-11-27 Rust. Thanks!

**Comment by djc** [comment]
This note has been in the documentation for a while: "Note that, if the base template lives in another module than the child template, the child template's module should import all symbols from the base template's module in order for it to find the trait definition that supports the inheritance mechanism."

Does that not work for you? If it does, how do you think I can make it easier to find so that you'd have been able to find it yourselves?

**Comment by kardeiz** [comment]
Thanks, I confess that I missed that and I admit that that is a reasonable place for it.

However, it doesn't seem to fix the issue. Here is a minimal case (now with stable Rust and no other dependencies):

**lib.rs**

```rust
#[macro_use]
extern crate askama;

pub mod child {
    use askama::Template;
    use super::parent::*;
    #[derive(Template)]
    #[template(path = "root.html")]
    pub struct RootTemplate<'a> {
        _parent: Layout<'a>,
        name: &'a str
    }
}

pub mod parent {
    use askama::Template;
    #[derive(Template, Default)]
    #[template(path = "layout.html")]
    pub struct Layout<'a> {
        title: String,
        user: Option<String>,
        path: &'a str
    }
}
```

**layout.html**
```jinja
{% block content %}{% endblock content %}
```

**root.html**
```jinja
{% extends "layout.html" %}
{% block content %}
  Hello
{% endblock content %}
```

Compiling this gives me the same error as above. If I copy and paste the parent struct into the child mod (and remove the reference to the parent mod), everything compiles fine.

Thanks for your assistance and speed!

**Comment by djc** [comment]
Thank you for the nice test case, I will put that in the test suite and figure out what's going on. That will take me a bit longer before I reply again, though.

**Comment by djc** [comment]
That took a bit longer than I hoped, but this has been fixed. I adapted your test case and committed it in b076422 so I can make sure it won't break again. Thanks for reporting.

(I'll try to get a new release out soon that contains this and other fixes.)
