### ISSUE TITLE
error: cannot find derive macro `Template` in this scope

### ISSUE THREAD

**Issue by GildedHonour** [djc/askama#62]
```
# src/main.rs
extern crate askama;

#[macro_use]
use askama::Template;

#[derive(Template)]
#[template(path = "templates/index.html")]
struct IndexTemplate {
    name: String,
}

```
===>

`error: cannot find derive macro `Template` in this scope`

**Comment by djc** [comment]
The `macro_use` needs to be on the `extern crate` statement, not on the `use` statement.

**Comment by GildedHonour** [comment]
Thx
```

#[template(path = "hello.html")] // using the template in this path, relative
                                 // to the templates dir in the crate root
```
What's "crate root?"?

**Comment by djc** [comment]
The crate root is the directory containing `Cargo.toml`. Right now you have to put templates in a directory called `templates`.

**Comment by GildedHonour** [comment]
And if I don't call it "templates", it won't compile?

**Comment by djc** [comment]
That name is hard-coded. You could try using `..` in your template path to see if it works, but that's not tested (so it's not really a supported feature).

**Comment by djc** [comment]
Since this seems to work as intended, I'll close this. Let me know if you think there should be a way to put your templates in a different directory somehow. That would probably involve having a configuration file of some kind to specify where the templates live.

**Comment by GildedHonour** [comment]
What if I have subfolders in "templates"?

**Comment by djc** [comment]
That should work fine, just put slashes in your template paths.
