### ISSUE TITLE
Unable to build simple example with askama_actix using actix-web 4.0.0-rc2

### ISSUE THREAD

**Issue by hut8** [djc/askama#633]
I have this simple example of using Askama with Actix in a repo here: https://github.com/hut8/askama-actix-mcve

This is the error I get:

```
error[E0308]: mismatched types
  --> src/main.rs:10:5
   |
10 |     IndexTemplate {}.to_response()
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `HttpResponse`, found enum `Result`
   |
   = note: expected struct `HttpResponse`
                found enum `Result<actix_http::response::Response, actix_http::error::Error>`

error[E0308]: mismatched types
 --> src/main.rs:4:10
  |
4 | #[derive(Template)]
  |          ^^^^^^^^
  |          |
  |          expected struct `HttpResponse`, found enum `Result`
  |          expected `HttpResponse` because of return type
  |
  = note: expected struct `HttpResponse`
               found enum `Result<actix_http::response::Response, actix_http::error::Error>`
  = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
```

When I tried replacing the specified return type with `Result<actix_http::response::Response, actix_http::error::Error>`, I had to add the crate actix_http as a dependency (which means I'm probably on the wrong track), but it turns out that those types are internal anyway, so this didn't work.

I'm using these versions:
```
actix-web = "4.0.0-rc.2"
askama = { version = "0.11.0", features = ["with-actix-web", "mime", "mime_guess"] }
askama_actix = "0.12"
```

I don't think that this is the same as https://github.com/djc/askama/issues/629 , because the solution in that issue did not fix my problem. I originally tried actix-web 3.3.3 but had problems with that as well.

I can't think of a simpler example; I copied most of this from the test in the askama-actix crate, but the dependency listed in Cargo.toml at  `https://github.com/djc/askama/blob/main/askama_actix/Cargo.toml#L17` points to the parent directory (which makes sense) but maybe this has something to do with the error.

Unfortunately, I am very new to Rust, so if this is in fact a dumb mistake on my part, please forgive me.

**Comment by Kijewski** [comment]
The current Git head works, but the released version of askama_actix is synchronous to actix-web v3. We (most likely) won't release a new version of askama_actix to crates.io before the stable actix-web v4 is released. For now you can use

```toml
[dependencies]
actix-web = "4.0.0-rc.2"
askama = { git = "https://github.com/djc/askama", branch = "main" }
askama_actix = { git = "https://github.com/djc/askama", branch = "main" }
```

**Comment by hut8** [comment]
Thanks for such a quick response. That makes perfect sense, and it works.
