### ISSUE TITLE
Immutable self and `Iterator::next`

### ISSUE THREAD

**Issue by imbolc** [djc/askama#669]
How do you process iterator if you need it's values in different places, so you can't let it to be consumed by `for`? The issue is that `Iterator::next` needs `&mut self` and `render` is only have an immutable one. The only way I found is wrapping the iterator into an interior mutability primitive. Is there another methods dealing with this? Why don't render accept `&mut self` instead?

**Comment by vallentin** [comment]
What's the example of when this would be needed? The issue quickly becomes then, that calling `.render()` on the same template instance multiple times, is going to result in different results then. So I'd suggest instead to collect into a `Vec` and using the `Vec` within the template. Unless I'm missing the point? :)

**Comment by imbolc** [comment]
> What's the example of when this would be needed?

In my case in need little text blocks (let's consider them to be ads) added to different places on different pages. So amount of the blocks for each particular page would differ. And I'd like this amount be defined by a particular template `{{ blocks.next() }}`.

> I'd suggest instead to collect into a `Vec`

I don't care about an unnecessary allocation in this solution. The real issue is that we can't stick with a common syntax like `{{ blocks.next() }}`, as we have to keep the index somewhere then, which again would require mutability. So we would retreat to using explicit indexes like `{{ blocks[1] }}`. Which would make changing the page difficult and error prone, as we have to scan the template itself and all sub / outer templates to visually find the last used index.

**Comment by imbolc** [comment]
> calling `.render()` on the same template instance multiple times

Could I ask in turn, for an example when this would make sense?

**Comment by djc** [comment]
Your template context type can have a method that returns an iterator and you can for-loop over that.

**Comment by imbolc** [comment]
> Your template context type can have a method that returns an iterator and you can for-loop over that.

Right. But I don't need to `for-loop` it in a single place at once. If I do it twice, a new iterator would be created each time, but I need the previous iteration to continue. I believe it would mean mutability of template context one way or another.

**Comment by Kijewski** [comment]
```rs
#[derive(Template)]
struct MyStruct<'a> {
    iterator: &a SomeIterator,
}

fn do_render() -> String {
    let iterable = [1,2,3,4];
    let mut iterator = iterable.iter();
    let my_struct = MyStruct { iterator: &mut iterator };
    my_struct.to_string()
}
```

**Comment by imbolc** [comment]
@Kijewski yeah, but it won't compile with 
```
error[E0596]: cannot borrow `*self.iterator` as mutable, as it is behind a `&` reference
 --> src/bin/askama-iter.rs:3:10
  |
3 | #[derive(Template)]
  |          ^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

Here's the copy-pastable code to get the error:
```rust
use askama::Template;

#[derive(Template)]
#[template(
    source = "{{ iterator.next().unwrap() }} {{ iterator.next().unwrap() }}",
    ext = "txt",
    print = "code"
)]
struct MyStruct<'a, I: Iterator<Item = &'a usize>> {
    iterator: &'a mut I,
}

fn do_render() -> String {
    let iterable = [1, 2, 3, 4];
    let mut iterator = iterable.iter();
    let my_struct = MyStruct {
        iterator: &mut iterator,
    };
    my_struct.to_string()
}

fn main() {
    do_render();
}
```

**Comment by imbolc** [comment]
Accepting a mutable self could surprize people because as @vallentin mentioned someone may use the struct after rendering not expecting data to change. But what do you think on a consuming option something like `render_consume(self)`? It won't let people use the struct after rendering.

**Comment by Kijewski** [comment]
Ah, yeah, my fault.

I don't see why you can't simply store the `next()` element in the template instance instead of the iterator?

**Comment by imbolc** [comment]
> Ah, yeah, my fault.
> 
> I don't see why you can't simply store the `next()` element in the template instance instead of the iterator?

Because, as I describe here https://github.com/djc/askama/issues/669#issuecomment-1103717635 , I'd like define the amount of items I'm iterating through on the template level.

**Comment by Kijewski** [comment]
How about an ugly but mutable iterator wrapper?

```rs
pub struct MutIter<I>(std::cell::Cell<Option<I>>);

impl<I: Iterator> MutIter<I> {
    pub fn new(it: impl IntoIterator<IntoIter = I>) -> Self {
        Self(Some(it.into_iter()).into())
    }

    pub fn next(&self) -> Option<I::Item> {
        let mut it = self.0.take()?;
        let next = it.next()?;
        self.0.set(Some(it));
        Some(next)
    }
}

```

**Comment by imbolc** [comment]
Yeah, I'm using interior mutability now, through `Mutex` though, as I need for it to be `Send`. I started the issue as the complication of this surprises me :)

**Comment by djc** [comment]
I view `render()` taking `&self` as fundamental, I don't want to change that -- it wouldn't make sense for `Display` to take `&mut self` either. However, we could maybe allow local variables to remain mutable somehow, so that you could assign an iterator returned from a context type method to a variable and call `next()` on it.

**Comment by imbolc** [comment]
> allow local variables to remain mutable somehow

I've just checked and found that local variables created in the base template are available in it's blocks and includes, so my case would fit into this option. Thank you :pray:  I'm closing this then.

**Comment by djc** [comment]
Well, I think right now local variables are also always accessed through a `&` ref, so it might not actually work? But that is something that could plausibly be made to work.
