### ISSUE TITLE
Trim all but 1 whitespace jinja condition

### ISSUE THREAD

**Issue by GuillaumeGomez** [djc/askama#671]
@vallentin suggested [here](https://github.com/djc/askama/pull/664#pullrequestreview-945253861) that we could extend the "trim_all_whitespace" feature to be able to trim all whitespace characters but one.

So currently, we have:

```jinja
<div>    {%- if foo -%} blabla {%- endif -%} </div>
```

Which will remove all whitespace characters before and after (by using `-`) and we have:

```jinja
<div>    {%+ if foo +%} blabla {%+ endif +%} </div>
```

Which means that the whitespace should be saved (only useful when the "trim all whitespace" feature is enabled).

The idea would now to add a new character to strip all whitespace characters but one. I propose `~`:

```jinja
<div>    {%~ if foo %} blabla {% endif %} </div>
```

**Comment by djc** [comment]
I'm on board with all that, including the proposed operator.

**Comment by GuillaumeGomez** [comment]
Ok, then I'll make a PR soon. :)

**Comment by Kijewski** [comment]
I like that! For readability I'd like it best if a run of whitespaces becomes a single '\n' if it contains an '\n', or a space otherwise.

**Comment by GuillaumeGomez** [comment]
I'm fine with implementing it this way. Anyone else has an opinion maybe?

**Comment by djc** [comment]
Yeah, I think that approach makes sense.

**Comment by vallentin** [comment]
I'd love, if it is also configurable like #664. So you can configure it through the config file or part of the `#[template(...)]`. As minifying HTML is part of my rendering pipeline, so if it was possible to enable it globally, without needing to sprinkle `~` everywhere, then that would be lovely :)

**Comment by GuillaumeGomez** [comment]
Sure. What should we name the config parameter then?

**Comment by GuillaumeGomez** [comment]
Also, if both "trim_all" and "trim_all_but_one" are enabled, what should we do?

**Comment by vallentin** [comment]
Maybe instead of having them be individual. Maybe it might be possible to do `whitespace = "trim_all"` and `whitespace = "trim_all_but_one"`

**Comment by GuillaumeGomez** [comment]
Maybe @djc was right: I should have gone with a string argument for "trim_whitespace" so then we wouldn't have this problem.

**Comment by djc** [comment]
> Maybe @djc was right: I should have gone with a string argument for "trim_whitespace" so then we wouldn't have this problem.

Yup!

**Comment by GuillaumeGomez** [comment]
Ok, then I'll change the parameter as well. :)

**Comment by vallentin** [comment]
> Maybe @djc was right: I should have gone with a string argument for "trim_whitespace" so then we wouldn't have this problem.
> 
> @vallentin Ah we reached the same conclusion haha.

Well, there hasn't been a new release yet. So it's not to late to play with it :)

**Comment by djc** [comment]
I think the names should be `suppress`, `preserve`, and then maybe `minimize`?

**Comment by GuillaumeGomez** [comment]
I think a mix between @djc's and @vallentin's propositions would work better. What do you think of:

```
trim_whitespace = "all" | "all_but_one" | "preserve"
```

?

**Comment by djc** [comment]
I still dislike anything "trim" because that's not, conceptually, what it is. We're either suppressing the whitespace from the template or preserving it, and this option is somewhere in between. To my eyes, `all_but_one` seems pretty ugly, and it kind of begs the question about which one.

I do like the idea of just calling it `whitespace` by default, to keep things simple and concise.

**Comment by GuillaumeGomez** [comment]
That makes sense. Then let's go with `whitespace` and `suppress`|`preserve`|`minimize`.
