### ISSUE TITLE
Transient error when building in Windows: Invalid access to memory location (os error 998)

### ISSUE THREAD

**Issue by mispecto** [djc/askama#683]
There's transient error we're getting when building a project that uses askama v.0.11.1 in Windows:

```
EXEC : error : Invalid access to memory location. (os error 998) 
  --> C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\askama-0.11.1\src\lib.rs:139:9
 | pub use askama_derive::*;
 |         ^^^^^^^^^^^^^
EXEC : error : could not compile `askama` due to previous error
```

Any idea why does it happen?

**Comment by Kijewski** [comment]
Totally unrelated to your question: You seriously should not compile rust programs (or, that is, any programs) using an admin / root account. 

Try deleting the "target" folder inside the project root. You could possibly updated your cargo version in the meantime and the ABI has changed.

**Comment by djc** [comment]
I have no clue how this could happen. Maybe worth an issue in rust-lang/rust?

**Comment by spektom** [comment]
Thanks.
