### ISSUE TITLE
include always strips preceeding newlines

### ISSUE THREAD

**Issue by drahnr** [djc/askama#69]
The file `test.yml`
```
smth
```

is included by `main.yml`:
```yaml
x:

{% include "test.yml"}
```

ends up in

```
x: smth
```

where it should be

```
x:

smth
```

unless I am mistaken.

**Comment by djc** [comment]
Hey, thanks for the report with actionable test case!

Looks like I managed to mess up the whitespace handling on include blocks. c023c35 should fix it, let me know if it works for you!
