### ISSUE TITLE
feature: `{%+` is not recognized

### ISSUE THREAD

**Issue by drahnr** [djc/askama#70]
I was checking the jinja documentation regarding newline behaviour (related to #69, looking for a workaround)
http://jinja.pocoo.org/docs/2.10/templates/
and I tried to use `{%+ include %}` which was not recognized.

Is this something that is planned/not planned to be implemented?

**Comment by djc** [comment]
Thanks for the feedback!

Askama doesn't currently support environment-wide options like `lstrip_blocks` and `trim_blocks`, without which the feature of `{%+` doesn't make any sense.

I have a rough plan for supporting environment-wide options, but it's not on any priority list.

**Comment by drahnr** [comment]
Thanks for the quick turn around time!

Since #69 is fixed, this is more of a nice to have.

**Comment by djc** [comment]
I'm going to close this for now, since a lot of the supporting Jinja infrastructure is not implemented yet and changing the defaults here is not a high priority for me.
