### ISSUE TITLE
Printing a literal '{{' in the output

### ISSUE THREAD

**Issue by nipunn1313** [djc/askama#704]
I am struggling to determine how to convince askama to print a literal `{{`.

When I put `{{hello}}` in my template, it does a substitution
When I put `\{\{hello\}\}` in my template, it outputs `\{\{hello\}\}`
When I put `{{{{}}}}`, it does not compile.

These are the templating mechanisms I might expect to try based on how other templating languages work. How does it work with askama? I dug through the docs, but couldn't easily find the way to do this.

**Comment by Kijewski** [comment]
Either ``{{ "{{" }}`` to print the string "{{", or ``{ {#- -#} {`` to split up the token. The latter option with generate better code, but is not readable at all, IMHO. And the third option is not use `{{}}` as delimiters at all: [\#configuration](https://djc.github.io/askama/configuration.html). If you want to print multiple `{{` tokens in your template, then maybe the last option is the best.

**Comment by nipunn1313** [comment]
Cool. Thanks for the info!
