### ISSUE TITLE
Build fails when using Rocket integration but not sure I've done things right

### ISSUE THREAD

**Issue by ctsrc** [djc/askama#71]
The documentation is rather sparse in terms of how to integrate with Rocket and the file `testing/tests/rocket.rs` is not quite sufficient for me to understand exactly what I should do either, so it could be that the following build failure arises because I am doing something wrong here.

When I try to build my project, I get the following error:

```
error[E0106]: missing lifetime specifier
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/askama-0.5.0/src/lib.rs:310:55
    |
310 |     pub fn respond(t: &super::Template, ext: &str) -> Result {
    |                                                       ^^^^^^ expected lifetime parameter
    |
    = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `t` or `ext`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
error: Could not compile `askama`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Here is my `Cargo.toml`, my `build.rs` and my `src/main.rs`: https://gist.github.com/ctsrc/dc2645843c8ca4a00697275a6c94a256

I am using Rust 1.27.0 nightly.

**Comment by djc** [comment]
Hey, sorry about that, I know how frustrating thia stuff can be. 

Are you using the released version by any chance? I really need to get out a new version; in the meantime, please see if master works for you.

**Comment by ctsrc** [comment]
Thank you, it works with git master. Closing issue :)
