### ISSUE TITLE
how to handle Option<String>

### ISSUE THREAD

**Issue by sysmat** [djc/askama#730]
- is there any syntax support for check **if present** and unwrap it?

**Comment by sysmat** [comment]
```
{% if host.alias.is_some() %}
    ServerAlias {{ host.alias.unwrap() }}
{% endif %}
```

- I got error

**Comment by djc** [comment]
You didn't mention the exact error, presumably it's about not being able to take an owned value out of a reference? In that case, you can probably use `host.alias.as_ref().unwrap()` instead.

There is some syntax support, but it is comparably heavyweight:

```
{% match host.alias %}
    {% when Some as (alias) %}
        ServerAlias {{ alias }}
{% endmatch %}
```

**Comment by sysmat** [comment]
- askama = "0.11.1"
- code
```
{% match host.alias %}
    {% when Some as (alias) %}
        ServerAlias {{ alias }}
{% endmatch %}
```
- produce error: 
```
problems parsing template source at row 16, column 21 near:
       "as (alias) %}\r\n            ServerAlias {"...
  --> src\main.rs:13:10

```

**Comment by djc** [comment]
Sorry, I misremembered the keyword. Have you looked at the documentation yet?

https://djc.github.io/askama/template_syntax.html#match

**Comment by sysmat** [comment]
@djc it works, thx. Yes I search doc, but my reading was superficial

**Comment by sysmat** [comment]
my bad using with **-** is to do it; `{%- when Some as (alias) -%}`
