### ISSUE TITLE
Yesno filter for booleans

### ISSUE THREAD

**Issue by kpietraszko** [djc/askama#731]
Sorry if I missed an equivalent.
I'd like to see a filter like this one in Django:
https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#yesno
Using regular `if` is far too verbose for stuff like conditional class names etc.
I realize this probably is quite easy to implement myself as a custom filter, but I feel this should come out of the box.

**Comment by djc** [comment]
I guess you could write `foo.then_some("yes").unwrap_or("no")` already?

I agree that `if` is pretty verbose for this use case, but `yesno` doesn't feel very Rusty.

**Comment by kpietraszko** [comment]
Thanks, your example is good enough.
