### ISSUE TITLE
Skip required Args  with `exclusive(true)`  

### ISSUE THREAD

**Issue by Clement-Jean** [djc/askama#741]
I'm trying to have a set of options and an argument that is required. Within this options `-a` should be exclusive, meaning that all the other options cannot be used. But I still want the required argument. Here is what I have:

```rust
Command::new("cli")
        .arg_required_else_help(true)
        .arg(Arg::new(WITH_ALL_KEY)
            //.exclusive(true) // this would be nice if it skips required args
            .num_args(0)
            .short('a'))
        .arg(Arg::new(WITH_DB_KEY) // should be omitted if a is set
            .num_args(0)
            .short('d'))
        .arg(Arg::new(WITH_UI_KEY) // should be omitted if a is set
            .num_args(0)
            .short('u'))
        .arg(Arg::new(DIRECTORY_KEY) // should never be omitted
            .required(true))
```

am I doing it wrong or is there no way to skip required args ?

**Comment by djc** [comment]
Did you file this against the wrong project? This looks like a clap issue, not an Askama issue.

**Comment by Clement-Jean** [comment]
oh sorry, I actually did 😶 my bad !
