### ISSUE TITLE
[Feature request] Turbo-fish syntax in custom filters

### ISSUE THREAD

**Issue by saona-raimundo** [djc/askama#743]
I have a custom filter that is naturally parametrized by a `usize` and I was hoping to implement it in a turbo-fish manner with a `const` parameter.

My custom filter indents the string by prefixing a string, a number of times, to each line. The code is the following.
```rust
    pub fn indent_by<const N: usize>(s: &str) -> ::askama::Result<String> {
    	let mut replace = "\n".to_string();
    	replace.extend(["    "; N]);
        Ok(s.replace("\n", &replace))
    }
```

I would like to call this filter by writing the filter `indent_by::<2>` in the Askama template (which is a stateless function). 

## Use-case

I am translating the Rule-Based approach for transformations in XLST to Rust. The idea is to code a function that takes an (XML) input and outputs another text format. Sometimes, this can be done by <em>delegating</em> the processing to the children. In light of #575, I implemented it as you suggested: having fields that are templates themselves. the result makes a lot of sense from the Rule-Based approach. 

By using `{{ child_template.render()?|safe }}`, I can locate the children result in a template, but to have full control of the output, I need to indent it like this `{{ child_template.render()?|indent_by::<X>|safe }}`.

I could indent as a post-processing, but I lose a lot of control over the output.

### Example

Note: I tried to come up with a minimal example, so I had to strip a few things. 
We want to display a poem, written in XML, in HTML. The input is
```xml
<poem>
   <author>Rupert Brooke</author>
   <title>Song</title>
</poem>
```
The desired output is
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        Song
    </title>
</head>
<body>
    <article>
        <h1>
            Song
        </h1>
        <address>
            Rupert Brooke
        </address>
    </article>
</body>
</html>
```

My approach is to have 3 templates: `File`, `Title`, and `Author`, where  `File` delegates to the others to achieve a Rule-Based approach. These are the templates.
```
{# file.html.askama -#}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {{ title.render()?|indent_by::<2>|safe }} {#- delegation #}
    </title>
</head>
<body>
    <article>
        <h1 class="display">
            {{ title.render()?|indent_by::<3>|safe }} {#- delegation #}
        </h1>
        {{ author.render()?|indent_by::<2>|safe }} {#- delegation #}
    </article>
</body>
</html>
```

```
{# title.html.askama -#}

{{ text }}
```

```
{# author.html.askama -#}

<address class="display">
    {{ text }}
</address>
```

In the Rust side, I would have the following code.
```rust
#[derive(Template)]
#[template(path = "file.html.askama", ext = "html", escape = "html")]
struct File<'a> {
    title: Title<'a>,
    author: Author<'a>,
}
#[derive(Template)]
#[template(path = "title.html.askama", ext = "html", escape = "html")]
struct Title<'a> {
    text: &'a str,
}
#[derive(Template)]
#[template(path = "author.html.askama", ext = "html", escape = "html")]
struct Author<'a> {
    text: &'a str,
}
```

**Comment by djc** [comment]
I think this would add too much complexity in the template language. But you can just pass the value as an additional argument, right?

```rust
    pub fn indent_by(s: &str, n: usize) -> ::askama::Result<String> {
        let mut replace = String::with_capacity(1 + n * 4);
        replace.push('\n');
    	replace.extend(0..n.iter().map("    "));
        Ok(s.replace("\n", &replace))
    }
```

**Comment by saona-raimundo** [comment]
Okay! Thanks for the answer :) 

Yes! your solution totally works, sorry for not seeing it before. Also, there is already a [`indent` built-in filter](https://djc.github.io/askama/filters.html#indent).

Would you consider expanding the [`Custom filters` section of the book](https://djc.github.io/askama/filters.html#custom-filters) to indicate that filters can take extra arguments after the `&str`? (I can do a first draft if you want)

**Comment by djc** [comment]
Of course, a PR would be great!
