### ISSUE TITLE
Support `.await` usage in Templates

### ISSUE THREAD

**Issue by hwittenborn** [djc/askama#746]
Going straight into my code, I have a template that's utilizing an async function like shown below:

```rust
{% set pkgname_of_pkgbase = pkg.find_related(Packages).one(mpr.db).await %}
```

However, attempting to compile this code shows the following error:

```rust
error[E0609]: no field `r#await` on type `impl std::future::Future<Output = Result<std::option::Option<<packages::Entity as sea_orm::EntityTrait>::Model>, sea_orm::DbErr>>`
 --> src/routes/misc.rs:6:10
  |
6 | #[derive(Template)]
  |          ^^^^^^^^ field not found in `impl std::future::Future<Output = Result<std::option::Option<<packages::Entity as sea_orm::EntityTrait>::Model>, sea_orm::DbErr>>`
  |
  = note: to `.await` a `Future`, switch to Rust 2018 or later
  = help: set `edition = "2021"` in `Cargo.toml`
  = note: for more on editions, read https://doc.rust-lang.org/edition-guide
  = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Checking my `Cargo.toml` file though, my edition is set to `2021`. Is there any reason the template isn't recognizing that? And I'm assuming it'd be fixed by that issue, but if not now can I get `.async` to be working in my templates?

**Comment by djc** [comment]
Ohh, interesting issue! As far as I'm aware macro-generated code implicitly inherits the edition of the crate in which the macro lives... but assuming you're using askama 0.11 (in particular, askama_derive 0.11.2) then that seems to be 2018 edition already, so, I'm honestly not sure what's going on with that. Can you make a minimal reproduction?

**Comment by hwittenborn** [comment]
> Can you make a minimal reproduction?

Yeah, this seems to reproduce it:
```rust
use askama::Template;

fn main() {}
async fn testing() {}

#[derive(Template)]
#[template(source = "{% set variable = crate::testing().await %}", ext = "html")]
struct AskamaTemplate {}
```

**Comment by Kijewski** [comment]
`await` is in [the list](https://github.com/djc/askama/blob/c441459a27eb7c0c476ce70833e05224ba6894fd/askama_derive/src/generator.rs#L2112) of identifiers that get automatically escaped, i.e. prefixed with `r#`. You could not use `.await` anyway, because the generated [`render_into`](https://github.com/djc/askama/blob/c441459a27eb7c0c476ce70833e05224ba6894fd/askama_derive/src/generator.rs#L2112) is not async.

I think the line you wrote should be moved outside of the template syntax, and the outcome become a field.

**Comment by hwittenborn** [comment]
> You could not use .await anyway, because the generated [render_into](https://github.com/djc/askama/blob/c441459a27eb7c0c476ce70833e05224ba6894fd/askama_derive/src/generator.rs#L2112) is not async.

Maybe there could be a `render_async` function or something like that then? Or maybe the `derive(Template)` stuff could just detect if any async code was being ran and make it derive an `AsyncTemplate` instead. I don't know too much how `Derive` works but I feel like it could maybe be done.

> I think the line you wrote should be moved outside of the template syntax, and the outcome become a field.

That's what I'm doing right now, but it feels kind of clunky doing that with my code.

**Comment by djc** [comment]
Yeah, I don't think `render_async()` setup makes sense. Template formatting is inherently synchronous and I feel comfortable setting it up as such. There's probably ways to make your code less clunky.
