### ISSUE TITLE
Question: white-space suppression for blocks only

### ISSUE THREAD

**Issue by ta32** [djc/askama#755]
The template
```
<test>{{"\n"}}
  {%- if prop1 -%}
{{"  "}}prop1{{"\n"}}
  {%- endif -%}
  {%- if prop2 -%}
{{"  "}}prop2{{"\n"}}
  {%- endif -%}
</test>
```
results in ( windows ) 
![image](https://user-images.githubusercontent.com/26617779/208345922-198dc373-198d-44c1-a2ed-65361f430e5b.png)

The white space control removes the whitespace characters until it reaches a non-ws character. It would be easier to create 'in-place' templates if there was an option where it only removes only the whitespace characters on line the statement is defined.

eg _"%- if prop1..."_ removes the 2 white spaces on the current line (ok) but wouldn't remove the newline after <test>
If there was such an option we could write templates like
```
<test>
  {% if prop1 %}
  prop1
  {% endif %}
  {% if prop2 %}
  prop2
  {% endif %}
</test>
```

I also tried playing with the ~% in the docs - but I get a compiler error 
"There is a third possibility: in case you want to suppress all whitespace characters except one, you can use ~:"

I get the impression this library is meant to have a similar interface to jinga templates. So I looked in their docs

With both trim_blocks and lstrip_blocks enabled, you can put block tags on their own lines, and the entire block line will be removed when rendered, preserving the whitespace of the contents. For example, without the trim_blocks and lstrip_blocks options, this template:

https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control

If you wanted to introduce this feature, would it be done via a configuration option
https://djc.github.io/askama/configuration.html?highlight=trim#configuration
or an extra ws control character, or both.

I think what I did is probably the best work around?

**Comment by ta32** [comment]
https://github.com/djc/askama/issues/70

Sorry didn't search closed issues. 

Seems like there is a lot of work in supporting such a feature

**Comment by djc** [comment]
Assuming you tested a released version, a bunch of extra stuff is implemented on the main branch (including, I think, `+`) and global whitespace suppression configurable via `askama.toml`.
