### ISSUE TITLE
Make `askama_shared::parser` module public

### ISSUE THREAD

**Issue by GuillaumeGomez** [djc/askama#760]
Is there any reason for this module to be private? Making it public would allow to have access to the parser directly.

**Comment by djc** [comment]
What branch are you looking at? What's your use case? See discussion in #748 and the changes from #687.

**Comment by GuillaumeGomez** [comment]
I was looking at the docs from the last published version. My use case is to be able to write my own proc-macro with `askama` parser (different needs and eventually smaller).

**Comment by djc** [comment]
What different needs? Smaller in what dimension?

**Comment by GuillaumeGomez** [comment]
Different needs in the storage (compile-time generated hashmap which updates templates in case they're updated) and smaller in term of deps and code (`syn` is very big).

**Comment by djc** [comment]
Would you be interested in contributing your synless derive code here? I would be open to entertaining it (though I would like to understand this plan in more detail).

As for the compile-time stuff, I've been contemplating an API that lets you run codegen asynchronously (for example, I have a bunch of code that regenerates only in an integration test so it fails in CI if the generated code is out of date). If this would address your issues, we could work on it in this repo.

**Comment by djc** [comment]
Further thoughts: is this driven by rustdoc needs? Is there a discussion in Zulip or in another repo somewhere that I could look at about the concerns?

**Comment by GuillaumeGomez** [comment]
> Would you be interested in contributing your synless derive code here? I would be open to entertaining it (though I would like to understand this plan in more detail).

Sure. The plan is basically to be able to get rid of the proc-macros by settting up the parser "by hand" (and of course, if possible at compile-time).

And it's not a rustdoc need but a personal one. So no discussion that can be seen anywhere.

**Comment by djc** [comment]
Sounds like a good plan, want to submit a PR with what you've got so far?

**Comment by GuillaumeGomez** [comment]
Need to clean up things a bit. A bit under water currently but I'll try to send a PR as soon as possible.

**Comment by djc** [comment]
No hurry!

**Comment by djc** [comment]
#834 extracts a parser crate.
