### ISSUE TITLE
Whitespace suppression ignored at start of template

### ISSUE THREAD

**Issue by couchand** [djc/askama#785]
While going deep into a rabbit hole of AST refactoring, I noticed a few test cases that, on their face, do not seem right:

This case uses the global setting `Minimize`:
https://github.com/djc/askama/blob/417cb924ae1f94d54e2eb13ebc7e9fab91b84588/testing/tests/whitespace.rs#L79

These cases use the global setting `Suppress`:
https://github.com/djc/askama/blob/417cb924ae1f94d54e2eb13ebc7e9fab91b84588/testing/tests/ws.rs#L178-L208

I would expect the leading space to be removed from the first case, and all the leading whitespace to be removed from the latter cases.  I could not find any documentation that describes this behavior.  Can anyone point me to a reason to believe this is expected?

**Comment by couchand** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Let me try to explain how I see the feature is supposed to worked: the feature removes whitespace characters **around** the `{% %}` and other "jinja controllers". The start and end of the template file are not jinja controllers and thus do not enter the "auto whitespace character removal". If you want them to be taken into account, you can always add `{# #}` as first and last elements of your template file.

**Comment by couchand** [comment]
I think I was thrown off by the whitespace being trimmed at the end of these test cases, and assumed that meant it was trimming due to configuration.  Digging deeper, I see that all whitespace at the end is unconditionally removed.  This despite the documentation stating:

> By default, it preserves all whitespace in template code, except that a single trailing newline character is suppressed. 

The following test passes (which surprises me):

```rust
macro_rules! test_template {
    ($source:literal, $rendered:expr) => {{
        #[derive(Template)]
        #[template(source = $source, ext = "txt")]
        struct CondWs;

        assert_eq!(CondWs.render().unwrap(), $rendered);
    }};
 }

macro_rules! test_template_config {
    ($config:literal, $source:literal, $rendered: literal) => {{
        #[derive(Template)]
        #[template(source = $source, ext = "txt", config = $config)]
        struct CondWs;

        assert_eq!(CondWs.render().unwrap(), $rendered);
    }};
}

#[test]
fn test_outer_whitespace() {
    test_template_config!("test_trim.toml", "\t1\t", "\t1");
    test_template_config!("test_trim.toml", " 1 ", " 1");
    test_template_config!("test_trim.toml", "\n1\n\n\n", "\n1");
    test_template_config!("test_minimize.toml", "\t1\t", "\t1");
    test_template_config!("test_minimize.toml", " 1 ", " 1");
    test_template_config!("test_minimize.toml", "\n1\n\n\n", "\n1");
    test_template!("\t1\t", "\t1");
    test_template!(" 1 ", " 1");
    test_template!("\n1\n\n\n", "\n1");
}
```

It seems to me that either the left side or the right side of the test cases has a bug.

If your description is the expected behavior, then the space should remain at the end of the first test case and two newlines should remain at the end of the latter cases (and possibly an extra carriage return?  I'm not sure what should happen with that...)

To me it seems more natural to consider the configured whitespace setting to apply to the outside of the template.  Effectively I want to treat the outside of the whole template the same as the inside of a match, loop, or conditional block.  If nothing is specified (and it can't be here because there's no "outside" tag), the configured default behavior should apply.

In any case it seems the handling should be symmetric.

**Comment by couchand** [comment]
Fair enough.  I'm deep enough in my other PR that I won't get to it for a bit, so please go ahead, thanks!

**Comment by GuillaumeGomez** [comment]
Opened #789.
