### ISSUE TITLE
Loop over (&EXPR).into_iter()

### ISSUE THREAD

**Issue by dtolnay** [djc/askama#8]
```diff
- for x in &self.y {
+ for x in (&self.y).into_iter() {
```

I think this fixes both #6 and #7.

**Comment by djc** [comment]
Woo, very nice! I had tried some things to figure out to get the inferencing to accept more stuff, but that was kind of a minefield.

**Comment by dtolnay** [comment]
Please add tests for #6 and #7.

**Comment by djc** [comment]
Kept them open for a reason. :)
