### ISSUE TITLE
Docs don't distinguish between {% %} and {% -%}

### ISSUE THREAD

**Issue by kevinw** [djc/askama#80]
It's unclear to me from the documentation what the difference between

```
{% foo %}
```

and

```
{% foo -%}
```

are.

**Comment by djc** [comment]
It is described, in prose, in the section "Whitespace control". I guess that's not very clear, and there's also no example. I'll try to improve what's there. Any suggestions for the kind of questions that you would like to see answered?

**Comment by kevinw** [comment]
Ah, I see. Thanks. One improvement might be an example showing the behavior with and without a minus sign, yeah.
