### ISSUE TITLE
Use actual name of imported crate in generated code

### ISSUE THREAD

**Issue by Kijewski** [djc/askama#803]
Using [`proc-macro-crate`](https://crates.io/crates/proc-macro-crate) (or extracting its logic) it would be possible to emit e.g. `::askama_axum::…` instead of `::askama::…` if the user only used the integration crate instead of the parent one. Also, if the user renames the import like `[dependencies] my_askama = { package = "askama" }`, we could still generate working code.

The major drawback is that `proc-macro-crate` uses [`toml_edit`](https://crates.io/crates/toml_edit) which has a ton of dependencies. And actually in <https://github.com/djc/askama/pull/780> we deliberately went away from using `toml_edit` for this exact reason.  `proc-macro-crate` is only ~200 lines and liberally licensed as `MIT OR Apache-2.0` like askama, so I guess we could simply extract or reproduce its logic using [`basic-toml`](https://crates.io/crates/basic-toml). Is this case we would have to depend on [`serde`](https://crates.io/crates/serde), but chances are that any user of askama uses serde as well in their project.

We already depend on `basic-toml` & `serde` if the feature `"config"` is enabled.

**Comment by djc** [comment]
Hmm, I'm not convinced that's worth the added complexity.

**Comment by Kijewski** [comment]
Yeah, you're right. Users probably would even expect renamed dependencies to work.
