### ISSUE TITLE
Forced template root dir

### ISSUE THREAD

**Issue by trsh** [djc/askama#81]
> The path is interpreted as relative to the templates dir in the directory where the originating crate's Cargo.toml resides. 

Why? This forces me a 1 way structure, that works bad with my project tree. Please add an option to change the root dir, or better to add multiple ones.

**Comment by djc** [comment]
I built it this way because it's simple and fairly easy to use.

Can you explain more about how your project tree is laid out, and how you would like Askama to work in your context?

**Comment by trsh** [comment]
I use actix FW and have multiple apps attached to server. Each app with it's underlying logic lives in separate Directory, where I also would like to add the templates.

Nerveless I can't really come up with an Idea how to organise this. One thing that comes to my mind, is that I have a choice to load the templates relative to dir where ```#[template(path = ".../templates/layout.html")]``` lives.

**Comment by trsh** [comment]
However this is not a _blocker_ for me, #82 is :/

**Comment by mashedcode** [comment]
@djc Thank you for your work. I really like askama.
> Can you explain more about how your project tree is laid out, and how you would like Askama to work in your context?

There're a lot of reasons why someone might want to put templates in a different directory.

Example:
One might want have a bunch of encapsulated modules that each consist of one template.
A project tree like that might be laid out like this: 
```
modules
| Cargo.toml
| lib.rs
| foo
| | layout.html (askama template)
| | mod.rs (Makes use of this crate to load askama template)
| | * Some more module related files.
| bar
| | layout.html
| | mod.rs
```

The current work around requires one to have an empty `templates/` directory and specify a relative template path as already mentioned by @trsh which is not ideal.

One backwards compatible approach to solve this would be to configure the default behavior by switches in `Cargo.toml`. As a bonus these switches may also be available as paramaters to when using `#[template(`.

For example:
```
[askama]
# Whether the path should be relative to the rust source file. (default: false)
relative = true
# Path to template directory which is relative to cargo manifest root. (default: "templates") 
path = ""
```

One may also want to treat paths in `#[template(path` which start with a leading slash as actual absolute paths.

**Comment by mashedcode** [comment]
@djc I'll be happy to implement whatever approach you think is best. The above is only my idea. You might have a better one.

**Comment by djc** [comment]
Here's the design I had in mind: there will be an optional `askama.toml` in the crate root (so, next `Cargo.toml`). It will contain any Askama configuration, all of which will be optional. The first option is like this:

```toml
[general]
dirs = ["templates", "foo/templates", "../bar/baz/templates"]
```

These are all paths relative to the crate root, and they are searched in order by `get_template_source()`.

Does that sound good?

**Comment by mashedcode** [comment]
Sounds good.

**Comment by djc** [comment]
Since I had a question about this on Gitter: I looked at what it could take to do template paths relative to the file defining the context struct. Unfortunately procedural macros right now don't give me a reliable way to figure out the path to the source code, as far as I can tell. Once they do, I definitely wouldn't mind revisiting that as an option, but the paths would have to be marked in some way (either with a path prefix like `./` or with a different attribute name like `rel`).

**Comment by djc** [comment]
@mashedcode so are you still interested in working on the design as proposed?

**Comment by djc** [comment]
Nice, I'm happy to provide further guidance/mentoring if needed; let me know.

**Comment by trsh** [comment]
Me too.

**Comment by denysvitali** [comment]
I also noticed that it isn't possible to add subdirs to the `templates` folder. For instance, the following attribute will result in a compilation fail:

```
#[derive(Template)]
#[template(path = "correspondents/add.html")]
```

with the following error:
```
  Compiling dmsrs v0.1.0 (file:///home/dvitali/Documents/rust/dmsrs)
error: proc-macro derive panicked
  --> src/routes/correspondents.rs:24:10
   |
24 | #[derive(Template)]
   |          ^^^^^^^^
   |
   = help: message: no entry found for key

error: aborting due to previous error

error: Could not compile `dmsrs`.
```

**Comment by denysvitali** [comment]
@djc Sure thing! I'll try create a minimal reproducible test, make a new issue and a PR to fix the problem / add a test (or both :smile:)

**Comment by HosMercury** [comment]
I think templates should be inside src because it contains rust code

**Comment by djc** [comment]
We recently merged a change so that paths that start with ./ do the right thing.

**Comment by BuriKizilkaya** [comment]
Can you show me a example, which I can start with `./`? 

The idea is that I can use vertical slice architecture. I would like to have the corresponding route-handler, html-template, etc. in the "home" directory. 

Can I also define wildcards?
