### ISSUE TITLE
Can I just {{ foo }} a template?

### ISSUE THREAD

**Issue by ro-kue** [djc/askama#816]
Hi!

I'd like to simply "print" a form template. I have a form struct that implements a form trait and that returns a FormTemplate and I put that into my page template as a normal field as described in the "render in place" example and in my actual html template file I would like to simply do {{ form }} and the form is rendered.

This is similar to how (I think. It's been a while) Django or WTForms render forms in templates.

The issue is that this just renders the HTML as text instead of actually putting the html on the page. Can I even do that with Askama or am I looking at a dead end here and I can't do it like that and need to include the template for the form and fields? I know that this is possible but I'd like to have all attributes scoped on the form / field template and I don't think I can pass variables to a template I include either, right?

**Comment by vallentin** [comment]
Askama implicitly escapes text, when you do `{{ form }}`. If you want to suppress that, then use `{{ form|safe }}`.

However, it sounds like there's more to the question than just that. If so, can you maybe provide some dummy code, to illustrate what you're trying to do?

To give a more complete example. What it sounds like to me, is that you're trying to do something like this:

```rust
use askama::Template;

#[derive(Template)]
#[template(source = "<form>Some Form</form>", ext = "html")]
pub struct Form {}

#[derive(Template)]
#[template(source = ""Form:\n<br>\n{{ form|safe }}", ext = "html")]
struct Page {
    form: Form,
}

let page = Page { form: Form {} };

println!("{}", page.render().unwrap());
```

Note the `|safe` in `Page`'s source. That suppresses escaping the HTML entities. So `page.render()` results in:

```html
Form:
<br>
<form>Some Form</form>
```

**Comment by djc** [comment]
Theoretically in this case the `safe` should not be necessary since the inner value is itself a template which means it is inherently safe. Unfortunately this is blocked by a lack of support for specialization.

**Comment by ro-kue** [comment]
That's exactly what I wanted and works perfectly. Thank you very much!
