### ISSUE TITLE
Nested templates won't work

### ISSUE THREAD

**Issue by trsh** [djc/askama#82]
```
let tmpl = DefaultTemplate { name: "world" };
  let tmpl_body = tmpl.render().unwrap();
  
  let layout = DefaultLayout { content: &tmpl_body };
  let layout_body = layout.render().unwrap();
  
  Ok(HttpResponse::Ok().content_type("text/html").body(layout_body))
```
`tmpl_body` is rendered as an String to HTML body. Is there a away around this?

**Comment by djc** [comment]
Can you provide a minimal example (including the templates), and explain your expected outcome vs the actual outcome?

**Comment by trsh** [comment]
clone https://github.com/trsh/examples
cd into template_askama
cargo build & cargo run

I expect the tmpl_body to appear in Layout as an HTML, not plain text.

The mine idea behind this, is that I don't want to Repeat stuff, that is General for all templates, like <html><body>. That's a lot of copy+paste and can even lead to huge problems in larger scale project. That's why introducing layouts logic.

**Comment by trsh** [comment]
Somehave I missed https://docs.rs/askama/0.6.3/askama/#template-inheritance :(( sorry

**Comment by djc** [comment]
Here's how you can fix this:

```diff
--- a/template_askama/templates/layout.html
+++ b/template_askama/templates/layout.html
@@ -5,6 +5,6 @@
   <title>Actix web</title>
 </head>
 <body>
-  {{content}}
+  {{content|safe}}
 </body>
 </html>
\ No newline at end of file
```

That is, the including template does not know whether the included template is safe to display without escaping. By simply marking it as safe with the `safe` filter, it will do what you expect.

And yes, I was going to say next that template inheritance is probably a better solution for what you're trying to do here.
