### ISSUE TITLE
Split `askama_derive` internals out into normal lib crate

### ISSUE THREAD

**Issue by wrapperup** [djc/askama#835]
Following #828 and #826.

It would be nice to have the bulk of `askama_derive` moved into a normal lib crate. (ie. `askama_derive_impl` that uses `proc_macro2::TokenStream`). This would make it easier to profile and benchmark the derive macros, since it would let us use the implementation inside of a binary. Could also let you track performance regressions as part of the CI.

**Comment by djc** [comment]
We used to have this, but @Kijewski didn't like it. 😜 If we flip flop on this we should make sure not to introduce the same problems as before (I believe the previous merge mainly addressed issues with the integration switches).

See also #835, which I think has a bit stronger motivation?

**Comment by wrapperup** [comment]
Resolved with #834
