### ISSUE TITLE
Parse error when using macro with expanded module path

### ISSUE THREAD

**Issue by wrapperup** [djc/askama#836]
I am making a crate that allows people to embed icons from Iconify at compile time, but I ran into a little snag.
Tried on main and 0.12. Only happens when using a macro, normal functions work fine.

The intended usage is:
```jsx
<body>
    <h1>Hello</h1>
    {{ iconify::svg!("mdi:home")|safe }}
</body>
```

But it gives me a parse error:
```
error: problems parsing template source at row 5, column 19 near:
       "!(\"mdi:home\") }}\r\n</body>\r\n</html>\r"
```

I can work around it by importing the macro (below compiles fine), but I'd prefer being able to keep the module path so I don't need to.
```jsx
{{ svg!("mdi:home")|safe }}
```

**Comment by djc** [comment]
Huh, I guess there's some subtlety in the parser relating to the combination of a path, the macro call and the filter. Care to submit a PR?

**Comment by wrapperup** [comment]
Sure, I'll take a jab at it.

**Comment by Kijewski** [comment]
Macro invocations are parsed specially, but they should actually be simply suffix expressions, and be handled like normal function calls:

https://github.com/djc/askama/blob/c9613ff6029ee58dc3f94c3dd955b905ed7fc9ef/askama_derive/src/parser/expr.rs#L256-L270
