### ISSUE TITLE
Rationale behind blocks only at top level

### ISSUE THREAD

**Issue by jkcclemens** [djc/askama#85]
Hello! I recently discovered askama, and I'm very excited about moving to it over Tera. I don't fully understand everything right now, but in trying to migrate, I discovered a confusing error.

I read that blocks can't be in loops, and that makes sense. However, I'm slightly confused as to why my templates, which include no blocks in loops, etc. aren't compiling. I get `blocks ('header') are only allowed at the top level`.

```j2
{% extends "frame.html.j2" %}

{% block head %}
...
{% endblock head %}

{% block body %}
...
{% block header %}
...
{% endblock header %}
...
{% block main %}{% endblock main %}
...
{% endblock body %}
```

`header` is inside of `body`, but I really don't understand why this isn't allowed. In fact, it's extremely useful to be able to provide bits inside of larger blocks that can be overwritten.

In addition, blocks lack the ability to do something similar to `{{ super() }}` from Tera, which lets you include the block's content instead of overwriting it, which is *extremely* useful. (Unless you can do so by doing `{{ _parent }}`. I don't really understand `_parent`, to be honest. My base template frames have no context, so having to make empty structs for them is confusing.)

What's the rationale behind denying this? It's a gigantic blocker for me, and I really want to use askama.

**Comment by jkcclemens** [comment]
Thanks for the quick response!

I'll have to dig into it a little (unless you want to take a look

Unfortunately, it seems like a large feature to look into adding when I'm completely unfamiliar with the codebase, especially if even you would need to dig into it, so I'd rather leave it to the professionals. 😃

**Comment by djc** [comment]
Master now implements deep inheritance and the `super()` macro. I'll release a 0.7.0 soon.

**Comment by jkcclemens** [comment]
Ooooh for the first time ever my askama branch compiles! You're the best!

**Comment by djc** [comment]
Note that you also no longer need the `_parent` fields, you can now just use a flattened struct including all the required fields.

**Comment by jmafc** [comment]
I have a base template in a Flask app that I'm porting that has something like the following in the <head>:
```jinja
  {% if page.no_index %}
    <meta name="robots" content="noindex,nofollow">
  {%- else %}
    {%- block meta_x %}{% endblock %}
  {%- endif %}
```
Various other templates then implement the `meta_x` block in at least three different ways. Askama doesn't like it and complains with a message just like the one in the original comment above. The closing/comments in May/June 2018 would lead one to believe that this should not happen, but it appears that although straight nesting of a block inside a block is now allowed, nesting inside an `if` block is not? Is that something that has a workaround (other than putting the `if` inside a `meta_x` block, which in my case would require surgery on almost all templates)?

**Comment by djc** [comment]
Yeah, I think that limitation might still be in place. I guess I was too lazy to write the more generic code that can walk the entire AST, and there's some argument that doing so will incur more compile-time costs. Probably should just fix it anyway. Would you mind filing a new issue about it? (Bonus points if you also want to try your hand at a PR. 😄 The relevant code is here: https://github.com/djc/askama/blob/master/askama_shared/src/heritage.rs#L45.)
