### ISSUE TITLE
Can a child template choose its parent based on a condition?

### ISSUE THREAD

**Issue by PatatasDelPapa** [djc/askama#857]
I'm following a github project that uses axum, htmx and minijinja but I decided to try use askama instead (for fun).
In many of the templates the project do `{% extends "_base.html" if base is defined else "_partial.html" %}` and I couldn't found a way of doing it in askama.
Is there a way a children template can conditionally specify it's parent depending on a value? if not then I believe I have to make 2 templates instead (a base variant and a partial variant)

**Comment by djc** [comment]
Nope, it's resolved at compile-time rather than at run-time.

**Comment by PatatasDelPapa** [comment]
I see thanks for the answer
