### ISSUE TITLE
Fuzzing askama_parser results in panic

### ISSUE THREAD

**Issue by manunio** [djc/askama#860]
Hi, fuzzing `askama_parser` resulted in panic at following line.
https://github.com/djc/askama/blob/43e92aa3b6b9cd967a70bd0fd54d1f087d6ed76b/askama_parser/src/expr.rs#L290
I suppose it happens because crash input contains Cyrillic letters which are multi-byte and we need exact byte indices to avoid such panic in `[..]` notation.
```rust
#[test]
fn testing() {
    let d = "{eeuuu{b&{!!&{!!11{{
        0!(!1q҄א!)!!!!!!n!";
    if let Ok(_) = Ast::from_str(d, &Syntax::default()) {}
}
```
```
running 1 test
thread 'tests::testing' panicked at 'byte index 6 is not a char boundary; it is inside 'א' (bytes 5..7) of `!1q҄א!)!!!!!!n!`', askama_parser/src/expr.rs:290:22
stack backtrace:
```

**Comment by djc** [comment]
Hah, figured that would be the next question. Yes, sounds good!
