### ISSUE TITLE
askama_derive update breaks filter usage with spaces

### ISSUE THREAD

**Issue by Atrox** [djc/askama#872]
My crate failed to build after updating `askama` from `v0.12.0` to `v0.12.1` and `askama_derive` from `v0.12.1` to `v0.12.2`.

The following doesn't work anymore after the update: `{{ item.field() | safe }}`
It successfully compiles again after removing the spaces: `{{ item.field()|safe }}`

**Comment by Kijewski** [comment]
This is actually working as intended™. In a filter expression you must not put spaces before the pipe `|`. This fact was always stated in [the book](https://djc.github.io/askama/filters.html), but due to minor implementation errors you code worked before, when it actually shouldn't have.

**Comment by Atrox** [comment]
Gotcha, thank you. Skipped that part in the book apparently and got lucky until now :).
