### ISSUE TITLE
question: xml templates support

### ISSUE THREAD

**Issue by GlennWSo** [djc/askama#876]
Does aska a work with xml templates?
Jinja can be used for xml templates.

My use case is hxml templates for the hyperview(think htmx but for native apps) framework

**Comment by djc** [comment]
Sure, Askama doesn't have much knowledge about HTML itself other than basic escaping rules (for which I think you can basically use the same stuff in XML). I know people are using it for source code and LaTeX, for example.

**Comment by GlennWSo** [comment]
That sounds very promising, I think this resolves the question. Thanks
