### ISSUE TITLE
Conditional compiling?

### ISSUE THREAD

**Issue by b1ek** [djc/askama#884]
I like to print out debug info like this:

```rs
#[cfg(debug_assertions)] {
    log::debug!("debug info here");
}
```

This helps optimize out the production build, especially with debug-only crates.  
Thing is, is it possible to use these macros in templates? There is not a word about that functionality in [Template syntax](https://djc.github.io/askama/template_syntax.html)

**Comment by Kijewski** [comment]
That's not possible, but you could simply have a macro in the scope of your `#[derive(Template)]`:

```rust
macro_rules! log_debug {
    ($($tt:tt)*) => {{
        #[cfg(debug_assertions)] {
            ::log::debug!($($tt)*);
        }
    }}
}
```

```jinja2
{% call log_debug!("debug info here") %}
```

**Comment by b1ek** [comment]
> That's not possible, but you could simply have a macro in the scope of your `#[derive(Template)]`:
> 
> ```rust
> macro_rules! log_debug {
>     ($($tt:tt)*) => {{
>         #[cfg(debug_assertions)] {
>             ::log::debug!($($tt)*);
>         }
>     }}
> }
> ```
> 
> ```
> {% call log_debug!("debug info here") %}
> ```

I see, that would do pretty much what i described.

However, in the template i would want to print the info into the template, like this:

```html
<!--
  Memory: 0.2/16GB Available
  Chrome memory usage: 14GB
-->
```

```askama
{% cfg(debug_assertions) %}
    blah blah blah
{% endcfg %}
```

Is that kind of syntax possible? It is not described anywhere in the docs. The thing is i want that code to be completely excluded from the production build, as it gets rather massive over time

**Comment by Kijewski** [comment]
I think this should work:

```jinja2
{% if cfg!(debug_assertions) %}
    blah blah blah
{% endif %}
```

**Comment by b1ek** [comment]
> I think this should work:
> 
> ```
> {% if cfg!(debug_assertions) %}
>     blah blah blah
> {% endif %}
> ```

Thanks, i will try! Not sure that this will compile out the code tho, but it might work

**Comment by b1ek** [comment]
Yup, that did work and that code is compiled out. Thanks!
