### ISSUE TITLE
Allow to have named arguments in macro

### ISSUE THREAD

**Issue by GuillaumeGomez** [djc/askama#885]
It'd pretty nice to be able to have named arguments. For example:

```
{% macro menu_link(href, text, target) %}
...
{% endmacro menu_link %}
```

Then to be able to call it like this:

```
{% menu_link(href="/something", text="link", target="_blank") %}
```

It makes the code much better when reading it.

As a first step, only allowing it for macros would be nice, but potentially extending it to filters would be nice too.

**Comment by djc** [comment]
I worry that this would be a little foreign to users -- that is, I'm not sure it passes the design test of "it should be obvious how this gets compiled to Rust code".

**Comment by GuillaumeGomez** [comment]
Does it really matter? If this is a big enough concern, we can add a new entry in the askama book explaining how it is generated.

**Comment by djc** [comment]
It matters to me -- I think an important design aspect of the templating language for Askama is that people can reason about how their template code gets translated into Rust code. Why don't you write the paragraph that explains this first and we can see how that looks?

**Comment by GuillaumeGomez** [comment]
Sure. I'll do that (hopefully) soon.

**Comment by GuillaumeGomez** [comment]
So now that #893 is merged, let's come back to this. :laughing: 

So I had in mind to keep a `Vec<String>` for each macro where each element is a macro argument name. Then when we encounter a macro with named arguments (should we allw to have a mix between named and not named?), we store the expression into a variable in the same order as declared in the template (so the "computation order" remains the same) and then pass the variables in the correct order to the macro.

Does this sound like an acceptable approach?
