### ISSUE TITLE
lifetime name must start with apostrophe as in "'a", got "r"

### ISSUE THREAD

**Issue by jebrosen** [djc/askama#89]
I am following the master branch of askama and encountered the following error:

```
error: proc-macro derive panicked
 --> src/templates.rs:6:10
  |
6 | #[derive(Template)]
  |          ^^^^^^^^
  |
  = help: message: lifetime name must start with apostrophe as in "'a", got "r"
```

Changing https://github.com/djc/askama/blob/master/askama_derive/src/generator.rs#L295 to `let lifetime = syn::Lifetime::new("'r", Span::call_site());` (with the apostrophe) resolved it.

**Comment by djc** [comment]
Ohh, that's stupid, thanks for letting me know. Master should work again now!
