### ISSUE TITLE
How could i get session flash message in a view after redirect 

### ISSUE THREAD

**Issue by HosMercury** [djc/askama#914]
Askama is impressive 

thanx for doing that great template engine ...

when getting a view after redirect 

how could I globally get the session data ( to use as a flash message )

should be added in the base.html to check if there is a flash_message then show it/them otherwise nothing

**Comment by djc** [comment]
This doesn't really seem to have any bearing on Askama specifically. You should figure out the right way to get the data into the Askama context type, then Askama can take care of rendering it for you.

**Comment by HosMercury** [comment]
I still think we have to have locals
