### ISSUE TITLE
Composing templates 

### ISSUE THREAD

**Issue by dev-ardi** [djc/askama#939]
I haven't seen an easy way of placing one template inside of another. This is really useful for code reuse

**Comment by GuillaumeGomez** [comment]
Please provide an example of what you'd like to have because it's not very clear what you want exactly (at least to me).

**Comment by djc** [comment]
Have you read the [book](https://djc.github.io/askama)? There is template inheritance, there are includes and macros. Seems like there are plenty of ways of composing templates to me.

**Comment by dev-ardi** [comment]
Thanks for pointing it out!
