### ISSUE TITLE
Use of the match syntax requires Deref in scope

### ISSUE THREAD

**Issue by jkcclemens** [djc/askama#94]
In order to match in templates, `std::ops::Deref` must be in scope. 

Otherwise, confusing errors abound:

```
error[E0599]: no method named `deref` found for type `&std::option::Option<std::string::String>` in the current scope
 --> webserver/src/routes/web/base.rs:7:10
  |
7 | #[derive(Template)]
  |          ^^^^^^^^
  |
  = help: items from traits can only be used if the trait is in scope
  = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
          `use lazy_static::Deref;`
```

This issue is two-part:

1. I don't think this should be necessary. The more imports that have seemingly no use in the actual code, the less clear the code is.
2. Until it isn't necessary, it should be documented.

**Comment by djc** [comment]
Can you add a minimal test case? IIRC we already import an aliased Deref in relevant scopes to prevent this sort of issue.

**Comment by jkcclemens** [comment]
I made [a repo](https://github.com/jkcclemens/askama_deref).

**Comment by djc** [comment]
Your example repo works with master after 70fc6d2, thanks for reporting!
