### ISSUE TITLE
Document the `fmt` filter

### ISSUE THREAD

**Issue by Kijewski** [djc/askama#945]
Looking at [the generator code](https://github.com/djc/askama/blob/1ee067f2b62a994fe1200fba8898e8909acd0ce0/askama_derive/src/generator.rs#L1318) I cannot tell, and it is not documented in the book. ~~The code ensures that no more than 2 arguments are given (the first argument being the left-hand side of the pipe), but the second argument in `…|fmt(second)` is never used anyway.~~

~~Is this filter simply a broken copy of `…|format`?~~

**Comment by Kijewski** [comment]
Ah, git blame told me it's related to #345. Also, I did not read the code properly, the argument is used.

**Comment by djc** [comment]
So any questions/concerns left here?

**Comment by Kijewski** [comment]
Yeah, the documentation is still missing.
