### ISSUE TITLE
Can't render simple template. Axum integration.

### ISSUE THREAD

**Issue by sergeda** [djc/askama#948]
I've followed the docs and defined a struct for the template:
```#[derive(Template)]
#[template(path = "sites.html")]
struct SitesTemplate {
    sites: Vec<SiteModel>,
}
```
Function:
```
async fn sites() -> SitesTemplate {
    SitesTemplate {sites: vec!(SiteModel{id: Uuid::new_v4(), domain: "".to_string()})}
}
```
And route:
```
    let app = Router::new()
        .route("/sites", get(sites));
```
I'm getting error:
> .route("/sites", get(sites));
>     |                          --- ^^^^^ the trait `Handler<_, _, _>` is not implemented for fn item `fn() -> impl Future<Output = SitesTemplate> {sites}`

Should I import something for automatic conversion into Response work?
My import:
`askama_axum::Template`

**Comment by djc** [comment]
What version of askama_axum and what version of axum are you depending on? Do you have `derive(Template)` on your `SitesTemplate`?

**Comment by sergeda** [comment]
Oh, I just checked and I was using old version of Axum. Switched to the 7 version and everything works fine now.
