### ISSUE TITLE
Add support for filter section

### ISSUE THREAD

**Issue by GuillaumeGomez** [djc/askama#955]
Would you be open to add support for [filter section](https://jinja.palletsprojects.com/en/3.1.x/templates/#id11)?

**Comment by Kijewski** [comment]
So, this filter first collects all produced text into a buffer, e.g. String, then the collected data is passed to the filter? How does this work with escaped data?

```jinja2
{% filter upper %}
{{ "<script>" }}
{% endfilter %}
```
→
```html
&LT;SCRIPT&GT;
```
because `"<script>"` gets escaped eagerly? Or
```html
&lt;SCRIPT&gt;
```
because the escaping is only done after the whole section was processed?

Could you tell me how you want to use a filter section?

**Comment by GuillaumeGomez** [comment]
I suppose that if we are in "html mode", we want it to be escaped indeed. So generated code would actually look like:

```
let _x = escape_html(format!("<script>"));
```

I need it for the tera to askama migration in docs.rs. Examples:

 * https://github.com/rust-lang/docs.rs/blob/4b3a59af7b7ae4f234537035912acb0adf721b37/templates/crate/build_details.html#L33
 * https://github.com/rust-lang/docs.rs/blob/4b3a59af7b7ae4f234537035912acb0adf721b37/templates/core/about/metadata.html#L17

**Comment by djc** [comment]
I feel like this has come up before, but I can't find any prior issues discussing it.

What alternatives have you come up with?

I don't like it that much, on account of the idea that I don't feel like the code generated it for it is conceptually obvious. But, I can't think of a strong reason to reject it, either... I notice that your use cases are relying on filters we haven't implemented yet (`dedent` and `highlight`), do you have have an implementation for those already?

**Comment by GuillaumeGomez** [comment]
Yes we already have them. Conceptually, I see it as very close as what we do for the rest in general: we generate a `format!` (in a sub-block would be best I think) and call filters on it and "return" the result of all this that we put either in a variable that will be used later on.

**Comment by djc** [comment]
Okay, I'm open to reviewing changes for this. I assume we'll collect, filter, then escape as @Kijewski suggested.
