### ISSUE TITLE
Document how integration should be imported

### ISSUE THREAD

**Issue by nc7s** [djc/askama#961]
The integration section of the "book" looks like this:

> ## {{TARGET}} integration
>
> Enabling the `with-{{target}}` feature appends an implementation of {{target}}'s {{corresponding_trait}} trait for each template type. This makes it easy to trivially return a value of that type in a {{target}} handler.

(repeat for each target)

However, a quick search shows that [you](https://github.com/djc/askama/issues/569#issuecomment-986238576) [need](https://github.com/djc/askama/issues/588#issuecomment-1002212182) [askama_{{target}}](https://github.com/djc/askama/issues/810#issuecomment-1497074654), not askama itself with `with-{{target}}` enabled (or [askama_{{target}} alone](https://github.com/djc/askama/issues/569#issuecomment-986553248)).

On the other hand, the getting started section says nothing more than adding askama itself.

If askama_{{target}} is the canonical way to use integration, maybe document that? I'm happy to PR with some advice on writing alignment.

**Comment by djc** [comment]
Yeah, I guess we didn't update the documentation after the recommendation changes. The recommendation is indeed that you should import directly from askama_{{target}}, though you may also need to import from askama directly. Happy to review a PR along these lines!
