### ISSUE TITLE
div appear with its classes initially in case of an Option

### ISSUE THREAD

**Issue by HosMercury** [djc/askama#968]
Hi, For this code 
```html
{% match messages %} 
  {% when Some with (msgs) %}
        <div class="bg-red-500 text-white border border-red-700 p-2 rounded-xl">
          {% for msg in msgs %}
          <p class="">{{ msg }}</p>
          <br />
          {% endfor %}
        </div>
        {% when None %} 
{% endmatch %}
```

Although the messages var  is an `Option` the div classes appear 
I mean this part always appears as an empty div with a small height and red background.
it should not appear unless there are messages!
```html
        <div class="bg-red-500 text-white border border-red-700 p-2 rounded-xl">
          {% for msg in msgs %}
          <p class="">{{ msg }}</p>
          <br />
          {% endfor %}
        </div>
```
![Screenshot 2024-02-28 at 1 18 14 AM](https://github.com/djc/askama/assets/8302755/2029179a-4fd7-4d29-9e58-530ed0275cd4)

**Comment by Kijewski** [comment]
I guess `msgs` is something like `Some(&[])`? So, even if it's not None, it's empty? Then you have to check for this case `{% if !msgs.is_empty() %} … {% endif %}`.

**Comment by HosMercury** [comment]
although it is of type `Option<Messages>`

https://docs.rs/axum-messages/0.3.0/axum_messages/struct.Messages.html

But anyhow your hack works

**Comment by HosMercury** [comment]
It was my bad
I converted messages to Vec<String> instead of the Option
Checking with is_empty
Worked with empty vec better than Option
As suggested sbove
