### ISSUE TITLE
Conditional HTML attributes

### ISSUE THREAD

**Issue by skaufhold** [djc/askama#971]
I'm trying to add a conditional attribute to a tag inside of a macro. Here's a shortened version of the failing code:

```
<input class="input input-bordered" {% if required %}required{% endif %}/>
```

First, should this work or is it intended to fail to compile?

If I use this version instead, it compiles successfully:

```
{%- if required -%}
<input class="input input-bordered" required />
{%- else -%}
<input class="input input-bordered" />
{%- endif -%}
```

Works for this case I guess, but I can't imagine myself doing this if there is more than one attribute that I want to do this with. Is there any other way to accomplish this?

**Comment by skaufhold** [comment]
The initial error is:

```
error: problems parsing template source at row 21, column 122 near:
       "=\"\" if=\"\" required=\"\" %}required{%=\"\" en"...
```

That's all I have, is there a more detailed message I can get using another way to invoke compilation?

**Comment by GuillaumeGomez** [comment]
Just tested locally and it works perfectly fine:

```rust
use askama::Template;

#[derive(Template)]
#[template(source = r#"
<input class="input input-bordered" {% if required %}required{% endif %}/>
"#, ext = "html")]
struct A {
    required: bool,
}

fn main() {
    let template = A {
        required: true,
    };
    assert_eq!(template.render().unwrap(), "hello")
}
```

I see in your message that you have `if=\"\"` and other things like that. Sounds like you have a syntax error.

**Comment by skaufhold** [comment]
Ohh, you're right, the issue is on my end. There's another tool processing the file before it goes into Askama, modifying things where it shouldn't. That's what's causing the problem. Sorry for the bogus issue, been on this issue for a while but totally didn't think about this possibility.
