### ISSUE TITLE
dynamic rendering based on html

### ISSUE THREAD

**Issue by i1kaaasra** [djc/askama#992]
hello
I want to know that Askama support rendering html on request time not compiled time ?? 
when a user get localhost:3000/?theme="mountain"
I want to get mountain html from server and render it to user
and 
when a user get localhost:3000/?theme="river"
I want to get river html's from server and render it to 

please guide me

**Comment by Kijewski** [comment]
> please guide me

Sure: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started

**Comment by djc** [comment]
In short, you can't -- see #491.
