### ISSUE TITLE
Many missing tags

### ISSUE THREAD

**Issue by paolobarbolini** [djc/askama#995]
While scraping crates.io I've found many tags to be missing on this repository, including the tag for version 0.12.1. Could at least that be added? The exact commit id can be found from https://docs.rs/crate/askama/0.12.1/source/.cargo_vcs_info.json

**Comment by djc** [comment]
Sorry, I had tagged 0.12.1 but failed to push the tag. Also added tags for 0.10.{2,3,4,5}. Apparently the commit distributed as 0.10.1 is no longer around for some reason, so I probably messed that up -- and most of the earlier releases seem to have tags already.
