### ISSUE TITLE
Support endcall

### ISSUE THREAD

**Issue by alexandervantrijffel** [djc/askama#996]
It would be great if endcall is supported to close a call block. I'm using [djlint](https://github.com/djlint/djlint) for formatting html template files. Because endcall is not supported by Askama, the djlint formatter processes call tags as unclosed call blocks which leads to incorrect indenting in files. 

Example:

<img width="889" alt="image" src="https://github.com/djc/askama/assets/994409/ed28b234-36b4-4612-ad39-49b3cbdf0684">

When endcall tags are added the code is correctly indented by djlint:

<img width="820" alt="image" src="https://github.com/djc/askama/assets/994409/734a9cce-d6f0-4f67-97de-4ce94e319d67">

But this is not supported by Askama:

<img width="1331" alt="image" src="https://github.com/djc/askama/assets/994409/09d1c016-cec9-4123-aeb7-f85079aa5f29">

**Comment by djc** [comment]
Happy to review a PR for this, are you able to submit one?

**Comment by alexandervantrijffel** [comment]
For ensuring backwards compatibility, a approach could be:

Let the Call node scan nodes until it finds either an endcall tag, a call tag or until it reaches the end of the document. If a call tag or the end of the document if found before an endcall tag, treat this call node as an unclosed call block. If an endcall tag is found, it's a valid call block.

I've tried to implement this in node.rs but didn't figure it out yet as I am not familiar with nom. 

At least I did write [a test case](https://github.com/djc/askama/commit/8d6ab6b5ce4003f65316ee58cbc69c0bfc041d02) for this, perhaps that helps:

**Comment by Kijewski** [comment]
>Not entirely clear to me what they do -- they pass the content of the block to the macro as the first/last argument?

The called macro can use `{{ caller() }}` to insert the concent between `{%call%}` and `{%endcall%}` of the caller.

If a macro `{% call(arg1) macro1() %}` calls `{{ call macro2() }}`, then macro2 can pass an argument `arg1` back to the body of macro1.

**Comment by djc** [comment]
Pff, that seems like a lot of complexity that seems like a bad fit for Askama.

**Comment by antifuchs** [comment]
I ran into this as well (and imagine how happy I was to find djlint, which seems like the only tool that's semi-reasonably able to indent askama's syntax), and found [the `"ignore_blocks": "call"` djlint directive](https://www.djlint.com/docs/configuration/#ignore-blocks), which I treats `call` blocks correctly, by letting djlint know that it's not a block that needs indentation.

**Comment by alexandervantrijffel** [comment]
Ignoring the call block is indeed a solution to my issue @antifuchs , thanks for sharing!

@maintainers feel free to close this issue if you like.
